// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: common/metrics.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Aggregation int32

const (
	// Hour.
	Aggregation_HOUR Aggregation = 0
	// Day.
	Aggregation_DAY Aggregation = 1
	// Month.
	Aggregation_MONTH Aggregation = 2
	// Minute.
	Aggregation_MINUTE Aggregation = 3
)

// Enum value maps for Aggregation.
var (
	Aggregation_name = map[int32]string{
		0: "HOUR",
		1: "DAY",
		2: "MONTH",
		3: "MINUTE",
	}
	Aggregation_value = map[string]int32{
		"HOUR":   0,
		"DAY":    1,
		"MONTH":  2,
		"MINUTE": 3,
	}
)

func (x Aggregation) Enum() *Aggregation {
	p := new(Aggregation)
	*p = x
	return p
}

func (x Aggregation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Aggregation) Descriptor() protoreflect.EnumDescriptor {
	return file_common_metrics_proto_enumTypes[0].Descriptor()
}

func (Aggregation) Type() protoreflect.EnumType {
	return &file_common_metrics_proto_enumTypes[0]
}

func (x Aggregation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Aggregation.Descriptor instead.
func (Aggregation) EnumDescriptor() ([]byte, []int) {
	return file_common_metrics_proto_rawDescGZIP(), []int{0}
}

type MetricKind int32

const (
	// Incrementing counters that never decrease (these are not reset on each
	// reading).
	MetricKind_COUNTER MetricKind = 0
	// Counters that do get reset upon reading.
	MetricKind_ABSOLUTE MetricKind = 1
	// E.g. a temperature value.
	MetricKind_GAUGE MetricKind = 2
)

// Enum value maps for MetricKind.
var (
	MetricKind_name = map[int32]string{
		0: "COUNTER",
		1: "ABSOLUTE",
		2: "GAUGE",
	}
	MetricKind_value = map[string]int32{
		"COUNTER":  0,
		"ABSOLUTE": 1,
		"GAUGE":    2,
	}
)

func (x MetricKind) Enum() *MetricKind {
	p := new(MetricKind)
	*p = x
	return p
}

func (x MetricKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricKind) Descriptor() protoreflect.EnumDescriptor {
	return file_common_metrics_proto_enumTypes[1].Descriptor()
}

func (MetricKind) Type() protoreflect.EnumType {
	return &file_common_metrics_proto_enumTypes[1]
}

func (x MetricKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricKind.Descriptor instead.
func (MetricKind) EnumDescriptor() ([]byte, []int) {
	return file_common_metrics_proto_rawDescGZIP(), []int{1}
}

type Metric struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Timestamps.
	Timestamps []*timestamppb.Timestamp `protobuf:"bytes,2,rep,name=timestamps,proto3" json:"timestamps,omitempty"`
	// Datasets.
	Datasets []*MetricDataset `protobuf:"bytes,3,rep,name=datasets,proto3" json:"datasets,omitempty"`
	// Kind.
	Kind          MetricKind `protobuf:"varint,4,opt,name=kind,proto3,enum=common.MetricKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_common_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_common_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_common_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *Metric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metric) GetTimestamps() []*timestamppb.Timestamp {
	if x != nil {
		return x.Timestamps
	}
	return nil
}

func (x *Metric) GetDatasets() []*MetricDataset {
	if x != nil {
		return x.Datasets
	}
	return nil
}

func (x *Metric) GetKind() MetricKind {
	if x != nil {
		return x.Kind
	}
	return MetricKind_COUNTER
}

type MetricDataset struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Label.
	Label string `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	// Data.
	// Each value index corresponds with the same timestamp index of the Metric.
	Data          []float32 `protobuf:"fixed32,2,rep,packed,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricDataset) Reset() {
	*x = MetricDataset{}
	mi := &file_common_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricDataset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricDataset) ProtoMessage() {}

func (x *MetricDataset) ProtoReflect() protoreflect.Message {
	mi := &file_common_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricDataset.ProtoReflect.Descriptor instead.
func (*MetricDataset) Descriptor() ([]byte, []int) {
	return file_common_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *MetricDataset) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *MetricDataset) GetData() []float32 {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_common_metrics_proto protoreflect.FileDescriptor

const file_common_metrics_proto_rawDesc = "" +
	"\n" +
	"\x14common/metrics.proto\x12\x06common\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb3\x01\n" +
	"\x06Metric\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12:\n" +
	"\n" +
	"timestamps\x18\x02 \x03(\v2\x1a.google.protobuf.TimestampR\n" +
	"timestamps\x121\n" +
	"\bdatasets\x18\x03 \x03(\v2\x15.common.MetricDatasetR\bdatasets\x12&\n" +
	"\x04kind\x18\x04 \x01(\x0e2\x12.common.MetricKindR\x04kind\"9\n" +
	"\rMetricDataset\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x12\n" +
	"\x04data\x18\x02 \x03(\x02R\x04data*7\n" +
	"\vAggregation\x12\b\n" +
	"\x04HOUR\x10\x00\x12\a\n" +
	"\x03DAY\x10\x01\x12\t\n" +
	"\x05MONTH\x10\x02\x12\n" +
	"\n" +
	"\x06MINUTE\x10\x03*2\n" +
	"\n" +
	"MetricKind\x12\v\n" +
	"\aCOUNTER\x10\x00\x12\f\n" +
	"\bABSOLUTE\x10\x01\x12\t\n" +
	"\x05GAUGE\x10\x02B\xb6\x01\n" +
	"\x11io.splitstack.apiB\fMetricsProtoP\x01Z7github.com/SplitStackServer/splitstack/api/go/v5/common\xaa\x02\x17SplitStackServer.Common\xca\x02\x17SplitStackServer\\Common\xe2\x02#GPBMetadata\\SplitStackServer\\Commonb\x06proto3"

var (
	file_common_metrics_proto_rawDescOnce sync.Once
	file_common_metrics_proto_rawDescData []byte
)

func file_common_metrics_proto_rawDescGZIP() []byte {
	file_common_metrics_proto_rawDescOnce.Do(func() {
		file_common_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_metrics_proto_rawDesc), len(file_common_metrics_proto_rawDesc)))
	})
	return file_common_metrics_proto_rawDescData
}

var file_common_metrics_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_common_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_metrics_proto_goTypes = []any{
	(Aggregation)(0),              // 0: common.Aggregation
	(MetricKind)(0),               // 1: common.MetricKind
	(*Metric)(nil),                // 2: common.Metric
	(*MetricDataset)(nil),         // 3: common.MetricDataset
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_common_metrics_proto_depIdxs = []int32{
	4, // 0: common.Metric.timestamps:type_name -> google.protobuf.Timestamp
	3, // 1: common.Metric.datasets:type_name -> common.MetricDataset
	1, // 2: common.Metric.kind:type_name -> common.MetricKind
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_common_metrics_proto_init() }
func file_common_metrics_proto_init() {
	if File_common_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_metrics_proto_rawDesc), len(file_common_metrics_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_metrics_proto_goTypes,
		DependencyIndexes: file_common_metrics_proto_depIdxs,
		EnumInfos:         file_common_metrics_proto_enumTypes,
		MessageInfos:      file_common_metrics_proto_msgTypes,
	}.Build()
	File_common_metrics_proto = out.File
	file_common_metrics_proto_goTypes = nil
	file_common_metrics_proto_depIdxs = nil
}
