// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: bs/certificate.proto

package bs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CertificateValidationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Certificate serial (hex string)
	Serial string `protobuf:"bytes,1,opt,name=serial,proto3" json:"serial,omitempty"`
	// Basestation EUI64 (hex string)
	BsEui string `protobuf:"bytes,2,opt,name=bs_eui,json=bsEui,proto3" json:"bs_eui,omitempty"`
	// Timestamp of the validation request
	Ts            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=ts,proto3" json:"ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertificateValidationRequest) Reset() {
	*x = CertificateValidationRequest{}
	mi := &file_bs_certificate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateValidationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateValidationRequest) ProtoMessage() {}

func (x *CertificateValidationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bs_certificate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateValidationRequest.ProtoReflect.Descriptor instead.
func (*CertificateValidationRequest) Descriptor() ([]byte, []int) {
	return file_bs_certificate_proto_rawDescGZIP(), []int{0}
}

func (x *CertificateValidationRequest) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *CertificateValidationRequest) GetBsEui() string {
	if x != nil {
		return x.BsEui
	}
	return ""
}

func (x *CertificateValidationRequest) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

// Incremental revocation update (single certificate)
// Published to: cert/status/update
type CertificateValidationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Certificate serial (hex string)
	Serial string `protobuf:"bytes,1,opt,name=serial,proto3" json:"serial,omitempty"`
	// Basestation EUI64 (hex string)
	BsEui string `protobuf:"bytes,2,opt,name=bs_eui,json=bsEui,proto3" json:"bs_eui,omitempty"`
	// True if the certificate is valid, false if revoked
	Valid bool `protobuf:"varint,3,opt,name=valid,proto3" json:"valid,omitempty"`
	// Reason for revocation, if applicable
	Reason *string `protobuf:"bytes,4,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	// Timestamp of the validation response
	Ts            *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=ts,proto3" json:"ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertificateValidationResponse) Reset() {
	*x = CertificateValidationResponse{}
	mi := &file_bs_certificate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateValidationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateValidationResponse) ProtoMessage() {}

func (x *CertificateValidationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bs_certificate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateValidationResponse.ProtoReflect.Descriptor instead.
func (*CertificateValidationResponse) Descriptor() ([]byte, []int) {
	return file_bs_certificate_proto_rawDescGZIP(), []int{1}
}

func (x *CertificateValidationResponse) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *CertificateValidationResponse) GetBsEui() string {
	if x != nil {
		return x.BsEui
	}
	return ""
}

func (x *CertificateValidationResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *CertificateValidationResponse) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

func (x *CertificateValidationResponse) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

var File_bs_certificate_proto protoreflect.FileDescriptor

const file_bs_certificate_proto_rawDesc = "" +
	"\n" +
	"\x14bs/certificate.proto\x12\x02bs\x1a\x1fgoogle/protobuf/timestamp.proto\"y\n" +
	"\x1cCertificateValidationRequest\x12\x16\n" +
	"\x06serial\x18\x01 \x01(\tR\x06serial\x12\x15\n" +
	"\x06bs_eui\x18\x02 \x01(\tR\x05bsEui\x12*\n" +
	"\x02ts\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\"\xb8\x01\n" +
	"\x1dCertificateValidationResponse\x12\x16\n" +
	"\x06serial\x18\x01 \x01(\tR\x06serial\x12\x15\n" +
	"\x06bs_eui\x18\x02 \x01(\tR\x05bsEui\x12\x14\n" +
	"\x05valid\x18\x03 \x01(\bR\x05valid\x12\x1b\n" +
	"\x06reason\x18\x04 \x01(\tH\x00R\x06reason\x88\x01\x01\x12*\n" +
	"\x02ts\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x02tsB\t\n" +
	"\a_reasonB\xca\x01\n" +
	"\x14io.splitstack.api.bsB\x10CertificateProtoP\x01Z5github.com/SplitStackServer/splitstack-grpc-api/go/bs\xaa\x02\x1cSplitStackServer.Basestation\xca\x02\x1cSplitStackServer\\Basestation\xe2\x02(GPBMetadata\\SplitStackServer\\Basestationb\x06proto3"

var (
	file_bs_certificate_proto_rawDescOnce sync.Once
	file_bs_certificate_proto_rawDescData []byte
)

func file_bs_certificate_proto_rawDescGZIP() []byte {
	file_bs_certificate_proto_rawDescOnce.Do(func() {
		file_bs_certificate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bs_certificate_proto_rawDesc), len(file_bs_certificate_proto_rawDesc)))
	})
	return file_bs_certificate_proto_rawDescData
}

var file_bs_certificate_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bs_certificate_proto_goTypes = []any{
	(*CertificateValidationRequest)(nil),  // 0: bs.CertificateValidationRequest
	(*CertificateValidationResponse)(nil), // 1: bs.CertificateValidationResponse
	(*timestamppb.Timestamp)(nil),         // 2: google.protobuf.Timestamp
}
var file_bs_certificate_proto_depIdxs = []int32{
	2, // 0: bs.CertificateValidationRequest.ts:type_name -> google.protobuf.Timestamp
	2, // 1: bs.CertificateValidationResponse.ts:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_bs_certificate_proto_init() }
func file_bs_certificate_proto_init() {
	if File_bs_certificate_proto != nil {
		return
	}
	file_bs_certificate_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bs_certificate_proto_rawDesc), len(file_bs_certificate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bs_certificate_proto_goTypes,
		DependencyIndexes: file_bs_certificate_proto_depIdxs,
		MessageInfos:      file_bs_certificate_proto_msgTypes,
	}.Build()
	File_bs_certificate_proto = out.File
	file_bs_certificate_proto_goTypes = nil
	file_bs_certificate_proto_depIdxs = nil
}
