// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: api/application_integration.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ApplicationIntegrationService_CreateApplicationIntegration_FullMethodName     = "/api.ApplicationIntegrationService/CreateApplicationIntegration"
	ApplicationIntegrationService_GetApplicationIntegration_FullMethodName        = "/api.ApplicationIntegrationService/GetApplicationIntegration"
	ApplicationIntegrationService_UpdateApplicationIntegration_FullMethodName     = "/api.ApplicationIntegrationService/UpdateApplicationIntegration"
	ApplicationIntegrationService_DeleteApplicationIntegration_FullMethodName     = "/api.ApplicationIntegrationService/DeleteApplicationIntegration"
	ApplicationIntegrationService_ListApplicationIntegrations_FullMethodName      = "/api.ApplicationIntegrationService/ListApplicationIntegrations"
	ApplicationIntegrationService_GetApplicationIntegrationToken_FullMethodName   = "/api.ApplicationIntegrationService/GetApplicationIntegrationToken"
	ApplicationIntegrationService_ResetApplicationIntegrationToken_FullMethodName = "/api.ApplicationIntegrationService/ResetApplicationIntegrationToken"
)

// ApplicationIntegrationServiceClient is the client API for ApplicationIntegrationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ApplicationIntegrationService is the service providing API methods for managing applications.
type ApplicationIntegrationServiceClient interface {
	// Create creates the given integration for an application.
	CreateApplicationIntegration(ctx context.Context, in *CreateApplicationIntegrationRequest, opts ...grpc.CallOption) (*CreateApplicationIntegrationResponse, error)
	// Get the application for the given ID.
	GetApplicationIntegration(ctx context.Context, in *GetApplicationIntegrationRequest, opts ...grpc.CallOption) (*GetApplicationIntegrationResponse, error)
	// Update updates the given application.
	UpdateApplicationIntegration(ctx context.Context, in *UpdateApplicationIntegrationRequest, opts ...grpc.CallOption) (*UpdateApplicationIntegrationResponse, error)
	// Delete the application for the given ID.
	DeleteApplicationIntegration(ctx context.Context, in *DeleteApplicationIntegrationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Get the list of applications.
	ListApplicationIntegrations(ctx context.Context, in *ListApplicationIntegrationsRequest, opts ...grpc.CallOption) (*ListApplicationIntegrationsResponse, error)
	// Get the application integration token.
	GetApplicationIntegrationToken(ctx context.Context, in *GetApplicationIntegrationTokenRequest, opts ...grpc.CallOption) (*ApplicationIntegrationTokenResponse, error)
	// Reset the application integration token.
	ResetApplicationIntegrationToken(ctx context.Context, in *ResetApplicationIntegrationTokenRequest, opts ...grpc.CallOption) (*ApplicationIntegrationTokenResponse, error)
}

type applicationIntegrationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewApplicationIntegrationServiceClient(cc grpc.ClientConnInterface) ApplicationIntegrationServiceClient {
	return &applicationIntegrationServiceClient{cc}
}

func (c *applicationIntegrationServiceClient) CreateApplicationIntegration(ctx context.Context, in *CreateApplicationIntegrationRequest, opts ...grpc.CallOption) (*CreateApplicationIntegrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateApplicationIntegrationResponse)
	err := c.cc.Invoke(ctx, ApplicationIntegrationService_CreateApplicationIntegration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationIntegrationServiceClient) GetApplicationIntegration(ctx context.Context, in *GetApplicationIntegrationRequest, opts ...grpc.CallOption) (*GetApplicationIntegrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetApplicationIntegrationResponse)
	err := c.cc.Invoke(ctx, ApplicationIntegrationService_GetApplicationIntegration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationIntegrationServiceClient) UpdateApplicationIntegration(ctx context.Context, in *UpdateApplicationIntegrationRequest, opts ...grpc.CallOption) (*UpdateApplicationIntegrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateApplicationIntegrationResponse)
	err := c.cc.Invoke(ctx, ApplicationIntegrationService_UpdateApplicationIntegration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationIntegrationServiceClient) DeleteApplicationIntegration(ctx context.Context, in *DeleteApplicationIntegrationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ApplicationIntegrationService_DeleteApplicationIntegration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationIntegrationServiceClient) ListApplicationIntegrations(ctx context.Context, in *ListApplicationIntegrationsRequest, opts ...grpc.CallOption) (*ListApplicationIntegrationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListApplicationIntegrationsResponse)
	err := c.cc.Invoke(ctx, ApplicationIntegrationService_ListApplicationIntegrations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationIntegrationServiceClient) GetApplicationIntegrationToken(ctx context.Context, in *GetApplicationIntegrationTokenRequest, opts ...grpc.CallOption) (*ApplicationIntegrationTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplicationIntegrationTokenResponse)
	err := c.cc.Invoke(ctx, ApplicationIntegrationService_GetApplicationIntegrationToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationIntegrationServiceClient) ResetApplicationIntegrationToken(ctx context.Context, in *ResetApplicationIntegrationTokenRequest, opts ...grpc.CallOption) (*ApplicationIntegrationTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplicationIntegrationTokenResponse)
	err := c.cc.Invoke(ctx, ApplicationIntegrationService_ResetApplicationIntegrationToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApplicationIntegrationServiceServer is the server API for ApplicationIntegrationService service.
// All implementations must embed UnimplementedApplicationIntegrationServiceServer
// for forward compatibility.
//
// ApplicationIntegrationService is the service providing API methods for managing applications.
type ApplicationIntegrationServiceServer interface {
	// Create creates the given integration for an application.
	CreateApplicationIntegration(context.Context, *CreateApplicationIntegrationRequest) (*CreateApplicationIntegrationResponse, error)
	// Get the application for the given ID.
	GetApplicationIntegration(context.Context, *GetApplicationIntegrationRequest) (*GetApplicationIntegrationResponse, error)
	// Update updates the given application.
	UpdateApplicationIntegration(context.Context, *UpdateApplicationIntegrationRequest) (*UpdateApplicationIntegrationResponse, error)
	// Delete the application for the given ID.
	DeleteApplicationIntegration(context.Context, *DeleteApplicationIntegrationRequest) (*emptypb.Empty, error)
	// Get the list of applications.
	ListApplicationIntegrations(context.Context, *ListApplicationIntegrationsRequest) (*ListApplicationIntegrationsResponse, error)
	// Get the application integration token.
	GetApplicationIntegrationToken(context.Context, *GetApplicationIntegrationTokenRequest) (*ApplicationIntegrationTokenResponse, error)
	// Reset the application integration token.
	ResetApplicationIntegrationToken(context.Context, *ResetApplicationIntegrationTokenRequest) (*ApplicationIntegrationTokenResponse, error)
	mustEmbedUnimplementedApplicationIntegrationServiceServer()
}

// UnimplementedApplicationIntegrationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedApplicationIntegrationServiceServer struct{}

func (UnimplementedApplicationIntegrationServiceServer) CreateApplicationIntegration(context.Context, *CreateApplicationIntegrationRequest) (*CreateApplicationIntegrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateApplicationIntegration not implemented")
}
func (UnimplementedApplicationIntegrationServiceServer) GetApplicationIntegration(context.Context, *GetApplicationIntegrationRequest) (*GetApplicationIntegrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetApplicationIntegration not implemented")
}
func (UnimplementedApplicationIntegrationServiceServer) UpdateApplicationIntegration(context.Context, *UpdateApplicationIntegrationRequest) (*UpdateApplicationIntegrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateApplicationIntegration not implemented")
}
func (UnimplementedApplicationIntegrationServiceServer) DeleteApplicationIntegration(context.Context, *DeleteApplicationIntegrationRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteApplicationIntegration not implemented")
}
func (UnimplementedApplicationIntegrationServiceServer) ListApplicationIntegrations(context.Context, *ListApplicationIntegrationsRequest) (*ListApplicationIntegrationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListApplicationIntegrations not implemented")
}
func (UnimplementedApplicationIntegrationServiceServer) GetApplicationIntegrationToken(context.Context, *GetApplicationIntegrationTokenRequest) (*ApplicationIntegrationTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetApplicationIntegrationToken not implemented")
}
func (UnimplementedApplicationIntegrationServiceServer) ResetApplicationIntegrationToken(context.Context, *ResetApplicationIntegrationTokenRequest) (*ApplicationIntegrationTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetApplicationIntegrationToken not implemented")
}
func (UnimplementedApplicationIntegrationServiceServer) mustEmbedUnimplementedApplicationIntegrationServiceServer() {
}
func (UnimplementedApplicationIntegrationServiceServer) testEmbeddedByValue() {}

// UnsafeApplicationIntegrationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApplicationIntegrationServiceServer will
// result in compilation errors.
type UnsafeApplicationIntegrationServiceServer interface {
	mustEmbedUnimplementedApplicationIntegrationServiceServer()
}

func RegisterApplicationIntegrationServiceServer(s grpc.ServiceRegistrar, srv ApplicationIntegrationServiceServer) {
	// If the following call pancis, it indicates UnimplementedApplicationIntegrationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ApplicationIntegrationService_ServiceDesc, srv)
}

func _ApplicationIntegrationService_CreateApplicationIntegration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateApplicationIntegrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationIntegrationServiceServer).CreateApplicationIntegration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationIntegrationService_CreateApplicationIntegration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationIntegrationServiceServer).CreateApplicationIntegration(ctx, req.(*CreateApplicationIntegrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationIntegrationService_GetApplicationIntegration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApplicationIntegrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationIntegrationServiceServer).GetApplicationIntegration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationIntegrationService_GetApplicationIntegration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationIntegrationServiceServer).GetApplicationIntegration(ctx, req.(*GetApplicationIntegrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationIntegrationService_UpdateApplicationIntegration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateApplicationIntegrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationIntegrationServiceServer).UpdateApplicationIntegration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationIntegrationService_UpdateApplicationIntegration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationIntegrationServiceServer).UpdateApplicationIntegration(ctx, req.(*UpdateApplicationIntegrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationIntegrationService_DeleteApplicationIntegration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteApplicationIntegrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationIntegrationServiceServer).DeleteApplicationIntegration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationIntegrationService_DeleteApplicationIntegration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationIntegrationServiceServer).DeleteApplicationIntegration(ctx, req.(*DeleteApplicationIntegrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationIntegrationService_ListApplicationIntegrations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListApplicationIntegrationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationIntegrationServiceServer).ListApplicationIntegrations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationIntegrationService_ListApplicationIntegrations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationIntegrationServiceServer).ListApplicationIntegrations(ctx, req.(*ListApplicationIntegrationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationIntegrationService_GetApplicationIntegrationToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApplicationIntegrationTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationIntegrationServiceServer).GetApplicationIntegrationToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationIntegrationService_GetApplicationIntegrationToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationIntegrationServiceServer).GetApplicationIntegrationToken(ctx, req.(*GetApplicationIntegrationTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationIntegrationService_ResetApplicationIntegrationToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetApplicationIntegrationTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationIntegrationServiceServer).ResetApplicationIntegrationToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationIntegrationService_ResetApplicationIntegrationToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationIntegrationServiceServer).ResetApplicationIntegrationToken(ctx, req.(*ResetApplicationIntegrationTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ApplicationIntegrationService_ServiceDesc is the grpc.ServiceDesc for ApplicationIntegrationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApplicationIntegrationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.ApplicationIntegrationService",
	HandlerType: (*ApplicationIntegrationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateApplicationIntegration",
			Handler:    _ApplicationIntegrationService_CreateApplicationIntegration_Handler,
		},
		{
			MethodName: "GetApplicationIntegration",
			Handler:    _ApplicationIntegrationService_GetApplicationIntegration_Handler,
		},
		{
			MethodName: "UpdateApplicationIntegration",
			Handler:    _ApplicationIntegrationService_UpdateApplicationIntegration_Handler,
		},
		{
			MethodName: "DeleteApplicationIntegration",
			Handler:    _ApplicationIntegrationService_DeleteApplicationIntegration_Handler,
		},
		{
			MethodName: "ListApplicationIntegrations",
			Handler:    _ApplicationIntegrationService_ListApplicationIntegrations_Handler,
		},
		{
			MethodName: "GetApplicationIntegrationToken",
			Handler:    _ApplicationIntegrationService_GetApplicationIntegrationToken_Handler,
		},
		{
			MethodName: "ResetApplicationIntegrationToken",
			Handler:    _ApplicationIntegrationService_ResetApplicationIntegrationToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/application_integration.proto",
}
