// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api/application.proto

package api

import (
	common "github.com/SplitStackServer/splitstack/api/go/v5/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Application struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Application ID (UUID).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Tenant ID (UUID).
	TenantId string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Application name.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Application description.
	Description *string `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Tags (user defined).
	// These tags can be used to add additional information to the application.
	// These tags are exposed in all the integration events of devices under
	// this application.
	Tags *common.Tags `protobuf:"bytes,5,opt,name=tags,proto3,oneof" json:"tags,omitempty"`
	// Enable variable MAC devices for the application.
	VariableMacEnabled bool `protobuf:"varint,6,opt,name=variable_mac_enabled,json=variableMacEnabled,proto3" json:"variable_mac_enabled,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Application) Reset() {
	*x = Application{}
	mi := &file_api_application_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Application) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Application) ProtoMessage() {}

func (x *Application) ProtoReflect() protoreflect.Message {
	mi := &file_api_application_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Application.ProtoReflect.Descriptor instead.
func (*Application) Descriptor() ([]byte, []int) {
	return file_api_application_proto_rawDescGZIP(), []int{0}
}

func (x *Application) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Application) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Application) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Application) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Application) GetTags() *common.Tags {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Application) GetVariableMacEnabled() bool {
	if x != nil {
		return x.VariableMacEnabled
	}
	return false
}

type ApplicationListItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Application ID (UUID).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Tenant ID (UUID).
	TenantId string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Application name.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Application description.
	Description *string `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Created at timestamp.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last update timestamp.
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Enable variable MAC devices for the application.
	VariableMacEnabled bool `protobuf:"varint,7,opt,name=variable_mac_enabled,json=variableMacEnabled,proto3" json:"variable_mac_enabled,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ApplicationListItem) Reset() {
	*x = ApplicationListItem{}
	mi := &file_api_application_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationListItem) ProtoMessage() {}

func (x *ApplicationListItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_application_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationListItem.ProtoReflect.Descriptor instead.
func (*ApplicationListItem) Descriptor() ([]byte, []int) {
	return file_api_application_proto_rawDescGZIP(), []int{1}
}

func (x *ApplicationListItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApplicationListItem) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ApplicationListItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApplicationListItem) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *ApplicationListItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ApplicationListItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ApplicationListItem) GetVariableMacEnabled() bool {
	if x != nil {
		return x.VariableMacEnabled
	}
	return false
}

type CreateApplicationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant ID (UUID).
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Application name.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Application description.
	Description *string `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Tags (user defined).
	// These tags can be used to add additional information to the application.
	// These tags are exposed in all the integration events of devices under
	// this application.
	Tags *common.Tags `protobuf:"bytes,4,opt,name=tags,proto3,oneof" json:"tags,omitempty"`
	// Enable variable MAC devices for the application.
	VariableMacEnabled bool `protobuf:"varint,5,opt,name=variable_mac_enabled,json=variableMacEnabled,proto3" json:"variable_mac_enabled,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateApplicationRequest) Reset() {
	*x = CreateApplicationRequest{}
	mi := &file_api_application_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateApplicationRequest) ProtoMessage() {}

func (x *CreateApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_application_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateApplicationRequest.ProtoReflect.Descriptor instead.
func (*CreateApplicationRequest) Descriptor() ([]byte, []int) {
	return file_api_application_proto_rawDescGZIP(), []int{2}
}

func (x *CreateApplicationRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateApplicationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateApplicationRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateApplicationRequest) GetTags() *common.Tags {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateApplicationRequest) GetVariableMacEnabled() bool {
	if x != nil {
		return x.VariableMacEnabled
	}
	return false
}

type CreateApplicationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Created Application object.
	Application *Application `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	// Created at timestamp.
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateApplicationResponse) Reset() {
	*x = CreateApplicationResponse{}
	mi := &file_api_application_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateApplicationResponse) ProtoMessage() {}

func (x *CreateApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_application_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateApplicationResponse.ProtoReflect.Descriptor instead.
func (*CreateApplicationResponse) Descriptor() ([]byte, []int) {
	return file_api_application_proto_rawDescGZIP(), []int{3}
}

func (x *CreateApplicationResponse) GetApplication() *Application {
	if x != nil {
		return x.Application
	}
	return nil
}

func (x *CreateApplicationResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetApplicationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Application ID (UUID).
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApplicationRequest) Reset() {
	*x = GetApplicationRequest{}
	mi := &file_api_application_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicationRequest) ProtoMessage() {}

func (x *GetApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_application_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicationRequest.ProtoReflect.Descriptor instead.
func (*GetApplicationRequest) Descriptor() ([]byte, []int) {
	return file_api_application_proto_rawDescGZIP(), []int{4}
}

func (x *GetApplicationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetApplicationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Application object.
	Application *Application `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	// Created at timestamp.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last update timestamp.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApplicationResponse) Reset() {
	*x = GetApplicationResponse{}
	mi := &file_api_application_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicationResponse) ProtoMessage() {}

func (x *GetApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_application_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicationResponse.ProtoReflect.Descriptor instead.
func (*GetApplicationResponse) Descriptor() ([]byte, []int) {
	return file_api_application_proto_rawDescGZIP(), []int{5}
}

func (x *GetApplicationResponse) GetApplication() *Application {
	if x != nil {
		return x.Application
	}
	return nil
}

func (x *GetApplicationResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetApplicationResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type UpdateApplicationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Application ID (UUID).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Application name.
	Name *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// Application description.
	Description *string `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Tags (user defined).
	// These tags can be used to add additional information to the application.
	// These tags are exposed in all the integration events of devices under
	// this application.
	Tags *common.Tags `protobuf:"bytes,4,opt,name=tags,proto3,oneof" json:"tags,omitempty"`
	// Enable variable MAC devices for the application.
	VariableMacEnabled *bool `protobuf:"varint,5,opt,name=variable_mac_enabled,json=variableMacEnabled,proto3,oneof" json:"variable_mac_enabled,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateApplicationRequest) Reset() {
	*x = UpdateApplicationRequest{}
	mi := &file_api_application_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateApplicationRequest) ProtoMessage() {}

func (x *UpdateApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_application_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateApplicationRequest.ProtoReflect.Descriptor instead.
func (*UpdateApplicationRequest) Descriptor() ([]byte, []int) {
	return file_api_application_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateApplicationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateApplicationRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateApplicationRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateApplicationRequest) GetTags() *common.Tags {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdateApplicationRequest) GetVariableMacEnabled() bool {
	if x != nil && x.VariableMacEnabled != nil {
		return *x.VariableMacEnabled
	}
	return false
}

type UpdateApplicationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Application object.
	Application *Application `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	// Created at timestamp.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last update timestamp.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateApplicationResponse) Reset() {
	*x = UpdateApplicationResponse{}
	mi := &file_api_application_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateApplicationResponse) ProtoMessage() {}

func (x *UpdateApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_application_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateApplicationResponse.ProtoReflect.Descriptor instead.
func (*UpdateApplicationResponse) Descriptor() ([]byte, []int) {
	return file_api_application_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateApplicationResponse) GetApplication() *Application {
	if x != nil {
		return x.Application
	}
	return nil
}

func (x *UpdateApplicationResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UpdateApplicationResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type DeleteApplicationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Application ID (UUID).
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteApplicationRequest) Reset() {
	*x = DeleteApplicationRequest{}
	mi := &file_api_application_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteApplicationRequest) ProtoMessage() {}

func (x *DeleteApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_application_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteApplicationRequest.ProtoReflect.Descriptor instead.
func (*DeleteApplicationRequest) Descriptor() ([]byte, []int) {
	return file_api_application_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteApplicationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListApplicationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant ID (UUID) to filter applications on.
	// To list all applications as a global admin user, this field can be left blank.
	TenantId *string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3,oneof" json:"tenant_id,omitempty"`
	// Pagination. Defaults to 100 objects at page index 0.
	Paginator *Paginator `protobuf:"bytes,2,opt,name=paginator,proto3" json:"paginator,omitempty"`
	// If set, the given string will be used to search on name (optional).
	SearchName    *string `protobuf:"bytes,3,opt,name=search_name,json=searchName,proto3,oneof" json:"search_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApplicationsRequest) Reset() {
	*x = ListApplicationsRequest{}
	mi := &file_api_application_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApplicationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApplicationsRequest) ProtoMessage() {}

func (x *ListApplicationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_application_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApplicationsRequest.ProtoReflect.Descriptor instead.
func (*ListApplicationsRequest) Descriptor() ([]byte, []int) {
	return file_api_application_proto_rawDescGZIP(), []int{9}
}

func (x *ListApplicationsRequest) GetTenantId() string {
	if x != nil && x.TenantId != nil {
		return *x.TenantId
	}
	return ""
}

func (x *ListApplicationsRequest) GetPaginator() *Paginator {
	if x != nil {
		return x.Paginator
	}
	return nil
}

func (x *ListApplicationsRequest) GetSearchName() string {
	if x != nil && x.SearchName != nil {
		return *x.SearchName
	}
	return ""
}

type ListApplicationsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pagination.
	Pagination *Pagination `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// Result-set.
	Result        []*ApplicationListItem `protobuf:"bytes,2,rep,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApplicationsResponse) Reset() {
	*x = ListApplicationsResponse{}
	mi := &file_api_application_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApplicationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApplicationsResponse) ProtoMessage() {}

func (x *ListApplicationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_application_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApplicationsResponse.ProtoReflect.Descriptor instead.
func (*ListApplicationsResponse) Descriptor() ([]byte, []int) {
	return file_api_application_proto_rawDescGZIP(), []int{10}
}

func (x *ListApplicationsResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListApplicationsResponse) GetResult() []*ApplicationListItem {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_api_application_proto protoreflect.FileDescriptor

const file_api_application_proto_rawDesc = "" +
	"\n" +
	"\x15api/application.proto\x12\x03api\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x10api/common.proto\x1a\x13common/common.proto\"\xe7\x01\n" +
	"\vApplication\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x00R\vdescription\x88\x01\x01\x12%\n" +
	"\x04tags\x18\x05 \x01(\v2\f.common.TagsH\x01R\x04tags\x88\x01\x01\x120\n" +
	"\x14variable_mac_enabled\x18\x06 \x01(\bR\x12variableMacEnabledB\x0e\n" +
	"\f_descriptionB\a\n" +
	"\x05_tags\"\xb5\x02\n" +
	"\x13ApplicationListItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x00R\vdescription\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x120\n" +
	"\x14variable_mac_enabled\x18\a \x01(\bR\x12variableMacEnabledB\x0e\n" +
	"\f_description\"\xe4\x01\n" +
	"\x18CreateApplicationRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12%\n" +
	"\x04tags\x18\x04 \x01(\v2\f.common.TagsH\x01R\x04tags\x88\x01\x01\x120\n" +
	"\x14variable_mac_enabled\x18\x05 \x01(\bR\x12variableMacEnabledB\x0e\n" +
	"\f_descriptionB\a\n" +
	"\x05_tags\"\x8a\x01\n" +
	"\x19CreateApplicationResponse\x122\n" +
	"\vapplication\x18\x01 \x01(\v2\x10.api.ApplicationR\vapplication\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"'\n" +
	"\x15GetApplicationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xc2\x01\n" +
	"\x16GetApplicationResponse\x122\n" +
	"\vapplication\x18\x01 \x01(\v2\x10.api.ApplicationR\vapplication\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x83\x02\n" +
	"\x18UpdateApplicationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12%\n" +
	"\x04tags\x18\x04 \x01(\v2\f.common.TagsH\x02R\x04tags\x88\x01\x01\x125\n" +
	"\x14variable_mac_enabled\x18\x05 \x01(\bH\x03R\x12variableMacEnabled\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\a\n" +
	"\x05_tagsB\x17\n" +
	"\x15_variable_mac_enabled\"\xc5\x01\n" +
	"\x19UpdateApplicationResponse\x122\n" +
	"\vapplication\x18\x01 \x01(\v2\x10.api.ApplicationR\vapplication\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"*\n" +
	"\x18DeleteApplicationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xad\x01\n" +
	"\x17ListApplicationsRequest\x12 \n" +
	"\ttenant_id\x18\x01 \x01(\tH\x00R\btenantId\x88\x01\x01\x12,\n" +
	"\tpaginator\x18\x02 \x01(\v2\x0e.api.PaginatorR\tpaginator\x12$\n" +
	"\vsearch_name\x18\x03 \x01(\tH\x01R\n" +
	"searchName\x88\x01\x01B\f\n" +
	"\n" +
	"_tenant_idB\x0e\n" +
	"\f_search_name\"}\n" +
	"\x18ListApplicationsResponse\x12/\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x0f.api.PaginationR\n" +
	"pagination\x120\n" +
	"\x06result\x18\x02 \x03(\v2\x18.api.ApplicationListItemR\x06result2\xc0\x04\n" +
	"\x12ApplicationService\x12p\n" +
	"\x11CreateApplication\x12\x1d.api.CreateApplicationRequest\x1a\x1e.api.CreateApplicationResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/applications\x12i\n" +
	"\x0eGetApplication\x12\x1a.api.GetApplicationRequest\x1a\x1b.api.GetApplicationResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/applications/{id}\x12u\n" +
	"\x11UpdateApplication\x12\x1d.api.UpdateApplicationRequest\x1a\x1e.api.UpdateApplicationResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\x1a\x16/api/applications/{id}\x12j\n" +
	"\x11DeleteApplication\x12\x1d.api.DeleteApplicationRequest\x1a\x16.google.protobuf.Empty\"\x1e\x82\xd3\xe4\x93\x02\x18*\x16/api/applications/{id}\x12j\n" +
	"\x10ListApplications\x12\x1c.api.ListApplicationsRequest\x1a\x1d.api.ListApplicationsResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/applicationsB\xae\x01\n" +
	"\x11io.splitstack.apiB\x10ApplicationProtoP\x01Z4github.com/SplitStackServer/splitstack/api/go/v5/api\xaa\x02\x14SplitStackServer.Api\xca\x02\x14SplitStackServer\\Api\xe2\x02 GPBMetadata\\SplitStackServer\\Apib\x06proto3"

var (
	file_api_application_proto_rawDescOnce sync.Once
	file_api_application_proto_rawDescData []byte
)

func file_api_application_proto_rawDescGZIP() []byte {
	file_api_application_proto_rawDescOnce.Do(func() {
		file_api_application_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_application_proto_rawDesc), len(file_api_application_proto_rawDesc)))
	})
	return file_api_application_proto_rawDescData
}

var file_api_application_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_application_proto_goTypes = []any{
	(*Application)(nil),               // 0: api.Application
	(*ApplicationListItem)(nil),       // 1: api.ApplicationListItem
	(*CreateApplicationRequest)(nil),  // 2: api.CreateApplicationRequest
	(*CreateApplicationResponse)(nil), // 3: api.CreateApplicationResponse
	(*GetApplicationRequest)(nil),     // 4: api.GetApplicationRequest
	(*GetApplicationResponse)(nil),    // 5: api.GetApplicationResponse
	(*UpdateApplicationRequest)(nil),  // 6: api.UpdateApplicationRequest
	(*UpdateApplicationResponse)(nil), // 7: api.UpdateApplicationResponse
	(*DeleteApplicationRequest)(nil),  // 8: api.DeleteApplicationRequest
	(*ListApplicationsRequest)(nil),   // 9: api.ListApplicationsRequest
	(*ListApplicationsResponse)(nil),  // 10: api.ListApplicationsResponse
	(*common.Tags)(nil),               // 11: common.Tags
	(*timestamppb.Timestamp)(nil),     // 12: google.protobuf.Timestamp
	(*Paginator)(nil),                 // 13: api.Paginator
	(*Pagination)(nil),                // 14: api.Pagination
	(*emptypb.Empty)(nil),             // 15: google.protobuf.Empty
}
var file_api_application_proto_depIdxs = []int32{
	11, // 0: api.Application.tags:type_name -> common.Tags
	12, // 1: api.ApplicationListItem.created_at:type_name -> google.protobuf.Timestamp
	12, // 2: api.ApplicationListItem.updated_at:type_name -> google.protobuf.Timestamp
	11, // 3: api.CreateApplicationRequest.tags:type_name -> common.Tags
	0,  // 4: api.CreateApplicationResponse.application:type_name -> api.Application
	12, // 5: api.CreateApplicationResponse.created_at:type_name -> google.protobuf.Timestamp
	0,  // 6: api.GetApplicationResponse.application:type_name -> api.Application
	12, // 7: api.GetApplicationResponse.created_at:type_name -> google.protobuf.Timestamp
	12, // 8: api.GetApplicationResponse.updated_at:type_name -> google.protobuf.Timestamp
	11, // 9: api.UpdateApplicationRequest.tags:type_name -> common.Tags
	0,  // 10: api.UpdateApplicationResponse.application:type_name -> api.Application
	12, // 11: api.UpdateApplicationResponse.created_at:type_name -> google.protobuf.Timestamp
	12, // 12: api.UpdateApplicationResponse.updated_at:type_name -> google.protobuf.Timestamp
	13, // 13: api.ListApplicationsRequest.paginator:type_name -> api.Paginator
	14, // 14: api.ListApplicationsResponse.pagination:type_name -> api.Pagination
	1,  // 15: api.ListApplicationsResponse.result:type_name -> api.ApplicationListItem
	2,  // 16: api.ApplicationService.CreateApplication:input_type -> api.CreateApplicationRequest
	4,  // 17: api.ApplicationService.GetApplication:input_type -> api.GetApplicationRequest
	6,  // 18: api.ApplicationService.UpdateApplication:input_type -> api.UpdateApplicationRequest
	8,  // 19: api.ApplicationService.DeleteApplication:input_type -> api.DeleteApplicationRequest
	9,  // 20: api.ApplicationService.ListApplications:input_type -> api.ListApplicationsRequest
	3,  // 21: api.ApplicationService.CreateApplication:output_type -> api.CreateApplicationResponse
	5,  // 22: api.ApplicationService.GetApplication:output_type -> api.GetApplicationResponse
	7,  // 23: api.ApplicationService.UpdateApplication:output_type -> api.UpdateApplicationResponse
	15, // 24: api.ApplicationService.DeleteApplication:output_type -> google.protobuf.Empty
	10, // 25: api.ApplicationService.ListApplications:output_type -> api.ListApplicationsResponse
	21, // [21:26] is the sub-list for method output_type
	16, // [16:21] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_api_application_proto_init() }
func file_api_application_proto_init() {
	if File_api_application_proto != nil {
		return
	}
	file_api_common_proto_init()
	file_api_application_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_application_proto_msgTypes[1].OneofWrappers = []any{}
	file_api_application_proto_msgTypes[2].OneofWrappers = []any{}
	file_api_application_proto_msgTypes[6].OneofWrappers = []any{}
	file_api_application_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_application_proto_rawDesc), len(file_api_application_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_application_proto_goTypes,
		DependencyIndexes: file_api_application_proto_depIdxs,
		MessageInfos:      file_api_application_proto_msgTypes,
	}.Build()
	File_api_application_proto = out.File
	file_api_application_proto_goTypes = nil
	file_api_application_proto_depIdxs = nil
}
