// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api/auth.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Email of the user.
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// Password of the user.
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_api_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The JWT token to use for authentication.
	Jwt           string `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_api_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetJwt() string {
	if x != nil {
		return x.Jwt
	}
	return ""
}

type OpenIdConnectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OpenId Connect callback code.
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// OpenId Connect callback state.
	State         string `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenIdConnectRequest) Reset() {
	*x = OpenIdConnectRequest{}
	mi := &file_api_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenIdConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenIdConnectRequest) ProtoMessage() {}

func (x *OpenIdConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenIdConnectRequest.ProtoReflect.Descriptor instead.
func (*OpenIdConnectRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_proto_rawDescGZIP(), []int{2}
}

func (x *OpenIdConnectRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *OpenIdConnectRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type OpenIdConnectResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Token to use for authentication.
	Token         string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenIdConnectResponse) Reset() {
	*x = OpenIdConnectResponse{}
	mi := &file_api_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenIdConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenIdConnectResponse) ProtoMessage() {}

func (x *OpenIdConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenIdConnectResponse.ProtoReflect.Descriptor instead.
func (*OpenIdConnectResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_proto_rawDescGZIP(), []int{3}
}

func (x *OpenIdConnectResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type OAuth2Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OAuth2 callback code.
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// OAuth2 callback state.
	State         string `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OAuth2Request) Reset() {
	*x = OAuth2Request{}
	mi := &file_api_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuth2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuth2Request) ProtoMessage() {}

func (x *OAuth2Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuth2Request.ProtoReflect.Descriptor instead.
func (*OAuth2Request) Descriptor() ([]byte, []int) {
	return file_api_auth_proto_rawDescGZIP(), []int{4}
}

func (x *OAuth2Request) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *OAuth2Request) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type OAuth2Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Token to use for authentication.
	Token         string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OAuth2Response) Reset() {
	*x = OAuth2Response{}
	mi := &file_api_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuth2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuth2Response) ProtoMessage() {}

func (x *OAuth2Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuth2Response.ProtoReflect.Descriptor instead.
func (*OAuth2Response) Descriptor() ([]byte, []int) {
	return file_api_auth_proto_rawDescGZIP(), []int{5}
}

func (x *OAuth2Response) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_api_auth_proto protoreflect.FileDescriptor

const file_api_auth_proto_rawDesc = "" +
	"\n" +
	"\x0eapi/auth.proto\x12\x03api\x1a\x1cgoogle/api/annotations.proto\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"!\n" +
	"\rLoginResponse\x12\x10\n" +
	"\x03jwt\x18\x01 \x01(\tR\x03jwt\"@\n" +
	"\x14OpenIdConnectRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\"-\n" +
	"\x15OpenIdConnectResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"9\n" +
	"\rOAuth2Request\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\"&\n" +
	"\x0eOAuth2Response\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token2\x96\x02\n" +
	"\vAuthService\x12J\n" +
	"\x05Login\x12\x11.api.LoginRequest\x1a\x12.api.LoginResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/api/auth/login\x12f\n" +
	"\x12OpenIdConnectLogin\x12\x19.api.OpenIdConnectRequest\x1a\x1a.api.OpenIdConnectResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/api/auth/oidc\x12S\n" +
	"\vOAuth2Login\x12\x12.api.OAuth2Request\x1a\x13.api.OAuth2Response\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/auth/oauth2B\xa9\x01\n" +
	"\x11io.splitstack.apiB\tAuthProtoP\x01Z6github.com/SplitStackServer/splitstack-grpc-api/go/api\xaa\x02\x14SplitStackServer.Api\xca\x02\x14SplitStackServer\\Api\xe2\x02 GPBMetadata\\SplitStackServer\\Apib\x06proto3"

var (
	file_api_auth_proto_rawDescOnce sync.Once
	file_api_auth_proto_rawDescData []byte
)

func file_api_auth_proto_rawDescGZIP() []byte {
	file_api_auth_proto_rawDescOnce.Do(func() {
		file_api_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_auth_proto_rawDesc), len(file_api_auth_proto_rawDesc)))
	})
	return file_api_auth_proto_rawDescData
}

var file_api_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_auth_proto_goTypes = []any{
	(*LoginRequest)(nil),          // 0: api.LoginRequest
	(*LoginResponse)(nil),         // 1: api.LoginResponse
	(*OpenIdConnectRequest)(nil),  // 2: api.OpenIdConnectRequest
	(*OpenIdConnectResponse)(nil), // 3: api.OpenIdConnectResponse
	(*OAuth2Request)(nil),         // 4: api.OAuth2Request
	(*OAuth2Response)(nil),        // 5: api.OAuth2Response
}
var file_api_auth_proto_depIdxs = []int32{
	0, // 0: api.AuthService.Login:input_type -> api.LoginRequest
	2, // 1: api.AuthService.OpenIdConnectLogin:input_type -> api.OpenIdConnectRequest
	4, // 2: api.AuthService.OAuth2Login:input_type -> api.OAuth2Request
	1, // 3: api.AuthService.Login:output_type -> api.LoginResponse
	3, // 4: api.AuthService.OpenIdConnectLogin:output_type -> api.OpenIdConnectResponse
	5, // 5: api.AuthService.OAuth2Login:output_type -> api.OAuth2Response
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_auth_proto_init() }
func file_api_auth_proto_init() {
	if File_api_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_auth_proto_rawDesc), len(file_api_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_auth_proto_goTypes,
		DependencyIndexes: file_api_auth_proto_depIdxs,
		MessageInfos:      file_api_auth_proto_msgTypes,
	}.Build()
	File_api_auth_proto = out.File
	file_api_auth_proto_goTypes = nil
	file_api_auth_proto_depIdxs = nil
}
