// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api/basestation.proto

package api

import (
	common "github.com/SplitStackServer/splitstack/api/go/v5/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BasestationState int32

const (
	// The gateway has never sent any data.
	BasestationState_NEVER_SEEN BasestationState = 0
	// Online.
	BasestationState_ONLINE BasestationState = 1
	// Offline.
	BasestationState_OFFLINE BasestationState = 2
)

// Enum value maps for BasestationState.
var (
	BasestationState_name = map[int32]string{
		0: "NEVER_SEEN",
		1: "ONLINE",
		2: "OFFLINE",
	}
	BasestationState_value = map[string]int32{
		"NEVER_SEEN": 0,
		"ONLINE":     1,
		"OFFLINE":    2,
	}
)

func (x BasestationState) Enum() *BasestationState {
	p := new(BasestationState)
	*p = x
	return p
}

func (x BasestationState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BasestationState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_basestation_proto_enumTypes[0].Descriptor()
}

func (BasestationState) Type() protoreflect.EnumType {
	return &file_api_basestation_proto_enumTypes[0]
}

func (x BasestationState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BasestationState.Descriptor instead.
func (BasestationState) EnumDescriptor() ([]byte, []int) {
	return file_api_basestation_proto_rawDescGZIP(), []int{0}
}

type ListBasestationsRequest_OrderBy int32

const (
	ListBasestationsRequest_NAME         ListBasestationsRequest_OrderBy = 0
	ListBasestationsRequest_EUI          ListBasestationsRequest_OrderBy = 1
	ListBasestationsRequest_LAST_SEEN_AT ListBasestationsRequest_OrderBy = 2
	ListBasestationsRequest_CREATED_AT   ListBasestationsRequest_OrderBy = 3
)

// Enum value maps for ListBasestationsRequest_OrderBy.
var (
	ListBasestationsRequest_OrderBy_name = map[int32]string{
		0: "NAME",
		1: "EUI",
		2: "LAST_SEEN_AT",
		3: "CREATED_AT",
	}
	ListBasestationsRequest_OrderBy_value = map[string]int32{
		"NAME":         0,
		"EUI":          1,
		"LAST_SEEN_AT": 2,
		"CREATED_AT":   3,
	}
)

func (x ListBasestationsRequest_OrderBy) Enum() *ListBasestationsRequest_OrderBy {
	p := new(ListBasestationsRequest_OrderBy)
	*p = x
	return p
}

func (x ListBasestationsRequest_OrderBy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListBasestationsRequest_OrderBy) Descriptor() protoreflect.EnumDescriptor {
	return file_api_basestation_proto_enumTypes[1].Descriptor()
}

func (ListBasestationsRequest_OrderBy) Type() protoreflect.EnumType {
	return &file_api_basestation_proto_enumTypes[1]
}

func (x ListBasestationsRequest_OrderBy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListBasestationsRequest_OrderBy.Descriptor instead.
func (ListBasestationsRequest_OrderBy) EnumDescriptor() ([]byte, []int) {
	return file_api_basestation_proto_rawDescGZIP(), []int{10, 0}
}

type Basestation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Basestation ID (UUID).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Basestation EUI64.
	Eui string `protobuf:"bytes,2,opt,name=eui,proto3" json:"eui,omitempty"`
	// Name.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Description.
	Description *string `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Basestation location.
	Location *common.GeoLocation `protobuf:"bytes,5,opt,name=location,proto3,oneof" json:"location,omitempty"`
	// Basestation metadata (set on connection).
	Metadata           *BasestationMetadata `protobuf:"bytes,6,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	UseGpsLocation     bool                 `protobuf:"varint,7,opt,name=use_gps_location,json=useGpsLocation,proto3" json:"use_gps_location,omitempty"`
	VariableMacSupport bool                 `protobuf:"varint,8,opt,name=variable_mac_support,json=variableMacSupport,proto3" json:"variable_mac_support,omitempty"`
	// Tags.
	Tags          *common.Tags `protobuf:"bytes,9,opt,name=tags,proto3,oneof" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Basestation) Reset() {
	*x = Basestation{}
	mi := &file_api_basestation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Basestation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Basestation) ProtoMessage() {}

func (x *Basestation) ProtoReflect() protoreflect.Message {
	mi := &file_api_basestation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Basestation.ProtoReflect.Descriptor instead.
func (*Basestation) Descriptor() ([]byte, []int) {
	return file_api_basestation_proto_rawDescGZIP(), []int{0}
}

func (x *Basestation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Basestation) GetEui() string {
	if x != nil {
		return x.Eui
	}
	return ""
}

func (x *Basestation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Basestation) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Basestation) GetLocation() *common.GeoLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Basestation) GetMetadata() *BasestationMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Basestation) GetUseGpsLocation() bool {
	if x != nil {
		return x.UseGpsLocation
	}
	return false
}

func (x *Basestation) GetVariableMacSupport() bool {
	if x != nil {
		return x.VariableMacSupport
	}
	return false
}

func (x *Basestation) GetTags() *common.Tags {
	if x != nil {
		return x.Tags
	}
	return nil
}

type BasestationListItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant ID.
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Basestation ID (UUID).
	BasestationId string `protobuf:"bytes,2,opt,name=basestation_id,json=basestationId,proto3" json:"basestation_id,omitempty"`
	// Basestation EUI64.
	Eui string `protobuf:"bytes,3,opt,name=eui,proto3" json:"eui,omitempty"`
	// Name.
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// Description.
	Description *string `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Location.
	Location *common.GeoLocation `protobuf:"bytes,6,opt,name=location,proto3,oneof" json:"location,omitempty"`
	// Basestation metadata (set on connection).
	Metadata *BasestationMetadata `protobuf:"bytes,7,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	// Created at timestamp.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last update timestamp.
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Last seen at timestamp.
	LastSeenAt         *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=last_seen_at,json=lastSeenAt,proto3,oneof" json:"last_seen_at,omitempty"`
	VariableMacSupport bool                   `protobuf:"varint,11,opt,name=variable_mac_support,json=variableMacSupport,proto3" json:"variable_mac_support,omitempty"`
	// Basestation state.
	State         BasestationState `protobuf:"varint,12,opt,name=state,proto3,enum=api.BasestationState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasestationListItem) Reset() {
	*x = BasestationListItem{}
	mi := &file_api_basestation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasestationListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasestationListItem) ProtoMessage() {}

func (x *BasestationListItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_basestation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasestationListItem.ProtoReflect.Descriptor instead.
func (*BasestationListItem) Descriptor() ([]byte, []int) {
	return file_api_basestation_proto_rawDescGZIP(), []int{1}
}

func (x *BasestationListItem) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *BasestationListItem) GetBasestationId() string {
	if x != nil {
		return x.BasestationId
	}
	return ""
}

func (x *BasestationListItem) GetEui() string {
	if x != nil {
		return x.Eui
	}
	return ""
}

func (x *BasestationListItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BasestationListItem) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *BasestationListItem) GetLocation() *common.GeoLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *BasestationListItem) GetMetadata() *BasestationMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *BasestationListItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *BasestationListItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *BasestationListItem) GetLastSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenAt
	}
	return nil
}

func (x *BasestationListItem) GetVariableMacSupport() bool {
	if x != nil {
		return x.VariableMacSupport
	}
	return false
}

func (x *BasestationListItem) GetState() BasestationState {
	if x != nil {
		return x.State
	}
	return BasestationState_NEVER_SEEN
}

type BasestationMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Vendor.
	Vendor *string `protobuf:"bytes,1,opt,name=vendor,proto3,oneof" json:"vendor,omitempty"`
	// Model.
	Model *string `protobuf:"bytes,2,opt,name=model,proto3,oneof" json:"model,omitempty"`
	// Alias.
	Alias *string `protobuf:"bytes,3,opt,name=alias,proto3,oneof" json:"alias,omitempty"`
	// Software version.
	SwVersion     *string `protobuf:"bytes,4,opt,name=sw_version,json=swVersion,proto3,oneof" json:"sw_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasestationMetadata) Reset() {
	*x = BasestationMetadata{}
	mi := &file_api_basestation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasestationMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasestationMetadata) ProtoMessage() {}

func (x *BasestationMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_basestation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasestationMetadata.ProtoReflect.Descriptor instead.
func (*BasestationMetadata) Descriptor() ([]byte, []int) {
	return file_api_basestation_proto_rawDescGZIP(), []int{2}
}

func (x *BasestationMetadata) GetVendor() string {
	if x != nil && x.Vendor != nil {
		return *x.Vendor
	}
	return ""
}

func (x *BasestationMetadata) GetModel() string {
	if x != nil && x.Model != nil {
		return *x.Model
	}
	return ""
}

func (x *BasestationMetadata) GetAlias() string {
	if x != nil && x.Alias != nil {
		return *x.Alias
	}
	return ""
}

func (x *BasestationMetadata) GetSwVersion() string {
	if x != nil && x.SwVersion != nil {
		return *x.SwVersion
	}
	return ""
}

type CreateBasestationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant ID.
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Basestation EUI64.
	Eui string `protobuf:"bytes,2,opt,name=eui,proto3" json:"eui,omitempty"`
	// Name (defaults to EUI).
	Name *string `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// Description.
	Description *string `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Location.
	Location *common.GeoLocation `protobuf:"bytes,5,opt,name=location,proto3,oneof" json:"location,omitempty"`
	// Use location data provided by the basestation.
	UseGpsLocation bool `protobuf:"varint,6,opt,name=use_gps_location,json=useGpsLocation,proto3" json:"use_gps_location,omitempty"`
	// Tags.
	Tags          *common.Tags `protobuf:"bytes,8,opt,name=tags,proto3,oneof" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBasestationRequest) Reset() {
	*x = CreateBasestationRequest{}
	mi := &file_api_basestation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBasestationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBasestationRequest) ProtoMessage() {}

func (x *CreateBasestationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_basestation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBasestationRequest.ProtoReflect.Descriptor instead.
func (*CreateBasestationRequest) Descriptor() ([]byte, []int) {
	return file_api_basestation_proto_rawDescGZIP(), []int{3}
}

func (x *CreateBasestationRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateBasestationRequest) GetEui() string {
	if x != nil {
		return x.Eui
	}
	return ""
}

func (x *CreateBasestationRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *CreateBasestationRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateBasestationRequest) GetLocation() *common.GeoLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *CreateBasestationRequest) GetUseGpsLocation() bool {
	if x != nil {
		return x.UseGpsLocation
	}
	return false
}

func (x *CreateBasestationRequest) GetTags() *common.Tags {
	if x != nil {
		return x.Tags
	}
	return nil
}

type CreateBasestationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Created Basestation object.
	Basestation *Basestation `protobuf:"bytes,1,opt,name=basestation,proto3" json:"basestation,omitempty"`
	// Created at timestamp.
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBasestationResponse) Reset() {
	*x = CreateBasestationResponse{}
	mi := &file_api_basestation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBasestationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBasestationResponse) ProtoMessage() {}

func (x *CreateBasestationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_basestation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBasestationResponse.ProtoReflect.Descriptor instead.
func (*CreateBasestationResponse) Descriptor() ([]byte, []int) {
	return file_api_basestation_proto_rawDescGZIP(), []int{4}
}

func (x *CreateBasestationResponse) GetBasestation() *Basestation {
	if x != nil {
		return x.Basestation
	}
	return nil
}

func (x *CreateBasestationResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetBasestationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Basestation ID (UUID).
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBasestationRequest) Reset() {
	*x = GetBasestationRequest{}
	mi := &file_api_basestation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBasestationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBasestationRequest) ProtoMessage() {}

func (x *GetBasestationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_basestation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBasestationRequest.ProtoReflect.Descriptor instead.
func (*GetBasestationRequest) Descriptor() ([]byte, []int) {
	return file_api_basestation_proto_rawDescGZIP(), []int{5}
}

func (x *GetBasestationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetBasestationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Basestation object.
	Basestation *Basestation `protobuf:"bytes,1,opt,name=basestation,proto3" json:"basestation,omitempty"`
	// Created at timestamp.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last update timestamp.
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Last seen at timestamp.
	LastSeenAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_seen_at,json=lastSeenAt,proto3,oneof" json:"last_seen_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBasestationResponse) Reset() {
	*x = GetBasestationResponse{}
	mi := &file_api_basestation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBasestationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBasestationResponse) ProtoMessage() {}

func (x *GetBasestationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_basestation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBasestationResponse.ProtoReflect.Descriptor instead.
func (*GetBasestationResponse) Descriptor() ([]byte, []int) {
	return file_api_basestation_proto_rawDescGZIP(), []int{6}
}

func (x *GetBasestationResponse) GetBasestation() *Basestation {
	if x != nil {
		return x.Basestation
	}
	return nil
}

func (x *GetBasestationResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetBasestationResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *GetBasestationResponse) GetLastSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenAt
	}
	return nil
}

type UpdateBasestationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Basestation ID (UUID).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Name.
	Name *string `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// Description.
	Description *string `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Location.
	Location *common.GeoLocation `protobuf:"bytes,5,opt,name=location,proto3,oneof" json:"location,omitempty"`
	// Use location data provided by the basestation.
	UseGpsLocation *bool `protobuf:"varint,6,opt,name=use_gps_location,json=useGpsLocation,proto3,oneof" json:"use_gps_location,omitempty"`
	// Tags.
	Tags          *common.Tags `protobuf:"bytes,8,opt,name=tags,proto3,oneof" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBasestationRequest) Reset() {
	*x = UpdateBasestationRequest{}
	mi := &file_api_basestation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBasestationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBasestationRequest) ProtoMessage() {}

func (x *UpdateBasestationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_basestation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBasestationRequest.ProtoReflect.Descriptor instead.
func (*UpdateBasestationRequest) Descriptor() ([]byte, []int) {
	return file_api_basestation_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateBasestationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateBasestationRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateBasestationRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateBasestationRequest) GetLocation() *common.GeoLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *UpdateBasestationRequest) GetUseGpsLocation() bool {
	if x != nil && x.UseGpsLocation != nil {
		return *x.UseGpsLocation
	}
	return false
}

func (x *UpdateBasestationRequest) GetTags() *common.Tags {
	if x != nil {
		return x.Tags
	}
	return nil
}

type UpdateBasestationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Basestation object.
	Basestation *Basestation `protobuf:"bytes,1,opt,name=basestation,proto3" json:"basestation,omitempty"`
	// Created at timestamp.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last update timestamp.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBasestationResponse) Reset() {
	*x = UpdateBasestationResponse{}
	mi := &file_api_basestation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBasestationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBasestationResponse) ProtoMessage() {}

func (x *UpdateBasestationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_basestation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBasestationResponse.ProtoReflect.Descriptor instead.
func (*UpdateBasestationResponse) Descriptor() ([]byte, []int) {
	return file_api_basestation_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateBasestationResponse) GetBasestation() *Basestation {
	if x != nil {
		return x.Basestation
	}
	return nil
}

func (x *UpdateBasestationResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UpdateBasestationResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type DeleteBasestationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Basestation ID (UUID).
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBasestationRequest) Reset() {
	*x = DeleteBasestationRequest{}
	mi := &file_api_basestation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBasestationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBasestationRequest) ProtoMessage() {}

func (x *DeleteBasestationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_basestation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBasestationRequest.ProtoReflect.Descriptor instead.
func (*DeleteBasestationRequest) Descriptor() ([]byte, []int) {
	return file_api_basestation_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteBasestationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListBasestationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant ID (UUID) to filter basestations on.
	// To list all basestations as a global admin user, this field can be left blank.
	TenantId *string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3,oneof" json:"tenant_id,omitempty"`
	// Pagination. Defaults to 100 objects at page index 0.
	Paginator *Paginator `protobuf:"bytes,2,opt,name=paginator,proto3" json:"paginator,omitempty"`
	// If set, the given string will be used to search on name (optional).
	SearchName *string `protobuf:"bytes,3,opt,name=search_name,json=searchName,proto3,oneof" json:"search_name,omitempty"`
	// Tags to filter devices on.
	Tags *common.Tags `protobuf:"bytes,4,opt,name=tags,proto3,oneof" json:"tags,omitempty"`
	// If set, the given value will be used to sort by (optional).
	OrderBy ListBasestationsRequest_OrderBy `protobuf:"varint,6,opt,name=order_by,json=orderBy,proto3,enum=api.ListBasestationsRequest_OrderBy" json:"order_by,omitempty"`
	// If set, the sorting direction will be decending (default = ascending) (optional).
	OrderByDesc   bool `protobuf:"varint,7,opt,name=order_by_desc,json=orderByDesc,proto3" json:"order_by_desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBasestationsRequest) Reset() {
	*x = ListBasestationsRequest{}
	mi := &file_api_basestation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBasestationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBasestationsRequest) ProtoMessage() {}

func (x *ListBasestationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_basestation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBasestationsRequest.ProtoReflect.Descriptor instead.
func (*ListBasestationsRequest) Descriptor() ([]byte, []int) {
	return file_api_basestation_proto_rawDescGZIP(), []int{10}
}

func (x *ListBasestationsRequest) GetTenantId() string {
	if x != nil && x.TenantId != nil {
		return *x.TenantId
	}
	return ""
}

func (x *ListBasestationsRequest) GetPaginator() *Paginator {
	if x != nil {
		return x.Paginator
	}
	return nil
}

func (x *ListBasestationsRequest) GetSearchName() string {
	if x != nil && x.SearchName != nil {
		return *x.SearchName
	}
	return ""
}

func (x *ListBasestationsRequest) GetTags() *common.Tags {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ListBasestationsRequest) GetOrderBy() ListBasestationsRequest_OrderBy {
	if x != nil {
		return x.OrderBy
	}
	return ListBasestationsRequest_NAME
}

func (x *ListBasestationsRequest) GetOrderByDesc() bool {
	if x != nil {
		return x.OrderByDesc
	}
	return false
}

type ListBasestationsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pagination.
	Pagination *Pagination `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// Result-set.
	Result        []*BasestationListItem `protobuf:"bytes,2,rep,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBasestationsResponse) Reset() {
	*x = ListBasestationsResponse{}
	mi := &file_api_basestation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBasestationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBasestationsResponse) ProtoMessage() {}

func (x *ListBasestationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_basestation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBasestationsResponse.ProtoReflect.Descriptor instead.
func (*ListBasestationsResponse) Descriptor() ([]byte, []int) {
	return file_api_basestation_proto_rawDescGZIP(), []int{11}
}

func (x *ListBasestationsResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListBasestationsResponse) GetResult() []*BasestationListItem {
	if x != nil {
		return x.Result
	}
	return nil
}

type GenerateBasestationClientCertificateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Basestation ID (UUID).
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateBasestationClientCertificateRequest) Reset() {
	*x = GenerateBasestationClientCertificateRequest{}
	mi := &file_api_basestation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateBasestationClientCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateBasestationClientCertificateRequest) ProtoMessage() {}

func (x *GenerateBasestationClientCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_basestation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateBasestationClientCertificateRequest.ProtoReflect.Descriptor instead.
func (*GenerateBasestationClientCertificateRequest) Descriptor() ([]byte, []int) {
	return file_api_basestation_proto_rawDescGZIP(), []int{12}
}

func (x *GenerateBasestationClientCertificateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GenerateBasestationClientCertificateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TLS certificate.
	TlsCert string `protobuf:"bytes,1,opt,name=tls_cert,json=tlsCert,proto3" json:"tls_cert,omitempty"`
	// TLS key.
	TlsKey string `protobuf:"bytes,2,opt,name=tls_key,json=tlsKey,proto3" json:"tls_key,omitempty"`
	// CA certificate.
	CaCert string `protobuf:"bytes,3,opt,name=ca_cert,json=caCert,proto3" json:"ca_cert,omitempty"`
	// Expires at defines the expiration date of the certificate.
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateBasestationClientCertificateResponse) Reset() {
	*x = GenerateBasestationClientCertificateResponse{}
	mi := &file_api_basestation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateBasestationClientCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateBasestationClientCertificateResponse) ProtoMessage() {}

func (x *GenerateBasestationClientCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_basestation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateBasestationClientCertificateResponse.ProtoReflect.Descriptor instead.
func (*GenerateBasestationClientCertificateResponse) Descriptor() ([]byte, []int) {
	return file_api_basestation_proto_rawDescGZIP(), []int{13}
}

func (x *GenerateBasestationClientCertificateResponse) GetTlsCert() string {
	if x != nil {
		return x.TlsCert
	}
	return ""
}

func (x *GenerateBasestationClientCertificateResponse) GetTlsKey() string {
	if x != nil {
		return x.TlsKey
	}
	return ""
}

func (x *GenerateBasestationClientCertificateResponse) GetCaCert() string {
	if x != nil {
		return x.CaCert
	}
	return ""
}

func (x *GenerateBasestationClientCertificateResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type GetBasestationMetricsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Basestation ID (UUID).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Interval start timestamp.
	Start *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	// Interval end timestamp.
	End *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	// Aggregation.
	Aggregation   common.Aggregation `protobuf:"varint,4,opt,name=aggregation,proto3,enum=common.Aggregation" json:"aggregation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBasestationMetricsRequest) Reset() {
	*x = GetBasestationMetricsRequest{}
	mi := &file_api_basestation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBasestationMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBasestationMetricsRequest) ProtoMessage() {}

func (x *GetBasestationMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_basestation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBasestationMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetBasestationMetricsRequest) Descriptor() ([]byte, []int) {
	return file_api_basestation_proto_rawDescGZIP(), []int{14}
}

func (x *GetBasestationMetricsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetBasestationMetricsRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *GetBasestationMetricsRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *GetBasestationMetricsRequest) GetAggregation() common.Aggregation {
	if x != nil {
		return x.Aggregation
	}
	return common.Aggregation(0)
}

type GetBasestationMetricsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Basestation update in seconds.
	Uptime *common.Metric `protobuf:"bytes,1,opt,name=uptime,proto3" json:"uptime,omitempty"`
	// CPU utilization, normalized to 1.0 for all cores.
	Cpu *common.Metric `protobuf:"bytes,2,opt,name=cpu,proto3" json:"cpu,omitempty"`
	// Memory utilization, normalized to 1.0.
	Memory *common.Metric `protobuf:"bytes,3,opt,name=memory,proto3" json:"memory,omitempty"`
	// System temperature in degree Celsius.
	Temp *common.Metric `protobuf:"bytes,4,opt,name=temp,proto3" json:"temp,omitempty"`
	// Fraction of TX time, sliding window over one hour
	DutyCycle     *common.Metric `protobuf:"bytes,5,opt,name=duty_cycle,json=dutyCycle,proto3" json:"duty_cycle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBasestationMetricsResponse) Reset() {
	*x = GetBasestationMetricsResponse{}
	mi := &file_api_basestation_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBasestationMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBasestationMetricsResponse) ProtoMessage() {}

func (x *GetBasestationMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_basestation_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBasestationMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetBasestationMetricsResponse) Descriptor() ([]byte, []int) {
	return file_api_basestation_proto_rawDescGZIP(), []int{15}
}

func (x *GetBasestationMetricsResponse) GetUptime() *common.Metric {
	if x != nil {
		return x.Uptime
	}
	return nil
}

func (x *GetBasestationMetricsResponse) GetCpu() *common.Metric {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *GetBasestationMetricsResponse) GetMemory() *common.Metric {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *GetBasestationMetricsResponse) GetTemp() *common.Metric {
	if x != nil {
		return x.Temp
	}
	return nil
}

func (x *GetBasestationMetricsResponse) GetDutyCycle() *common.Metric {
	if x != nil {
		return x.DutyCycle
	}
	return nil
}

var File_api_basestation_proto protoreflect.FileDescriptor

const file_api_basestation_proto_rawDesc = "" +
	"\n" +
	"\x15api/basestation.proto\x12\x03api\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x10api/common.proto\x1a\x13common/common.proto\x1a\x14common/metrics.proto\"\x91\x03\n" +
	"\vBasestation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03eui\x18\x02 \x01(\tR\x03eui\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x00R\vdescription\x88\x01\x01\x124\n" +
	"\blocation\x18\x05 \x01(\v2\x13.common.GeoLocationH\x01R\blocation\x88\x01\x01\x129\n" +
	"\bmetadata\x18\x06 \x01(\v2\x18.api.BasestationMetadataH\x02R\bmetadata\x88\x01\x01\x12(\n" +
	"\x10use_gps_location\x18\a \x01(\bR\x0euseGpsLocation\x120\n" +
	"\x14variable_mac_support\x18\b \x01(\bR\x12variableMacSupport\x12%\n" +
	"\x04tags\x18\t \x01(\v2\f.common.TagsH\x03R\x04tags\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_locationB\v\n" +
	"\t_metadataB\a\n" +
	"\x05_tags\"\xea\x04\n" +
	"\x13BasestationListItem\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12%\n" +
	"\x0ebasestation_id\x18\x02 \x01(\tR\rbasestationId\x12\x10\n" +
	"\x03eui\x18\x03 \x01(\tR\x03eui\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x00R\vdescription\x88\x01\x01\x124\n" +
	"\blocation\x18\x06 \x01(\v2\x13.common.GeoLocationH\x01R\blocation\x88\x01\x01\x129\n" +
	"\bmetadata\x18\a \x01(\v2\x18.api.BasestationMetadataH\x02R\bmetadata\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12A\n" +
	"\flast_seen_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampH\x03R\n" +
	"lastSeenAt\x88\x01\x01\x120\n" +
	"\x14variable_mac_support\x18\v \x01(\bR\x12variableMacSupport\x12+\n" +
	"\x05state\x18\f \x01(\x0e2\x15.api.BasestationStateR\x05stateB\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_locationB\v\n" +
	"\t_metadataB\x0f\n" +
	"\r_last_seen_at\"\xba\x01\n" +
	"\x13BasestationMetadata\x12\x1b\n" +
	"\x06vendor\x18\x01 \x01(\tH\x00R\x06vendor\x88\x01\x01\x12\x19\n" +
	"\x05model\x18\x02 \x01(\tH\x01R\x05model\x88\x01\x01\x12\x19\n" +
	"\x05alias\x18\x03 \x01(\tH\x02R\x05alias\x88\x01\x01\x12\"\n" +
	"\n" +
	"sw_version\x18\x04 \x01(\tH\x03R\tswVersion\x88\x01\x01B\t\n" +
	"\a_vendorB\b\n" +
	"\x06_modelB\b\n" +
	"\x06_aliasB\r\n" +
	"\v_sw_version\"\xbf\x02\n" +
	"\x18CreateBasestationRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x10\n" +
	"\x03eui\x18\x02 \x01(\tR\x03eui\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x01R\vdescription\x88\x01\x01\x124\n" +
	"\blocation\x18\x05 \x01(\v2\x13.common.GeoLocationH\x02R\blocation\x88\x01\x01\x12(\n" +
	"\x10use_gps_location\x18\x06 \x01(\bR\x0euseGpsLocation\x12%\n" +
	"\x04tags\x18\b \x01(\v2\f.common.TagsH\x03R\x04tags\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_locationB\a\n" +
	"\x05_tags\"\x8a\x01\n" +
	"\x19CreateBasestationResponse\x122\n" +
	"\vbasestation\x18\x01 \x01(\v2\x10.api.BasestationR\vbasestation\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"'\n" +
	"\x15GetBasestationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x96\x02\n" +
	"\x16GetBasestationResponse\x122\n" +
	"\vbasestation\x18\x01 \x01(\v2\x10.api.BasestationR\vbasestation\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12A\n" +
	"\flast_seen_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\n" +
	"lastSeenAt\x88\x01\x01B\x0f\n" +
	"\r_last_seen_at\"\xba\x02\n" +
	"\x18UpdateBasestationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x01R\vdescription\x88\x01\x01\x124\n" +
	"\blocation\x18\x05 \x01(\v2\x13.common.GeoLocationH\x02R\blocation\x88\x01\x01\x12-\n" +
	"\x10use_gps_location\x18\x06 \x01(\bH\x03R\x0euseGpsLocation\x88\x01\x01\x12%\n" +
	"\x04tags\x18\b \x01(\v2\f.common.TagsH\x04R\x04tags\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_locationB\x13\n" +
	"\x11_use_gps_locationB\a\n" +
	"\x05_tags\"\xc5\x01\n" +
	"\x19UpdateBasestationResponse\x122\n" +
	"\vbasestation\x18\x01 \x01(\v2\x10.api.BasestationR\vbasestation\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"*\n" +
	"\x18DeleteBasestationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x82\x03\n" +
	"\x17ListBasestationsRequest\x12 \n" +
	"\ttenant_id\x18\x01 \x01(\tH\x00R\btenantId\x88\x01\x01\x12,\n" +
	"\tpaginator\x18\x02 \x01(\v2\x0e.api.PaginatorR\tpaginator\x12$\n" +
	"\vsearch_name\x18\x03 \x01(\tH\x01R\n" +
	"searchName\x88\x01\x01\x12%\n" +
	"\x04tags\x18\x04 \x01(\v2\f.common.TagsH\x02R\x04tags\x88\x01\x01\x12?\n" +
	"\border_by\x18\x06 \x01(\x0e2$.api.ListBasestationsRequest.OrderByR\aorderBy\x12\"\n" +
	"\rorder_by_desc\x18\a \x01(\bR\vorderByDesc\">\n" +
	"\aOrderBy\x12\b\n" +
	"\x04NAME\x10\x00\x12\a\n" +
	"\x03EUI\x10\x01\x12\x10\n" +
	"\fLAST_SEEN_AT\x10\x02\x12\x0e\n" +
	"\n" +
	"CREATED_AT\x10\x03B\f\n" +
	"\n" +
	"_tenant_idB\x0e\n" +
	"\f_search_nameB\a\n" +
	"\x05_tags\"}\n" +
	"\x18ListBasestationsResponse\x12/\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x0f.api.PaginationR\n" +
	"pagination\x120\n" +
	"\x06result\x18\x02 \x03(\v2\x18.api.BasestationListItemR\x06result\"=\n" +
	"+GenerateBasestationClientCertificateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xb6\x01\n" +
	",GenerateBasestationClientCertificateResponse\x12\x19\n" +
	"\btls_cert\x18\x01 \x01(\tR\atlsCert\x12\x17\n" +
	"\atls_key\x18\x02 \x01(\tR\x06tlsKey\x12\x17\n" +
	"\aca_cert\x18\x03 \x01(\tR\x06caCert\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\xc5\x01\n" +
	"\x1cGetBasestationMetricsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\x05start\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\x125\n" +
	"\vaggregation\x18\x04 \x01(\x0e2\x13.common.AggregationR\vaggregation\"\xe4\x01\n" +
	"\x1dGetBasestationMetricsResponse\x12&\n" +
	"\x06uptime\x18\x01 \x01(\v2\x0e.common.MetricR\x06uptime\x12 \n" +
	"\x03cpu\x18\x02 \x01(\v2\x0e.common.MetricR\x03cpu\x12&\n" +
	"\x06memory\x18\x03 \x01(\v2\x0e.common.MetricR\x06memory\x12\"\n" +
	"\x04temp\x18\x04 \x01(\v2\x0e.common.MetricR\x04temp\x12-\n" +
	"\n" +
	"duty_cycle\x18\x05 \x01(\v2\x0e.common.MetricR\tdutyCycle*;\n" +
	"\x10BasestationState\x12\x0e\n" +
	"\n" +
	"NEVER_SEEN\x10\x00\x12\n" +
	"\n" +
	"\x06ONLINE\x10\x01\x12\v\n" +
	"\aOFFLINE\x10\x022\x83\a\n" +
	"\x12BasestationService\x12p\n" +
	"\x11CreateBasestation\x12\x1d.api.CreateBasestationRequest\x1a\x1e.api.CreateBasestationResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/basestations\x12i\n" +
	"\x0eGetBasestation\x12\x1a.api.GetBasestationRequest\x1a\x1b.api.GetBasestationResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/basestations/{id}\x12u\n" +
	"\x11UpdateBasestation\x12\x1d.api.UpdateBasestationRequest\x1a\x1e.api.UpdateBasestationResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\x1a\x16/api/basestations/{id}\x12j\n" +
	"\x11DeleteBasestation\x12\x1d.api.DeleteBasestationRequest\x1a\x16.google.protobuf.Empty\"\x1e\x82\xd3\xe4\x93\x02\x18*\x16/api/basestations/{id}\x12j\n" +
	"\x10ListBasestations\x12\x1c.api.ListBasestationsRequest\x1a\x1d.api.ListBasestationsResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/basestations\x12\xb7\x01\n" +
	"$GenerateBasestationClientCertificate\x120.api.GenerateBasestationClientCertificateRequest\x1a1.api.GenerateBasestationClientCertificateResponse\"*\x82\xd3\xe4\x93\x02$\"\"/api/basestations/{id}/certificate\x12\x86\x01\n" +
	"\x15GetBasestationMetrics\x12!.api.GetBasestationMetricsRequest\x1a\".api.GetBasestationMetricsResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/api/basestations/{id}/metricsB\xae\x01\n" +
	"\x11io.splitstack.apiB\x10BasestationProtoP\x01Z4github.com/SplitStackServer/splitstack/api/go/v5/api\xaa\x02\x14SplitStackServer.Api\xca\x02\x14SplitStackServer\\Api\xe2\x02 GPBMetadata\\SplitStackServer\\Apib\x06proto3"

var (
	file_api_basestation_proto_rawDescOnce sync.Once
	file_api_basestation_proto_rawDescData []byte
)

func file_api_basestation_proto_rawDescGZIP() []byte {
	file_api_basestation_proto_rawDescOnce.Do(func() {
		file_api_basestation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_basestation_proto_rawDesc), len(file_api_basestation_proto_rawDesc)))
	})
	return file_api_basestation_proto_rawDescData
}

var file_api_basestation_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_basestation_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_basestation_proto_goTypes = []any{
	(BasestationState)(0),                                // 0: api.BasestationState
	(ListBasestationsRequest_OrderBy)(0),                 // 1: api.ListBasestationsRequest.OrderBy
	(*Basestation)(nil),                                  // 2: api.Basestation
	(*BasestationListItem)(nil),                          // 3: api.BasestationListItem
	(*BasestationMetadata)(nil),                          // 4: api.BasestationMetadata
	(*CreateBasestationRequest)(nil),                     // 5: api.CreateBasestationRequest
	(*CreateBasestationResponse)(nil),                    // 6: api.CreateBasestationResponse
	(*GetBasestationRequest)(nil),                        // 7: api.GetBasestationRequest
	(*GetBasestationResponse)(nil),                       // 8: api.GetBasestationResponse
	(*UpdateBasestationRequest)(nil),                     // 9: api.UpdateBasestationRequest
	(*UpdateBasestationResponse)(nil),                    // 10: api.UpdateBasestationResponse
	(*DeleteBasestationRequest)(nil),                     // 11: api.DeleteBasestationRequest
	(*ListBasestationsRequest)(nil),                      // 12: api.ListBasestationsRequest
	(*ListBasestationsResponse)(nil),                     // 13: api.ListBasestationsResponse
	(*GenerateBasestationClientCertificateRequest)(nil),  // 14: api.GenerateBasestationClientCertificateRequest
	(*GenerateBasestationClientCertificateResponse)(nil), // 15: api.GenerateBasestationClientCertificateResponse
	(*GetBasestationMetricsRequest)(nil),                 // 16: api.GetBasestationMetricsRequest
	(*GetBasestationMetricsResponse)(nil),                // 17: api.GetBasestationMetricsResponse
	(*common.GeoLocation)(nil),                           // 18: common.GeoLocation
	(*common.Tags)(nil),                                  // 19: common.Tags
	(*timestamppb.Timestamp)(nil),                        // 20: google.protobuf.Timestamp
	(*Paginator)(nil),                                    // 21: api.Paginator
	(*Pagination)(nil),                                   // 22: api.Pagination
	(common.Aggregation)(0),                              // 23: common.Aggregation
	(*common.Metric)(nil),                                // 24: common.Metric
	(*emptypb.Empty)(nil),                                // 25: google.protobuf.Empty
}
var file_api_basestation_proto_depIdxs = []int32{
	18, // 0: api.Basestation.location:type_name -> common.GeoLocation
	4,  // 1: api.Basestation.metadata:type_name -> api.BasestationMetadata
	19, // 2: api.Basestation.tags:type_name -> common.Tags
	18, // 3: api.BasestationListItem.location:type_name -> common.GeoLocation
	4,  // 4: api.BasestationListItem.metadata:type_name -> api.BasestationMetadata
	20, // 5: api.BasestationListItem.created_at:type_name -> google.protobuf.Timestamp
	20, // 6: api.BasestationListItem.updated_at:type_name -> google.protobuf.Timestamp
	20, // 7: api.BasestationListItem.last_seen_at:type_name -> google.protobuf.Timestamp
	0,  // 8: api.BasestationListItem.state:type_name -> api.BasestationState
	18, // 9: api.CreateBasestationRequest.location:type_name -> common.GeoLocation
	19, // 10: api.CreateBasestationRequest.tags:type_name -> common.Tags
	2,  // 11: api.CreateBasestationResponse.basestation:type_name -> api.Basestation
	20, // 12: api.CreateBasestationResponse.created_at:type_name -> google.protobuf.Timestamp
	2,  // 13: api.GetBasestationResponse.basestation:type_name -> api.Basestation
	20, // 14: api.GetBasestationResponse.created_at:type_name -> google.protobuf.Timestamp
	20, // 15: api.GetBasestationResponse.updated_at:type_name -> google.protobuf.Timestamp
	20, // 16: api.GetBasestationResponse.last_seen_at:type_name -> google.protobuf.Timestamp
	18, // 17: api.UpdateBasestationRequest.location:type_name -> common.GeoLocation
	19, // 18: api.UpdateBasestationRequest.tags:type_name -> common.Tags
	2,  // 19: api.UpdateBasestationResponse.basestation:type_name -> api.Basestation
	20, // 20: api.UpdateBasestationResponse.created_at:type_name -> google.protobuf.Timestamp
	20, // 21: api.UpdateBasestationResponse.updated_at:type_name -> google.protobuf.Timestamp
	21, // 22: api.ListBasestationsRequest.paginator:type_name -> api.Paginator
	19, // 23: api.ListBasestationsRequest.tags:type_name -> common.Tags
	1,  // 24: api.ListBasestationsRequest.order_by:type_name -> api.ListBasestationsRequest.OrderBy
	22, // 25: api.ListBasestationsResponse.pagination:type_name -> api.Pagination
	3,  // 26: api.ListBasestationsResponse.result:type_name -> api.BasestationListItem
	20, // 27: api.GenerateBasestationClientCertificateResponse.expires_at:type_name -> google.protobuf.Timestamp
	20, // 28: api.GetBasestationMetricsRequest.start:type_name -> google.protobuf.Timestamp
	20, // 29: api.GetBasestationMetricsRequest.end:type_name -> google.protobuf.Timestamp
	23, // 30: api.GetBasestationMetricsRequest.aggregation:type_name -> common.Aggregation
	24, // 31: api.GetBasestationMetricsResponse.uptime:type_name -> common.Metric
	24, // 32: api.GetBasestationMetricsResponse.cpu:type_name -> common.Metric
	24, // 33: api.GetBasestationMetricsResponse.memory:type_name -> common.Metric
	24, // 34: api.GetBasestationMetricsResponse.temp:type_name -> common.Metric
	24, // 35: api.GetBasestationMetricsResponse.duty_cycle:type_name -> common.Metric
	5,  // 36: api.BasestationService.CreateBasestation:input_type -> api.CreateBasestationRequest
	7,  // 37: api.BasestationService.GetBasestation:input_type -> api.GetBasestationRequest
	9,  // 38: api.BasestationService.UpdateBasestation:input_type -> api.UpdateBasestationRequest
	11, // 39: api.BasestationService.DeleteBasestation:input_type -> api.DeleteBasestationRequest
	12, // 40: api.BasestationService.ListBasestations:input_type -> api.ListBasestationsRequest
	14, // 41: api.BasestationService.GenerateBasestationClientCertificate:input_type -> api.GenerateBasestationClientCertificateRequest
	16, // 42: api.BasestationService.GetBasestationMetrics:input_type -> api.GetBasestationMetricsRequest
	6,  // 43: api.BasestationService.CreateBasestation:output_type -> api.CreateBasestationResponse
	8,  // 44: api.BasestationService.GetBasestation:output_type -> api.GetBasestationResponse
	10, // 45: api.BasestationService.UpdateBasestation:output_type -> api.UpdateBasestationResponse
	25, // 46: api.BasestationService.DeleteBasestation:output_type -> google.protobuf.Empty
	13, // 47: api.BasestationService.ListBasestations:output_type -> api.ListBasestationsResponse
	15, // 48: api.BasestationService.GenerateBasestationClientCertificate:output_type -> api.GenerateBasestationClientCertificateResponse
	17, // 49: api.BasestationService.GetBasestationMetrics:output_type -> api.GetBasestationMetricsResponse
	43, // [43:50] is the sub-list for method output_type
	36, // [36:43] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_api_basestation_proto_init() }
func file_api_basestation_proto_init() {
	if File_api_basestation_proto != nil {
		return
	}
	file_api_common_proto_init()
	file_api_basestation_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_basestation_proto_msgTypes[1].OneofWrappers = []any{}
	file_api_basestation_proto_msgTypes[2].OneofWrappers = []any{}
	file_api_basestation_proto_msgTypes[3].OneofWrappers = []any{}
	file_api_basestation_proto_msgTypes[6].OneofWrappers = []any{}
	file_api_basestation_proto_msgTypes[7].OneofWrappers = []any{}
	file_api_basestation_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_basestation_proto_rawDesc), len(file_api_basestation_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_basestation_proto_goTypes,
		DependencyIndexes: file_api_basestation_proto_depIdxs,
		EnumInfos:         file_api_basestation_proto_enumTypes,
		MessageInfos:      file_api_basestation_proto_msgTypes,
	}.Build()
	File_api_basestation_proto = out.File
	file_api_basestation_proto_goTypes = nil
	file_api_basestation_proto_depIdxs = nil
}
