// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api/common.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IntegrationKind int32

const (
	IntegrationKind_HTTP_PUSH    IntegrationKind = 0
	IntegrationKind_INFLUX_DB    IntegrationKind = 1
	IntegrationKind_THINGS_BOARD IntegrationKind = 2
)

// Enum value maps for IntegrationKind.
var (
	IntegrationKind_name = map[int32]string{
		0: "HTTP_PUSH",
		1: "INFLUX_DB",
		2: "THINGS_BOARD",
	}
	IntegrationKind_value = map[string]int32{
		"HTTP_PUSH":    0,
		"INFLUX_DB":    1,
		"THINGS_BOARD": 2,
	}
)

func (x IntegrationKind) Enum() *IntegrationKind {
	p := new(IntegrationKind)
	*p = x
	return p
}

func (x IntegrationKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IntegrationKind) Descriptor() protoreflect.EnumDescriptor {
	return file_api_common_proto_enumTypes[0].Descriptor()
}

func (IntegrationKind) Type() protoreflect.EnumType {
	return &file_api_common_proto_enumTypes[0]
}

func (x IntegrationKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IntegrationKind.Descriptor instead.
func (IntegrationKind) EnumDescriptor() ([]byte, []int) {
	return file_api_common_proto_rawDescGZIP(), []int{0}
}

// Paginate requests for multiple objects.
type Paginator struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Requested number of items per page. Defaults to 100.
	PageSize uint64 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Requested page. First page is 0.
	Page          uint64 `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Paginator) Reset() {
	*x = Paginator{}
	mi := &file_api_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Paginator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Paginator) ProtoMessage() {}

func (x *Paginator) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Paginator.ProtoReflect.Descriptor instead.
func (*Paginator) Descriptor() ([]byte, []int) {
	return file_api_common_proto_rawDescGZIP(), []int{0}
}

func (x *Paginator) GetPageSize() uint64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *Paginator) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

// Details about the pagination.
type Pagination struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total number of available pages with the requested page size
	NumPages uint64 `protobuf:"varint,1,opt,name=num_pages,json=numPages,proto3" json:"num_pages,omitempty"`
	// Total number of available items
	NumItems      uint64 `protobuf:"varint,2,opt,name=num_items,json=numItems,proto3" json:"num_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_api_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_api_common_proto_rawDescGZIP(), []int{1}
}

func (x *Pagination) GetNumPages() uint64 {
	if x != nil {
		return x.NumPages
	}
	return 0
}

func (x *Pagination) GetNumItems() uint64 {
	if x != nil {
		return x.NumItems
	}
	return 0
}

type VariableMacList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of variable MACs
	Vm            []uint32 `protobuf:"varint,1,rep,packed,name=vm,proto3" json:"vm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VariableMacList) Reset() {
	*x = VariableMacList{}
	mi := &file_api_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VariableMacList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariableMacList) ProtoMessage() {}

func (x *VariableMacList) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariableMacList.ProtoReflect.Descriptor instead.
func (*VariableMacList) Descriptor() ([]byte, []int) {
	return file_api_common_proto_rawDescGZIP(), []int{2}
}

func (x *VariableMacList) GetVm() []uint32 {
	if x != nil {
		return x.Vm
	}
	return nil
}

var File_api_common_proto protoreflect.FileDescriptor

const file_api_common_proto_rawDesc = "" +
	"\n" +
	"\x10api/common.proto\x12\x03api\"<\n" +
	"\tPaginator\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x04R\bpageSize\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x04R\x04page\"F\n" +
	"\n" +
	"Pagination\x12\x1b\n" +
	"\tnum_pages\x18\x01 \x01(\x04R\bnumPages\x12\x1b\n" +
	"\tnum_items\x18\x02 \x01(\x04R\bnumItems\"!\n" +
	"\x0fVariableMacList\x12\x0e\n" +
	"\x02vm\x18\x01 \x03(\rR\x02vm*A\n" +
	"\x0fIntegrationKind\x12\r\n" +
	"\tHTTP_PUSH\x10\x00\x12\r\n" +
	"\tINFLUX_DB\x10\x01\x12\x10\n" +
	"\fTHINGS_BOARD\x10\x02B\xa8\x01\n" +
	"\x11io.splitstack.apiB\vCommonProtoP\x01Z3github.com/SplitStackServer/splitstack-grpc-api/api\xaa\x02\x14SplitStackServer.Api\xca\x02\x14SplitStackServer\\Api\xe2\x02 GPBMetadata\\SplitStackServer\\Apib\x06proto3"

var (
	file_api_common_proto_rawDescOnce sync.Once
	file_api_common_proto_rawDescData []byte
)

func file_api_common_proto_rawDescGZIP() []byte {
	file_api_common_proto_rawDescOnce.Do(func() {
		file_api_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_common_proto_rawDesc), len(file_api_common_proto_rawDesc)))
	})
	return file_api_common_proto_rawDescData
}

var file_api_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_common_proto_goTypes = []any{
	(IntegrationKind)(0),    // 0: api.IntegrationKind
	(*Paginator)(nil),       // 1: api.Paginator
	(*Pagination)(nil),      // 2: api.Pagination
	(*VariableMacList)(nil), // 3: api.VariableMacList
}
var file_api_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_common_proto_init() }
func file_api_common_proto_init() {
	if File_api_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_common_proto_rawDesc), len(file_api_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_common_proto_goTypes,
		DependencyIndexes: file_api_common_proto_depIdxs,
		EnumInfos:         file_api_common_proto_enumTypes,
		MessageInfos:      file_api_common_proto_msgTypes,
	}.Build()
	File_api_common_proto = out.File
	file_api_common_proto_goTypes = nil
	file_api_common_proto_depIdxs = nil
}
