// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api/device_profile.proto

package api

import (
	common "github.com/SplitStackServer/splitstack/api/go/v5/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CodecRuntime int32

const (
	// None.
	CodecRuntime_NONE CodecRuntime = 0
	// mioty BluePrint (JSON).
	CodecRuntime_BLUEPRINT CodecRuntime = 1
	// JavaScript.
	CodecRuntime_JS CodecRuntime = 2
	// IO-Link IODD.
	CodecRuntime_IO_LINK_IODD CodecRuntime = 3
)

// Enum value maps for CodecRuntime.
var (
	CodecRuntime_name = map[int32]string{
		0: "NONE",
		1: "BLUEPRINT",
		2: "JS",
		3: "IO_LINK_IODD",
	}
	CodecRuntime_value = map[string]int32{
		"NONE":         0,
		"BLUEPRINT":    1,
		"JS":           2,
		"IO_LINK_IODD": 3,
	}
)

func (x CodecRuntime) Enum() *CodecRuntime {
	p := new(CodecRuntime)
	*p = x
	return p
}

func (x CodecRuntime) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CodecRuntime) Descriptor() protoreflect.EnumDescriptor {
	return file_api_device_profile_proto_enumTypes[0].Descriptor()
}

func (CodecRuntime) Type() protoreflect.EnumType {
	return &file_api_device_profile_proto_enumTypes[0]
}

func (x CodecRuntime) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CodecRuntime.Descriptor instead.
func (CodecRuntime) EnumDescriptor() ([]byte, []int) {
	return file_api_device_profile_proto_rawDescGZIP(), []int{0}
}

type MeasurementKind int32

const (
	// Unknown (in which case it is not tracked).
	MeasurementKind_UNKNOWN MeasurementKind = 0
	// Incrementing counters that never decrease (these are not reset on each
	// reading).
	MeasurementKind_COUNTER MeasurementKind = 1
	// Counters that do get reset upon reading.
	MeasurementKind_ABSOLUTE MeasurementKind = 2
	// E.g. a temperature value.
	MeasurementKind_GAUGE MeasurementKind = 3
	// E.g. a firmware version, true / false value.
	MeasurementKind_STRING MeasurementKind = 4
)

// Enum value maps for MeasurementKind.
var (
	MeasurementKind_name = map[int32]string{
		0: "UNKNOWN",
		1: "COUNTER",
		2: "ABSOLUTE",
		3: "GAUGE",
		4: "STRING",
	}
	MeasurementKind_value = map[string]int32{
		"UNKNOWN":  0,
		"COUNTER":  1,
		"ABSOLUTE": 2,
		"GAUGE":    3,
		"STRING":   4,
	}
)

func (x MeasurementKind) Enum() *MeasurementKind {
	p := new(MeasurementKind)
	*p = x
	return p
}

func (x MeasurementKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MeasurementKind) Descriptor() protoreflect.EnumDescriptor {
	return file_api_device_profile_proto_enumTypes[1].Descriptor()
}

func (MeasurementKind) Type() protoreflect.EnumType {
	return &file_api_device_profile_proto_enumTypes[1]
}

func (x MeasurementKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MeasurementKind.Descriptor instead.
func (MeasurementKind) EnumDescriptor() ([]byte, []int) {
	return file_api_device_profile_proto_rawDescGZIP(), []int{1}
}

type DeviceProfile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Device-profile ID (UUID).
	// Note: on create this will be automatically generated.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Tenant ID (UUID).
	TenantId string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Name.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Description.
	Description *string `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Manufacturer.
	Manufacturer string `protobuf:"bytes,5,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	// Firmware version.
	Firmware string `protobuf:"bytes,6,opt,name=firmware,proto3" json:"firmware,omitempty"`
	// Region.
	Region common.Region `protobuf:"varint,7,opt,name=region,proto3,enum=common.Region" json:"region,omitempty"`
	// Device class.
	DeviceClass common.DeviceClass `protobuf:"varint,8,opt,name=device_class,json=deviceClass,proto3,enum=common.DeviceClass" json:"device_class,omitempty"`
	// Uplink interval (seconds).
	// This defines the expected uplink interval which the device uses for
	// communication. If the uplink interval has expired and no uplink has
	// been received, the device is considered inactive.
	UplinkInterval uint32 `protobuf:"varint,10,opt,name=uplink_interval,json=uplinkInterval,proto3" json:"uplink_interval,omitempty"`
	// Payload codec runtime.
	PayloadCodecRuntime CodecRuntime `protobuf:"varint,11,opt,name=payload_codec_runtime,json=payloadCodecRuntime,proto3,enum=api.CodecRuntime" json:"payload_codec_runtime,omitempty"`
	// Payload codec script.
	PayloadCodecScript *string `protobuf:"bytes,12,opt,name=payload_codec_script,json=payloadCodecScript,proto3,oneof" json:"payload_codec_script,omitempty"`
	// Measurements.
	// If defined, ChirpStack will visualize these metrics in the web-interface.
	Measurements *Measurements `protobuf:"bytes,20,opt,name=measurements,proto3,oneof" json:"measurements,omitempty"`
	// Auto-detect measurements.
	// If set to true, measurements will be automatically added based on the
	// keys of the decoded payload. In cases where the decoded payload contains
	// random keys in the data, you want to set this to false.
	AutoDetectMeasurements bool `protobuf:"varint,21,opt,name=auto_detect_measurements,json=autoDetectMeasurements,proto3" json:"auto_detect_measurements,omitempty"`
	// Tags (user defined).
	// These tags can be used to add additional information the the
	// device-profile. These tags are exposed in all the integration events of
	// devices using this device-profile.
	Tags          *common.Tags `protobuf:"bytes,26,opt,name=tags,proto3,oneof" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceProfile) Reset() {
	*x = DeviceProfile{}
	mi := &file_api_device_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceProfile) ProtoMessage() {}

func (x *DeviceProfile) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceProfile.ProtoReflect.Descriptor instead.
func (*DeviceProfile) Descriptor() ([]byte, []int) {
	return file_api_device_profile_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceProfile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeviceProfile) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DeviceProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeviceProfile) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *DeviceProfile) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *DeviceProfile) GetFirmware() string {
	if x != nil {
		return x.Firmware
	}
	return ""
}

func (x *DeviceProfile) GetRegion() common.Region {
	if x != nil {
		return x.Region
	}
	return common.Region(0)
}

func (x *DeviceProfile) GetDeviceClass() common.DeviceClass {
	if x != nil {
		return x.DeviceClass
	}
	return common.DeviceClass(0)
}

func (x *DeviceProfile) GetUplinkInterval() uint32 {
	if x != nil {
		return x.UplinkInterval
	}
	return 0
}

func (x *DeviceProfile) GetPayloadCodecRuntime() CodecRuntime {
	if x != nil {
		return x.PayloadCodecRuntime
	}
	return CodecRuntime_NONE
}

func (x *DeviceProfile) GetPayloadCodecScript() string {
	if x != nil && x.PayloadCodecScript != nil {
		return *x.PayloadCodecScript
	}
	return ""
}

func (x *DeviceProfile) GetMeasurements() *Measurements {
	if x != nil {
		return x.Measurements
	}
	return nil
}

func (x *DeviceProfile) GetAutoDetectMeasurements() bool {
	if x != nil {
		return x.AutoDetectMeasurements
	}
	return false
}

func (x *DeviceProfile) GetTags() *common.Tags {
	if x != nil {
		return x.Tags
	}
	return nil
}

type Measurements struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Measurements  map[string]*Measurement `protobuf:"bytes,1,rep,name=measurements,proto3" json:"measurements,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Measurements) Reset() {
	*x = Measurements{}
	mi := &file_api_device_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Measurements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Measurements) ProtoMessage() {}

func (x *Measurements) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Measurements.ProtoReflect.Descriptor instead.
func (*Measurements) Descriptor() ([]byte, []int) {
	return file_api_device_profile_proto_rawDescGZIP(), []int{1}
}

func (x *Measurements) GetMeasurements() map[string]*Measurement {
	if x != nil {
		return x.Measurements
	}
	return nil
}

type Measurement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name (user defined).
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Kind.
	Kind          MeasurementKind `protobuf:"varint,3,opt,name=kind,proto3,enum=api.MeasurementKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Measurement) Reset() {
	*x = Measurement{}
	mi := &file_api_device_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Measurement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Measurement) ProtoMessage() {}

func (x *Measurement) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Measurement.ProtoReflect.Descriptor instead.
func (*Measurement) Descriptor() ([]byte, []int) {
	return file_api_device_profile_proto_rawDescGZIP(), []int{2}
}

func (x *Measurement) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Measurement) GetKind() MeasurementKind {
	if x != nil {
		return x.Kind
	}
	return MeasurementKind_UNKNOWN
}

type DeviceProfileListItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant ID.
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Device-profile ID (UUID).
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Created at timestamp.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last update timestamp.
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Name.
	Name string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	// Region.
	Region common.Region `protobuf:"varint,6,opt,name=region,proto3,enum=common.Region" json:"region,omitempty"`
	// Device class.
	DeviceClass   common.DeviceClass `protobuf:"varint,7,opt,name=device_class,json=deviceClass,proto3,enum=common.DeviceClass" json:"device_class,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceProfileListItem) Reset() {
	*x = DeviceProfileListItem{}
	mi := &file_api_device_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceProfileListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceProfileListItem) ProtoMessage() {}

func (x *DeviceProfileListItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceProfileListItem.ProtoReflect.Descriptor instead.
func (*DeviceProfileListItem) Descriptor() ([]byte, []int) {
	return file_api_device_profile_proto_rawDescGZIP(), []int{3}
}

func (x *DeviceProfileListItem) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DeviceProfileListItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeviceProfileListItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DeviceProfileListItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *DeviceProfileListItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeviceProfileListItem) GetRegion() common.Region {
	if x != nil {
		return x.Region
	}
	return common.Region(0)
}

func (x *DeviceProfileListItem) GetDeviceClass() common.DeviceClass {
	if x != nil {
		return x.DeviceClass
	}
	return common.DeviceClass(0)
}

type CreateDeviceProfileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant ID (UUID).
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Name.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Description.
	Description *string `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Manufacturer.
	Manufacturer string `protobuf:"bytes,4,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	// Firmware version.
	Firmware string `protobuf:"bytes,5,opt,name=firmware,proto3" json:"firmware,omitempty"`
	// Region.
	Region common.Region `protobuf:"varint,6,opt,name=region,proto3,enum=common.Region" json:"region,omitempty"`
	// Device class.
	DeviceClass common.DeviceClass `protobuf:"varint,7,opt,name=device_class,json=deviceClass,proto3,enum=common.DeviceClass" json:"device_class,omitempty"`
	// MAC Payload format (MPF)
	// Indicates that a telegram is a container for a MPF payload.
	MacFormat *common.MacPayloadFormat `protobuf:"varint,8,opt,name=mac_format,json=macFormat,proto3,enum=common.MacPayloadFormat,oneof" json:"mac_format,omitempty"`
	// Uplink interval (seconds).
	// This defines the expected uplink interval which the device uses for
	// communication. If the uplink interval has expired and no uplink has
	// been received, the device is considered inactive.
	UplinkInterval uint32 `protobuf:"varint,9,opt,name=uplink_interval,json=uplinkInterval,proto3" json:"uplink_interval,omitempty"`
	// Payload codec runtime.
	PayloadCodecRuntime CodecRuntime `protobuf:"varint,10,opt,name=payload_codec_runtime,json=payloadCodecRuntime,proto3,enum=api.CodecRuntime" json:"payload_codec_runtime,omitempty"`
	// Payload codec script.
	PayloadCodecScript *string `protobuf:"bytes,11,opt,name=payload_codec_script,json=payloadCodecScript,proto3,oneof" json:"payload_codec_script,omitempty"`
	// Measurements.
	// If defined, ChirpStack will visualize these metrics in the web-interface.
	Measurements *Measurements `protobuf:"bytes,12,opt,name=measurements,proto3,oneof" json:"measurements,omitempty"`
	// Auto-detect measurements.
	// If set to true, measurements will be automatically added based on the
	// keys of the decoded payload. In cases where the decoded payload contains
	// random keys in the data, you want to set this to false.
	AutoDetectMeasurements bool `protobuf:"varint,13,opt,name=auto_detect_measurements,json=autoDetectMeasurements,proto3" json:"auto_detect_measurements,omitempty"`
	// True if End Point uses dual channel mode
	DualChannel bool `protobuf:"varint,14,opt,name=dual_channel,json=dualChannel,proto3" json:"dual_channel,omitempty"`
	// True if End Point uses DL repetition
	Repetition bool `protobuf:"varint,15,opt,name=repetition,proto3" json:"repetition,omitempty"`
	// True if End Point uses wide carrier offset
	WideCarrOff bool `protobuf:"varint,16,opt,name=wide_carr_off,json=wideCarrOff,proto3" json:"wide_carr_off,omitempty"`
	// True if End Point uses long DL interblock distance
	LongBlkDist bool `protobuf:"varint,17,opt,name=long_blk_dist,json=longBlkDist,proto3" json:"long_blk_dist,omitempty"`
	// Tags (user defined).
	// These tags can be used to add additional information the the
	// device-profile. These tags are exposed in all the integration events of
	// devices using this device-profile.
	Tags          *common.Tags `protobuf:"bytes,18,opt,name=tags,proto3,oneof" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDeviceProfileRequest) Reset() {
	*x = CreateDeviceProfileRequest{}
	mi := &file_api_device_profile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDeviceProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeviceProfileRequest) ProtoMessage() {}

func (x *CreateDeviceProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_profile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeviceProfileRequest.ProtoReflect.Descriptor instead.
func (*CreateDeviceProfileRequest) Descriptor() ([]byte, []int) {
	return file_api_device_profile_proto_rawDescGZIP(), []int{4}
}

func (x *CreateDeviceProfileRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateDeviceProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDeviceProfileRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateDeviceProfileRequest) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *CreateDeviceProfileRequest) GetFirmware() string {
	if x != nil {
		return x.Firmware
	}
	return ""
}

func (x *CreateDeviceProfileRequest) GetRegion() common.Region {
	if x != nil {
		return x.Region
	}
	return common.Region(0)
}

func (x *CreateDeviceProfileRequest) GetDeviceClass() common.DeviceClass {
	if x != nil {
		return x.DeviceClass
	}
	return common.DeviceClass(0)
}

func (x *CreateDeviceProfileRequest) GetMacFormat() common.MacPayloadFormat {
	if x != nil && x.MacFormat != nil {
		return *x.MacFormat
	}
	return common.MacPayloadFormat(0)
}

func (x *CreateDeviceProfileRequest) GetUplinkInterval() uint32 {
	if x != nil {
		return x.UplinkInterval
	}
	return 0
}

func (x *CreateDeviceProfileRequest) GetPayloadCodecRuntime() CodecRuntime {
	if x != nil {
		return x.PayloadCodecRuntime
	}
	return CodecRuntime_NONE
}

func (x *CreateDeviceProfileRequest) GetPayloadCodecScript() string {
	if x != nil && x.PayloadCodecScript != nil {
		return *x.PayloadCodecScript
	}
	return ""
}

func (x *CreateDeviceProfileRequest) GetMeasurements() *Measurements {
	if x != nil {
		return x.Measurements
	}
	return nil
}

func (x *CreateDeviceProfileRequest) GetAutoDetectMeasurements() bool {
	if x != nil {
		return x.AutoDetectMeasurements
	}
	return false
}

func (x *CreateDeviceProfileRequest) GetDualChannel() bool {
	if x != nil {
		return x.DualChannel
	}
	return false
}

func (x *CreateDeviceProfileRequest) GetRepetition() bool {
	if x != nil {
		return x.Repetition
	}
	return false
}

func (x *CreateDeviceProfileRequest) GetWideCarrOff() bool {
	if x != nil {
		return x.WideCarrOff
	}
	return false
}

func (x *CreateDeviceProfileRequest) GetLongBlkDist() bool {
	if x != nil {
		return x.LongBlkDist
	}
	return false
}

func (x *CreateDeviceProfileRequest) GetTags() *common.Tags {
	if x != nil {
		return x.Tags
	}
	return nil
}

type CreateDeviceProfileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Device-profile object.
	DeviceProfile *DeviceProfile `protobuf:"bytes,1,opt,name=device_profile,json=deviceProfile,proto3" json:"device_profile,omitempty"`
	// Created at timestamp.
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDeviceProfileResponse) Reset() {
	*x = CreateDeviceProfileResponse{}
	mi := &file_api_device_profile_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDeviceProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeviceProfileResponse) ProtoMessage() {}

func (x *CreateDeviceProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_profile_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeviceProfileResponse.ProtoReflect.Descriptor instead.
func (*CreateDeviceProfileResponse) Descriptor() ([]byte, []int) {
	return file_api_device_profile_proto_rawDescGZIP(), []int{5}
}

func (x *CreateDeviceProfileResponse) GetDeviceProfile() *DeviceProfile {
	if x != nil {
		return x.DeviceProfile
	}
	return nil
}

func (x *CreateDeviceProfileResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetDeviceProfileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID (UUID).
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceProfileRequest) Reset() {
	*x = GetDeviceProfileRequest{}
	mi := &file_api_device_profile_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceProfileRequest) ProtoMessage() {}

func (x *GetDeviceProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_profile_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceProfileRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceProfileRequest) Descriptor() ([]byte, []int) {
	return file_api_device_profile_proto_rawDescGZIP(), []int{6}
}

func (x *GetDeviceProfileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetDeviceProfileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Device-profile object.
	DeviceProfile *DeviceProfile `protobuf:"bytes,1,opt,name=device_profile,json=deviceProfile,proto3" json:"device_profile,omitempty"`
	// Created at timestamp.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last update timestamp.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceProfileResponse) Reset() {
	*x = GetDeviceProfileResponse{}
	mi := &file_api_device_profile_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceProfileResponse) ProtoMessage() {}

func (x *GetDeviceProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_profile_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceProfileResponse.ProtoReflect.Descriptor instead.
func (*GetDeviceProfileResponse) Descriptor() ([]byte, []int) {
	return file_api_device_profile_proto_rawDescGZIP(), []int{7}
}

func (x *GetDeviceProfileResponse) GetDeviceProfile() *DeviceProfile {
	if x != nil {
		return x.DeviceProfile
	}
	return nil
}

func (x *GetDeviceProfileResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetDeviceProfileResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type UpdateDeviceProfileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Device-profile ID (UUID).
	// Note: on create this will be automatically generated.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Name.
	Name *string `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// Description.
	Description *string `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Manufacturer.
	Manufacturer *string `protobuf:"bytes,5,opt,name=manufacturer,proto3,oneof" json:"manufacturer,omitempty"`
	// Firmware version.
	Firmware *string `protobuf:"bytes,6,opt,name=firmware,proto3,oneof" json:"firmware,omitempty"`
	// Region.
	Region *common.Region `protobuf:"varint,7,opt,name=region,proto3,enum=common.Region,oneof" json:"region,omitempty"`
	// Device class.
	DeviceClass *common.DeviceClass `protobuf:"varint,8,opt,name=device_class,json=deviceClass,proto3,enum=common.DeviceClass,oneof" json:"device_class,omitempty"`
	// Uplink interval (seconds).
	// This defines the expected uplink interval which the device uses for
	// communication. If the uplink interval has expired and no uplink has
	// been received, the device is considered inactive.
	UplinkInterval *uint32 `protobuf:"varint,10,opt,name=uplink_interval,json=uplinkInterval,proto3,oneof" json:"uplink_interval,omitempty"`
	// Payload codec runtime.
	PayloadCodecRuntime *CodecRuntime `protobuf:"varint,11,opt,name=payload_codec_runtime,json=payloadCodecRuntime,proto3,enum=api.CodecRuntime,oneof" json:"payload_codec_runtime,omitempty"`
	// Payload codec script.
	PayloadCodecScript *string `protobuf:"bytes,12,opt,name=payload_codec_script,json=payloadCodecScript,proto3,oneof" json:"payload_codec_script,omitempty"`
	// Measurements.
	// If defined, ChirpStack will visualize these metrics in the web-interface.
	Measurements *Measurements `protobuf:"bytes,13,opt,name=measurements,proto3,oneof" json:"measurements,omitempty"`
	// Auto-detect measurements.
	// If set to true, measurements will be automatically added based on the
	// keys of the decoded payload. In cases where the decoded payload contains
	// random keys in the data, you want to set this to false.
	AutoDetectMeasurements *bool `protobuf:"varint,14,opt,name=auto_detect_measurements,json=autoDetectMeasurements,proto3,oneof" json:"auto_detect_measurements,omitempty"`
	// Tags (user defined).
	// These tags can be used to add additional information the the
	// device-profile. These tags are exposed in all the integration events of
	// devices using this device-profile.
	Tags          *common.Tags `protobuf:"bytes,19,opt,name=tags,proto3,oneof" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDeviceProfileRequest) Reset() {
	*x = UpdateDeviceProfileRequest{}
	mi := &file_api_device_profile_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeviceProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeviceProfileRequest) ProtoMessage() {}

func (x *UpdateDeviceProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_profile_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeviceProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateDeviceProfileRequest) Descriptor() ([]byte, []int) {
	return file_api_device_profile_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateDeviceProfileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateDeviceProfileRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateDeviceProfileRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateDeviceProfileRequest) GetManufacturer() string {
	if x != nil && x.Manufacturer != nil {
		return *x.Manufacturer
	}
	return ""
}

func (x *UpdateDeviceProfileRequest) GetFirmware() string {
	if x != nil && x.Firmware != nil {
		return *x.Firmware
	}
	return ""
}

func (x *UpdateDeviceProfileRequest) GetRegion() common.Region {
	if x != nil && x.Region != nil {
		return *x.Region
	}
	return common.Region(0)
}

func (x *UpdateDeviceProfileRequest) GetDeviceClass() common.DeviceClass {
	if x != nil && x.DeviceClass != nil {
		return *x.DeviceClass
	}
	return common.DeviceClass(0)
}

func (x *UpdateDeviceProfileRequest) GetUplinkInterval() uint32 {
	if x != nil && x.UplinkInterval != nil {
		return *x.UplinkInterval
	}
	return 0
}

func (x *UpdateDeviceProfileRequest) GetPayloadCodecRuntime() CodecRuntime {
	if x != nil && x.PayloadCodecRuntime != nil {
		return *x.PayloadCodecRuntime
	}
	return CodecRuntime_NONE
}

func (x *UpdateDeviceProfileRequest) GetPayloadCodecScript() string {
	if x != nil && x.PayloadCodecScript != nil {
		return *x.PayloadCodecScript
	}
	return ""
}

func (x *UpdateDeviceProfileRequest) GetMeasurements() *Measurements {
	if x != nil {
		return x.Measurements
	}
	return nil
}

func (x *UpdateDeviceProfileRequest) GetAutoDetectMeasurements() bool {
	if x != nil && x.AutoDetectMeasurements != nil {
		return *x.AutoDetectMeasurements
	}
	return false
}

func (x *UpdateDeviceProfileRequest) GetTags() *common.Tags {
	if x != nil {
		return x.Tags
	}
	return nil
}

type UpdateDeviceProfileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Device-profile object.
	DeviceProfile *DeviceProfile `protobuf:"bytes,1,opt,name=device_profile,json=deviceProfile,proto3" json:"device_profile,omitempty"`
	// Created at timestamp.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last update timestamp.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDeviceProfileResponse) Reset() {
	*x = UpdateDeviceProfileResponse{}
	mi := &file_api_device_profile_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeviceProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeviceProfileResponse) ProtoMessage() {}

func (x *UpdateDeviceProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_profile_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeviceProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateDeviceProfileResponse) Descriptor() ([]byte, []int) {
	return file_api_device_profile_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateDeviceProfileResponse) GetDeviceProfile() *DeviceProfile {
	if x != nil {
		return x.DeviceProfile
	}
	return nil
}

func (x *UpdateDeviceProfileResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UpdateDeviceProfileResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type DeleteDeviceProfileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID (UUID).
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDeviceProfileRequest) Reset() {
	*x = DeleteDeviceProfileRequest{}
	mi := &file_api_device_profile_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDeviceProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDeviceProfileRequest) ProtoMessage() {}

func (x *DeleteDeviceProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_profile_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDeviceProfileRequest.ProtoReflect.Descriptor instead.
func (*DeleteDeviceProfileRequest) Descriptor() ([]byte, []int) {
	return file_api_device_profile_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteDeviceProfileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListDeviceProfilesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant ID to list the device-profiles for.
	// To list all device-profiles as a global admin user, this field can be left blank.
	TenantId *string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3,oneof" json:"tenant_id,omitempty"`
	// Pagination. Defaults to 100 objects at page index 0.
	Paginator *Paginator `protobuf:"bytes,2,opt,name=paginator,proto3" json:"paginator,omitempty"`
	// If set, the given string will be used to search on name (optional).
	SearchName    *string `protobuf:"bytes,3,opt,name=search_name,json=searchName,proto3,oneof" json:"search_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeviceProfilesRequest) Reset() {
	*x = ListDeviceProfilesRequest{}
	mi := &file_api_device_profile_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeviceProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeviceProfilesRequest) ProtoMessage() {}

func (x *ListDeviceProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_profile_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeviceProfilesRequest.ProtoReflect.Descriptor instead.
func (*ListDeviceProfilesRequest) Descriptor() ([]byte, []int) {
	return file_api_device_profile_proto_rawDescGZIP(), []int{11}
}

func (x *ListDeviceProfilesRequest) GetTenantId() string {
	if x != nil && x.TenantId != nil {
		return *x.TenantId
	}
	return ""
}

func (x *ListDeviceProfilesRequest) GetPaginator() *Paginator {
	if x != nil {
		return x.Paginator
	}
	return nil
}

func (x *ListDeviceProfilesRequest) GetSearchName() string {
	if x != nil && x.SearchName != nil {
		return *x.SearchName
	}
	return ""
}

type ListDeviceProfilesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pagination.
	Pagination *Pagination `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// Result-set.
	Result        []*DeviceProfileListItem `protobuf:"bytes,2,rep,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeviceProfilesResponse) Reset() {
	*x = ListDeviceProfilesResponse{}
	mi := &file_api_device_profile_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeviceProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeviceProfilesResponse) ProtoMessage() {}

func (x *ListDeviceProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_profile_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeviceProfilesResponse.ProtoReflect.Descriptor instead.
func (*ListDeviceProfilesResponse) Descriptor() ([]byte, []int) {
	return file_api_device_profile_proto_rawDescGZIP(), []int{12}
}

func (x *ListDeviceProfilesResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListDeviceProfilesResponse) GetResult() []*DeviceProfileListItem {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_api_device_profile_proto protoreflect.FileDescriptor

const file_api_device_profile_proto_rawDesc = "" +
	"\n" +
	"\x18api/device_profile.proto\x12\x03api\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x13common/common.proto\x1a\x10api/common.proto\"\x9e\x05\n" +
	"\rDeviceProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\"\n" +
	"\fmanufacturer\x18\x05 \x01(\tR\fmanufacturer\x12\x1a\n" +
	"\bfirmware\x18\x06 \x01(\tR\bfirmware\x12&\n" +
	"\x06region\x18\a \x01(\x0e2\x0e.common.RegionR\x06region\x126\n" +
	"\fdevice_class\x18\b \x01(\x0e2\x13.common.DeviceClassR\vdeviceClass\x12'\n" +
	"\x0fuplink_interval\x18\n" +
	" \x01(\rR\x0euplinkInterval\x12E\n" +
	"\x15payload_codec_runtime\x18\v \x01(\x0e2\x11.api.CodecRuntimeR\x13payloadCodecRuntime\x125\n" +
	"\x14payload_codec_script\x18\f \x01(\tH\x01R\x12payloadCodecScript\x88\x01\x01\x12:\n" +
	"\fmeasurements\x18\x14 \x01(\v2\x11.api.MeasurementsH\x02R\fmeasurements\x88\x01\x01\x128\n" +
	"\x18auto_detect_measurements\x18\x15 \x01(\bR\x16autoDetectMeasurements\x12%\n" +
	"\x04tags\x18\x1a \x01(\v2\f.common.TagsH\x03R\x04tags\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\x17\n" +
	"\x15_payload_codec_scriptB\x0f\n" +
	"\r_measurementsB\a\n" +
	"\x05_tags\"\xaa\x01\n" +
	"\fMeasurements\x12G\n" +
	"\fmeasurements\x18\x01 \x03(\v2#.api.Measurements.MeasurementsEntryR\fmeasurements\x1aQ\n" +
	"\x11MeasurementsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.api.MeasurementR\x05value:\x028\x01\"K\n" +
	"\vMeasurement\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12(\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x14.api.MeasurementKindR\x04kind\"\xae\x02\n" +
	"\x15DeviceProfileListItem\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12&\n" +
	"\x06region\x18\x06 \x01(\x0e2\x0e.common.RegionR\x06region\x126\n" +
	"\fdevice_class\x18\a \x01(\x0e2\x13.common.DeviceClassR\vdeviceClass\"\xf3\x06\n" +
	"\x1aCreateDeviceProfileRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\"\n" +
	"\fmanufacturer\x18\x04 \x01(\tR\fmanufacturer\x12\x1a\n" +
	"\bfirmware\x18\x05 \x01(\tR\bfirmware\x12&\n" +
	"\x06region\x18\x06 \x01(\x0e2\x0e.common.RegionR\x06region\x126\n" +
	"\fdevice_class\x18\a \x01(\x0e2\x13.common.DeviceClassR\vdeviceClass\x12<\n" +
	"\n" +
	"mac_format\x18\b \x01(\x0e2\x18.common.MacPayloadFormatH\x01R\tmacFormat\x88\x01\x01\x12'\n" +
	"\x0fuplink_interval\x18\t \x01(\rR\x0euplinkInterval\x12E\n" +
	"\x15payload_codec_runtime\x18\n" +
	" \x01(\x0e2\x11.api.CodecRuntimeR\x13payloadCodecRuntime\x125\n" +
	"\x14payload_codec_script\x18\v \x01(\tH\x02R\x12payloadCodecScript\x88\x01\x01\x12:\n" +
	"\fmeasurements\x18\f \x01(\v2\x11.api.MeasurementsH\x03R\fmeasurements\x88\x01\x01\x128\n" +
	"\x18auto_detect_measurements\x18\r \x01(\bR\x16autoDetectMeasurements\x12!\n" +
	"\fdual_channel\x18\x0e \x01(\bR\vdualChannel\x12\x1e\n" +
	"\n" +
	"repetition\x18\x0f \x01(\bR\n" +
	"repetition\x12\"\n" +
	"\rwide_carr_off\x18\x10 \x01(\bR\vwideCarrOff\x12\"\n" +
	"\rlong_blk_dist\x18\x11 \x01(\bR\vlongBlkDist\x12%\n" +
	"\x04tags\x18\x12 \x01(\v2\f.common.TagsH\x04R\x04tags\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\r\n" +
	"\v_mac_formatB\x17\n" +
	"\x15_payload_codec_scriptB\x0f\n" +
	"\r_measurementsB\a\n" +
	"\x05_tags\"\x93\x01\n" +
	"\x1bCreateDeviceProfileResponse\x129\n" +
	"\x0edevice_profile\x18\x01 \x01(\v2\x12.api.DeviceProfileR\rdeviceProfile\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\")\n" +
	"\x17GetDeviceProfileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xcb\x01\n" +
	"\x18GetDeviceProfileResponse\x129\n" +
	"\x0edevice_profile\x18\x01 \x01(\v2\x12.api.DeviceProfileR\rdeviceProfile\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xc4\x06\n" +
	"\x1aUpdateDeviceProfileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x01R\vdescription\x88\x01\x01\x12'\n" +
	"\fmanufacturer\x18\x05 \x01(\tH\x02R\fmanufacturer\x88\x01\x01\x12\x1f\n" +
	"\bfirmware\x18\x06 \x01(\tH\x03R\bfirmware\x88\x01\x01\x12+\n" +
	"\x06region\x18\a \x01(\x0e2\x0e.common.RegionH\x04R\x06region\x88\x01\x01\x12;\n" +
	"\fdevice_class\x18\b \x01(\x0e2\x13.common.DeviceClassH\x05R\vdeviceClass\x88\x01\x01\x12,\n" +
	"\x0fuplink_interval\x18\n" +
	" \x01(\rH\x06R\x0euplinkInterval\x88\x01\x01\x12J\n" +
	"\x15payload_codec_runtime\x18\v \x01(\x0e2\x11.api.CodecRuntimeH\aR\x13payloadCodecRuntime\x88\x01\x01\x125\n" +
	"\x14payload_codec_script\x18\f \x01(\tH\bR\x12payloadCodecScript\x88\x01\x01\x12:\n" +
	"\fmeasurements\x18\r \x01(\v2\x11.api.MeasurementsH\tR\fmeasurements\x88\x01\x01\x12=\n" +
	"\x18auto_detect_measurements\x18\x0e \x01(\bH\n" +
	"R\x16autoDetectMeasurements\x88\x01\x01\x12%\n" +
	"\x04tags\x18\x13 \x01(\v2\f.common.TagsH\vR\x04tags\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\x0f\n" +
	"\r_manufacturerB\v\n" +
	"\t_firmwareB\t\n" +
	"\a_regionB\x0f\n" +
	"\r_device_classB\x12\n" +
	"\x10_uplink_intervalB\x18\n" +
	"\x16_payload_codec_runtimeB\x17\n" +
	"\x15_payload_codec_scriptB\x0f\n" +
	"\r_measurementsB\x1b\n" +
	"\x19_auto_detect_measurementsB\a\n" +
	"\x05_tags\"\xce\x01\n" +
	"\x1bUpdateDeviceProfileResponse\x129\n" +
	"\x0edevice_profile\x18\x01 \x01(\v2\x12.api.DeviceProfileR\rdeviceProfile\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\",\n" +
	"\x1aDeleteDeviceProfileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xaf\x01\n" +
	"\x19ListDeviceProfilesRequest\x12 \n" +
	"\ttenant_id\x18\x01 \x01(\tH\x00R\btenantId\x88\x01\x01\x12,\n" +
	"\tpaginator\x18\x02 \x01(\v2\x0e.api.PaginatorR\tpaginator\x12$\n" +
	"\vsearch_name\x18\x03 \x01(\tH\x01R\n" +
	"searchName\x88\x01\x01B\f\n" +
	"\n" +
	"_tenant_idB\x0e\n" +
	"\f_search_name\"\x81\x01\n" +
	"\x1aListDeviceProfilesResponse\x12/\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x0f.api.PaginationR\n" +
	"pagination\x122\n" +
	"\x06result\x18\x02 \x03(\v2\x1a.api.DeviceProfileListItemR\x06result*A\n" +
	"\fCodecRuntime\x12\b\n" +
	"\x04NONE\x10\x00\x12\r\n" +
	"\tBLUEPRINT\x10\x01\x12\x06\n" +
	"\x02JS\x10\x02\x12\x10\n" +
	"\fIO_LINK_IODD\x10\x03*P\n" +
	"\x0fMeasurementKind\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aCOUNTER\x10\x01\x12\f\n" +
	"\bABSOLUTE\x10\x02\x12\t\n" +
	"\x05GAUGE\x10\x03\x12\n" +
	"\n" +
	"\x06STRING\x10\x042\xed\x04\n" +
	"\x14DeviceProfileService\x12y\n" +
	"\x13CreateDeviceProfile\x12\x1f.api.CreateDeviceProfileRequest\x1a .api.CreateDeviceProfileResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/device-profiles\x12r\n" +
	"\x10GetDeviceProfile\x12\x1c.api.GetDeviceProfileRequest\x1a\x1d.api.GetDeviceProfileResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/device-profiles/{id}\x12~\n" +
	"\x13UpdateDeviceProfile\x12\x1f.api.UpdateDeviceProfileRequest\x1a .api.UpdateDeviceProfileResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\x1a\x19/api/device-profiles/{id}\x12q\n" +
	"\x13DeleteDeviceProfile\x12\x1f.api.DeleteDeviceProfileRequest\x1a\x16.google.protobuf.Empty\"!\x82\xd3\xe4\x93\x02\x1b*\x19/api/device-profiles/{id}\x12s\n" +
	"\x12ListDeviceProfiles\x12\x1e.api.ListDeviceProfilesRequest\x1a\x1f.api.ListDeviceProfilesResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/device-profilesB\xb0\x01\n" +
	"\x11io.splitstack.apiB\x12DeviceProfileProtoP\x01Z4github.com/SplitStackServer/splitstack/api/go/v5/api\xaa\x02\x14SplitStackServer.Api\xca\x02\x14SplitStackServer\\Api\xe2\x02 GPBMetadata\\SplitStackServer\\Apib\x06proto3"

var (
	file_api_device_profile_proto_rawDescOnce sync.Once
	file_api_device_profile_proto_rawDescData []byte
)

func file_api_device_profile_proto_rawDescGZIP() []byte {
	file_api_device_profile_proto_rawDescOnce.Do(func() {
		file_api_device_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_device_profile_proto_rawDesc), len(file_api_device_profile_proto_rawDesc)))
	})
	return file_api_device_profile_proto_rawDescData
}

var file_api_device_profile_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_device_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_device_profile_proto_goTypes = []any{
	(CodecRuntime)(0),                   // 0: api.CodecRuntime
	(MeasurementKind)(0),                // 1: api.MeasurementKind
	(*DeviceProfile)(nil),               // 2: api.DeviceProfile
	(*Measurements)(nil),                // 3: api.Measurements
	(*Measurement)(nil),                 // 4: api.Measurement
	(*DeviceProfileListItem)(nil),       // 5: api.DeviceProfileListItem
	(*CreateDeviceProfileRequest)(nil),  // 6: api.CreateDeviceProfileRequest
	(*CreateDeviceProfileResponse)(nil), // 7: api.CreateDeviceProfileResponse
	(*GetDeviceProfileRequest)(nil),     // 8: api.GetDeviceProfileRequest
	(*GetDeviceProfileResponse)(nil),    // 9: api.GetDeviceProfileResponse
	(*UpdateDeviceProfileRequest)(nil),  // 10: api.UpdateDeviceProfileRequest
	(*UpdateDeviceProfileResponse)(nil), // 11: api.UpdateDeviceProfileResponse
	(*DeleteDeviceProfileRequest)(nil),  // 12: api.DeleteDeviceProfileRequest
	(*ListDeviceProfilesRequest)(nil),   // 13: api.ListDeviceProfilesRequest
	(*ListDeviceProfilesResponse)(nil),  // 14: api.ListDeviceProfilesResponse
	nil,                                 // 15: api.Measurements.MeasurementsEntry
	(common.Region)(0),                  // 16: common.Region
	(common.DeviceClass)(0),             // 17: common.DeviceClass
	(*common.Tags)(nil),                 // 18: common.Tags
	(*timestamppb.Timestamp)(nil),       // 19: google.protobuf.Timestamp
	(common.MacPayloadFormat)(0),        // 20: common.MacPayloadFormat
	(*Paginator)(nil),                   // 21: api.Paginator
	(*Pagination)(nil),                  // 22: api.Pagination
	(*emptypb.Empty)(nil),               // 23: google.protobuf.Empty
}
var file_api_device_profile_proto_depIdxs = []int32{
	16, // 0: api.DeviceProfile.region:type_name -> common.Region
	17, // 1: api.DeviceProfile.device_class:type_name -> common.DeviceClass
	0,  // 2: api.DeviceProfile.payload_codec_runtime:type_name -> api.CodecRuntime
	3,  // 3: api.DeviceProfile.measurements:type_name -> api.Measurements
	18, // 4: api.DeviceProfile.tags:type_name -> common.Tags
	15, // 5: api.Measurements.measurements:type_name -> api.Measurements.MeasurementsEntry
	1,  // 6: api.Measurement.kind:type_name -> api.MeasurementKind
	19, // 7: api.DeviceProfileListItem.created_at:type_name -> google.protobuf.Timestamp
	19, // 8: api.DeviceProfileListItem.updated_at:type_name -> google.protobuf.Timestamp
	16, // 9: api.DeviceProfileListItem.region:type_name -> common.Region
	17, // 10: api.DeviceProfileListItem.device_class:type_name -> common.DeviceClass
	16, // 11: api.CreateDeviceProfileRequest.region:type_name -> common.Region
	17, // 12: api.CreateDeviceProfileRequest.device_class:type_name -> common.DeviceClass
	20, // 13: api.CreateDeviceProfileRequest.mac_format:type_name -> common.MacPayloadFormat
	0,  // 14: api.CreateDeviceProfileRequest.payload_codec_runtime:type_name -> api.CodecRuntime
	3,  // 15: api.CreateDeviceProfileRequest.measurements:type_name -> api.Measurements
	18, // 16: api.CreateDeviceProfileRequest.tags:type_name -> common.Tags
	2,  // 17: api.CreateDeviceProfileResponse.device_profile:type_name -> api.DeviceProfile
	19, // 18: api.CreateDeviceProfileResponse.created_at:type_name -> google.protobuf.Timestamp
	2,  // 19: api.GetDeviceProfileResponse.device_profile:type_name -> api.DeviceProfile
	19, // 20: api.GetDeviceProfileResponse.created_at:type_name -> google.protobuf.Timestamp
	19, // 21: api.GetDeviceProfileResponse.updated_at:type_name -> google.protobuf.Timestamp
	16, // 22: api.UpdateDeviceProfileRequest.region:type_name -> common.Region
	17, // 23: api.UpdateDeviceProfileRequest.device_class:type_name -> common.DeviceClass
	0,  // 24: api.UpdateDeviceProfileRequest.payload_codec_runtime:type_name -> api.CodecRuntime
	3,  // 25: api.UpdateDeviceProfileRequest.measurements:type_name -> api.Measurements
	18, // 26: api.UpdateDeviceProfileRequest.tags:type_name -> common.Tags
	2,  // 27: api.UpdateDeviceProfileResponse.device_profile:type_name -> api.DeviceProfile
	19, // 28: api.UpdateDeviceProfileResponse.created_at:type_name -> google.protobuf.Timestamp
	19, // 29: api.UpdateDeviceProfileResponse.updated_at:type_name -> google.protobuf.Timestamp
	21, // 30: api.ListDeviceProfilesRequest.paginator:type_name -> api.Paginator
	22, // 31: api.ListDeviceProfilesResponse.pagination:type_name -> api.Pagination
	5,  // 32: api.ListDeviceProfilesResponse.result:type_name -> api.DeviceProfileListItem
	4,  // 33: api.Measurements.MeasurementsEntry.value:type_name -> api.Measurement
	6,  // 34: api.DeviceProfileService.CreateDeviceProfile:input_type -> api.CreateDeviceProfileRequest
	8,  // 35: api.DeviceProfileService.GetDeviceProfile:input_type -> api.GetDeviceProfileRequest
	10, // 36: api.DeviceProfileService.UpdateDeviceProfile:input_type -> api.UpdateDeviceProfileRequest
	12, // 37: api.DeviceProfileService.DeleteDeviceProfile:input_type -> api.DeleteDeviceProfileRequest
	13, // 38: api.DeviceProfileService.ListDeviceProfiles:input_type -> api.ListDeviceProfilesRequest
	7,  // 39: api.DeviceProfileService.CreateDeviceProfile:output_type -> api.CreateDeviceProfileResponse
	9,  // 40: api.DeviceProfileService.GetDeviceProfile:output_type -> api.GetDeviceProfileResponse
	11, // 41: api.DeviceProfileService.UpdateDeviceProfile:output_type -> api.UpdateDeviceProfileResponse
	23, // 42: api.DeviceProfileService.DeleteDeviceProfile:output_type -> google.protobuf.Empty
	14, // 43: api.DeviceProfileService.ListDeviceProfiles:output_type -> api.ListDeviceProfilesResponse
	39, // [39:44] is the sub-list for method output_type
	34, // [34:39] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_api_device_profile_proto_init() }
func file_api_device_profile_proto_init() {
	if File_api_device_profile_proto != nil {
		return
	}
	file_api_common_proto_init()
	file_api_device_profile_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_device_profile_proto_msgTypes[4].OneofWrappers = []any{}
	file_api_device_profile_proto_msgTypes[8].OneofWrappers = []any{}
	file_api_device_profile_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_device_profile_proto_rawDesc), len(file_api_device_profile_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_device_profile_proto_goTypes,
		DependencyIndexes: file_api_device_profile_proto_depIdxs,
		EnumInfos:         file_api_device_profile_proto_enumTypes,
		MessageInfos:      file_api_device_profile_proto_msgTypes,
	}.Build()
	File_api_device_profile_proto = out.File
	file_api_device_profile_proto_goTypes = nil
	file_api_device_profile_proto_depIdxs = nil
}
