// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: api/device_key.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeviceKeyService_CreateDeviceKey_FullMethodName = "/api.DeviceKeyService/CreateDeviceKey"
	DeviceKeyService_GetDeviceKey_FullMethodName    = "/api.DeviceKeyService/GetDeviceKey"
	DeviceKeyService_UpdateDeviceKey_FullMethodName = "/api.DeviceKeyService/UpdateDeviceKey"
)

// DeviceKeyServiceClient is the client API for DeviceKeyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DeviceService is the service providing API methods for managing devices.
type DeviceKeyServiceClient interface {
	// Create the given device-keys.
	CreateDeviceKey(ctx context.Context, in *CreateDeviceKeyRequest, opts ...grpc.CallOption) (*CreateDeviceKeyResponse, error)
	// Get the device-keys for the given DevEUI.
	GetDeviceKey(ctx context.Context, in *GetDeviceKeyRequest, opts ...grpc.CallOption) (*GetDeviceKeyResponse, error)
	// Update the given device-keys.
	UpdateDeviceKey(ctx context.Context, in *UpdateDeviceKeyRequest, opts ...grpc.CallOption) (*UpdateDeviceKeyResponse, error)
}

type deviceKeyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeviceKeyServiceClient(cc grpc.ClientConnInterface) DeviceKeyServiceClient {
	return &deviceKeyServiceClient{cc}
}

func (c *deviceKeyServiceClient) CreateDeviceKey(ctx context.Context, in *CreateDeviceKeyRequest, opts ...grpc.CallOption) (*CreateDeviceKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDeviceKeyResponse)
	err := c.cc.Invoke(ctx, DeviceKeyService_CreateDeviceKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceKeyServiceClient) GetDeviceKey(ctx context.Context, in *GetDeviceKeyRequest, opts ...grpc.CallOption) (*GetDeviceKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeviceKeyResponse)
	err := c.cc.Invoke(ctx, DeviceKeyService_GetDeviceKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceKeyServiceClient) UpdateDeviceKey(ctx context.Context, in *UpdateDeviceKeyRequest, opts ...grpc.CallOption) (*UpdateDeviceKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDeviceKeyResponse)
	err := c.cc.Invoke(ctx, DeviceKeyService_UpdateDeviceKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeviceKeyServiceServer is the server API for DeviceKeyService service.
// All implementations must embed UnimplementedDeviceKeyServiceServer
// for forward compatibility.
//
// DeviceService is the service providing API methods for managing devices.
type DeviceKeyServiceServer interface {
	// Create the given device-keys.
	CreateDeviceKey(context.Context, *CreateDeviceKeyRequest) (*CreateDeviceKeyResponse, error)
	// Get the device-keys for the given DevEUI.
	GetDeviceKey(context.Context, *GetDeviceKeyRequest) (*GetDeviceKeyResponse, error)
	// Update the given device-keys.
	UpdateDeviceKey(context.Context, *UpdateDeviceKeyRequest) (*UpdateDeviceKeyResponse, error)
	mustEmbedUnimplementedDeviceKeyServiceServer()
}

// UnimplementedDeviceKeyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeviceKeyServiceServer struct{}

func (UnimplementedDeviceKeyServiceServer) CreateDeviceKey(context.Context, *CreateDeviceKeyRequest) (*CreateDeviceKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDeviceKey not implemented")
}
func (UnimplementedDeviceKeyServiceServer) GetDeviceKey(context.Context, *GetDeviceKeyRequest) (*GetDeviceKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeviceKey not implemented")
}
func (UnimplementedDeviceKeyServiceServer) UpdateDeviceKey(context.Context, *UpdateDeviceKeyRequest) (*UpdateDeviceKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDeviceKey not implemented")
}
func (UnimplementedDeviceKeyServiceServer) mustEmbedUnimplementedDeviceKeyServiceServer() {}
func (UnimplementedDeviceKeyServiceServer) testEmbeddedByValue()                          {}

// UnsafeDeviceKeyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeviceKeyServiceServer will
// result in compilation errors.
type UnsafeDeviceKeyServiceServer interface {
	mustEmbedUnimplementedDeviceKeyServiceServer()
}

func RegisterDeviceKeyServiceServer(s grpc.ServiceRegistrar, srv DeviceKeyServiceServer) {
	// If the following call pancis, it indicates UnimplementedDeviceKeyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeviceKeyService_ServiceDesc, srv)
}

func _DeviceKeyService_CreateDeviceKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDeviceKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceKeyServiceServer).CreateDeviceKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceKeyService_CreateDeviceKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceKeyServiceServer).CreateDeviceKey(ctx, req.(*CreateDeviceKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceKeyService_GetDeviceKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceKeyServiceServer).GetDeviceKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceKeyService_GetDeviceKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceKeyServiceServer).GetDeviceKey(ctx, req.(*GetDeviceKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceKeyService_UpdateDeviceKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDeviceKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceKeyServiceServer).UpdateDeviceKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceKeyService_UpdateDeviceKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceKeyServiceServer).UpdateDeviceKey(ctx, req.(*UpdateDeviceKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeviceKeyService_ServiceDesc is the grpc.ServiceDesc for DeviceKeyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeviceKeyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.DeviceKeyService",
	HandlerType: (*DeviceKeyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDeviceKey",
			Handler:    _DeviceKeyService_CreateDeviceKey_Handler,
		},
		{
			MethodName: "GetDeviceKey",
			Handler:    _DeviceKeyService_GetDeviceKey_Handler,
		},
		{
			MethodName: "UpdateDeviceKey",
			Handler:    _DeviceKeyService_UpdateDeviceKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/device_key.proto",
}
