// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api/stats.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetGlobalStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGlobalStatsRequest) Reset() {
	*x = GetGlobalStatsRequest{}
	mi := &file_api_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGlobalStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGlobalStatsRequest) ProtoMessage() {}

func (x *GetGlobalStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGlobalStatsRequest.ProtoReflect.Descriptor instead.
func (*GetGlobalStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_stats_proto_rawDescGZIP(), []int{0}
}

type GetGlobalStatsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total number of users in the system.
	TotalUsers uint64 `protobuf:"varint,1,opt,name=total_users,json=totalUsers,proto3" json:"total_users,omitempty"`
	// Total number of tenants in the system.
	TotalTenants uint64 `protobuf:"varint,2,opt,name=total_tenants,json=totalTenants,proto3" json:"total_tenants,omitempty"`
	// Global device counts.
	DeviceCount *DeviceCount `protobuf:"bytes,6,opt,name=device_count,json=deviceCount,proto3" json:"device_count,omitempty"`
	// Global basestation counts.
	BasestationCount *BasestationCount `protobuf:"bytes,4,opt,name=basestation_count,json=basestationCount,proto3" json:"basestation_count,omitempty"`
	// Global application counts.
	ApplicationCount *ApplicationCount `protobuf:"bytes,5,opt,name=application_count,json=applicationCount,proto3" json:"application_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetGlobalStatsResponse) Reset() {
	*x = GetGlobalStatsResponse{}
	mi := &file_api_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGlobalStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGlobalStatsResponse) ProtoMessage() {}

func (x *GetGlobalStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGlobalStatsResponse.ProtoReflect.Descriptor instead.
func (*GetGlobalStatsResponse) Descriptor() ([]byte, []int) {
	return file_api_stats_proto_rawDescGZIP(), []int{1}
}

func (x *GetGlobalStatsResponse) GetTotalUsers() uint64 {
	if x != nil {
		return x.TotalUsers
	}
	return 0
}

func (x *GetGlobalStatsResponse) GetTotalTenants() uint64 {
	if x != nil {
		return x.TotalTenants
	}
	return 0
}

func (x *GetGlobalStatsResponse) GetDeviceCount() *DeviceCount {
	if x != nil {
		return x.DeviceCount
	}
	return nil
}

func (x *GetGlobalStatsResponse) GetBasestationCount() *BasestationCount {
	if x != nil {
		return x.BasestationCount
	}
	return nil
}

func (x *GetGlobalStatsResponse) GetApplicationCount() *ApplicationCount {
	if x != nil {
		return x.ApplicationCount
	}
	return nil
}

type GetVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionRequest) Reset() {
	*x = GetVersionRequest{}
	mi := &file_api_stats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionRequest) ProtoMessage() {}

func (x *GetVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_stats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionRequest.ProtoReflect.Descriptor instead.
func (*GetVersionRequest) Descriptor() ([]byte, []int) {
	return file_api_stats_proto_rawDescGZIP(), []int{2}
}

type GetVersionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The version of the SplitStack server.
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// The build date of the SplitStack server.
	BuildDate string `protobuf:"bytes,2,opt,name=build_date,json=buildDate,proto3" json:"build_date,omitempty"`
	// The git commit hash of the SplitStack server.
	GitCommit     string `protobuf:"bytes,3,opt,name=git_commit,json=gitCommit,proto3" json:"git_commit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionResponse) Reset() {
	*x = GetVersionResponse{}
	mi := &file_api_stats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionResponse) ProtoMessage() {}

func (x *GetVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_stats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionResponse.ProtoReflect.Descriptor instead.
func (*GetVersionResponse) Descriptor() ([]byte, []int) {
	return file_api_stats_proto_rawDescGZIP(), []int{3}
}

func (x *GetVersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetVersionResponse) GetBuildDate() string {
	if x != nil {
		return x.BuildDate
	}
	return ""
}

func (x *GetVersionResponse) GetGitCommit() string {
	if x != nil {
		return x.GitCommit
	}
	return ""
}

var File_api_stats_proto protoreflect.FileDescriptor

const file_api_stats_proto_rawDesc = "" +
	"\n" +
	"\x0fapi/stats.proto\x12\x03api\x1a\x1cgoogle/api/annotations.proto\x1a\x10api/common.proto\"\x17\n" +
	"\x15GetGlobalStatsRequest\"\x9b\x02\n" +
	"\x16GetGlobalStatsResponse\x12\x1f\n" +
	"\vtotal_users\x18\x01 \x01(\x04R\n" +
	"totalUsers\x12#\n" +
	"\rtotal_tenants\x18\x02 \x01(\x04R\ftotalTenants\x123\n" +
	"\fdevice_count\x18\x06 \x01(\v2\x10.api.DeviceCountR\vdeviceCount\x12B\n" +
	"\x11basestation_count\x18\x04 \x01(\v2\x15.api.BasestationCountR\x10basestationCount\x12B\n" +
	"\x11application_count\x18\x05 \x01(\v2\x15.api.ApplicationCountR\x10applicationCount\"\x13\n" +
	"\x11GetVersionRequest\"l\n" +
	"\x12GetVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"build_date\x18\x02 \x01(\tR\tbuildDate\x12\x1d\n" +
	"\n" +
	"git_commit\x18\x03 \x01(\tR\tgitCommit2\xcf\x01\n" +
	"\fStatsService\x12d\n" +
	"\x0eGetGlobalStats\x12\x1a.api.GetGlobalStatsRequest\x1a\x1b.api.GetGlobalStatsResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/stats/global\x12Y\n" +
	"\n" +
	"GetVersion\x12\x16.api.GetVersionRequest\x1a\x17.api.GetVersionResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/stats/versionB\xaa\x01\n" +
	"\x11io.splitstack.apiB\n" +
	"StatsProtoP\x01Z6github.com/SplitStackServer/splitstack-grpc-api/go/api\xaa\x02\x14SplitStackServer.Api\xca\x02\x14SplitStackServer\\Api\xe2\x02 GPBMetadata\\SplitStackServer\\Apib\x06proto3"

var (
	file_api_stats_proto_rawDescOnce sync.Once
	file_api_stats_proto_rawDescData []byte
)

func file_api_stats_proto_rawDescGZIP() []byte {
	file_api_stats_proto_rawDescOnce.Do(func() {
		file_api_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_stats_proto_rawDesc), len(file_api_stats_proto_rawDesc)))
	})
	return file_api_stats_proto_rawDescData
}

var file_api_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_stats_proto_goTypes = []any{
	(*GetGlobalStatsRequest)(nil),  // 0: api.GetGlobalStatsRequest
	(*GetGlobalStatsResponse)(nil), // 1: api.GetGlobalStatsResponse
	(*GetVersionRequest)(nil),      // 2: api.GetVersionRequest
	(*GetVersionResponse)(nil),     // 3: api.GetVersionResponse
	(*DeviceCount)(nil),            // 4: api.DeviceCount
	(*BasestationCount)(nil),       // 5: api.BasestationCount
	(*ApplicationCount)(nil),       // 6: api.ApplicationCount
}
var file_api_stats_proto_depIdxs = []int32{
	4, // 0: api.GetGlobalStatsResponse.device_count:type_name -> api.DeviceCount
	5, // 1: api.GetGlobalStatsResponse.basestation_count:type_name -> api.BasestationCount
	6, // 2: api.GetGlobalStatsResponse.application_count:type_name -> api.ApplicationCount
	0, // 3: api.StatsService.GetGlobalStats:input_type -> api.GetGlobalStatsRequest
	2, // 4: api.StatsService.GetVersion:input_type -> api.GetVersionRequest
	1, // 5: api.StatsService.GetGlobalStats:output_type -> api.GetGlobalStatsResponse
	3, // 6: api.StatsService.GetVersion:output_type -> api.GetVersionResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_stats_proto_init() }
func file_api_stats_proto_init() {
	if File_api_stats_proto != nil {
		return
	}
	file_api_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_stats_proto_rawDesc), len(file_api_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_stats_proto_goTypes,
		DependencyIndexes: file_api_stats_proto_depIdxs,
		MessageInfos:      file_api_stats_proto_msgTypes,
	}.Build()
	File_api_stats_proto = out.File
	file_api_stats_proto_goTypes = nil
	file_api_stats_proto_depIdxs = nil
}
