// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: api/tenant_user.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TenantUserService_AddTenantUser_FullMethodName    = "/api.TenantUserService/AddTenantUser"
	TenantUserService_GetTenantUser_FullMethodName    = "/api.TenantUserService/GetTenantUser"
	TenantUserService_UpdateTenantUser_FullMethodName = "/api.TenantUserService/UpdateTenantUser"
	TenantUserService_DeleteTenantUser_FullMethodName = "/api.TenantUserService/DeleteTenantUser"
	TenantUserService_ListTenantUsers_FullMethodName  = "/api.TenantUserService/ListTenantUsers"
)

// TenantUserServiceClient is the client API for TenantUserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TenantUserService is the service providing API methods for managing tenant users.
type TenantUserServiceClient interface {
	// Add an user to the tenant.
	// Note: the user must already exist.
	AddTenantUser(ctx context.Context, in *AddTenantUserRequest, opts ...grpc.CallOption) (*AddTenantUserResponse, error)
	// Get the the tenant user for the given tenant and user IDs.
	GetTenantUser(ctx context.Context, in *GetTenantUserRequest, opts ...grpc.CallOption) (*GetTenantUserResponse, error)
	// Update the given tenant user.
	UpdateTenantUser(ctx context.Context, in *UpdateTenantUserRequest, opts ...grpc.CallOption) (*UpdateTenantUserResponse, error)
	// Delete the given tenant user.
	DeleteTenantUser(ctx context.Context, in *DeleteTenantUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Get the list of tenant users.
	ListTenantUsers(ctx context.Context, in *ListTenantUsersRequest, opts ...grpc.CallOption) (*ListTenantUsersResponse, error)
}

type tenantUserServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTenantUserServiceClient(cc grpc.ClientConnInterface) TenantUserServiceClient {
	return &tenantUserServiceClient{cc}
}

func (c *tenantUserServiceClient) AddTenantUser(ctx context.Context, in *AddTenantUserRequest, opts ...grpc.CallOption) (*AddTenantUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddTenantUserResponse)
	err := c.cc.Invoke(ctx, TenantUserService_AddTenantUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantUserServiceClient) GetTenantUser(ctx context.Context, in *GetTenantUserRequest, opts ...grpc.CallOption) (*GetTenantUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTenantUserResponse)
	err := c.cc.Invoke(ctx, TenantUserService_GetTenantUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantUserServiceClient) UpdateTenantUser(ctx context.Context, in *UpdateTenantUserRequest, opts ...grpc.CallOption) (*UpdateTenantUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTenantUserResponse)
	err := c.cc.Invoke(ctx, TenantUserService_UpdateTenantUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantUserServiceClient) DeleteTenantUser(ctx context.Context, in *DeleteTenantUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TenantUserService_DeleteTenantUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantUserServiceClient) ListTenantUsers(ctx context.Context, in *ListTenantUsersRequest, opts ...grpc.CallOption) (*ListTenantUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTenantUsersResponse)
	err := c.cc.Invoke(ctx, TenantUserService_ListTenantUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TenantUserServiceServer is the server API for TenantUserService service.
// All implementations must embed UnimplementedTenantUserServiceServer
// for forward compatibility.
//
// TenantUserService is the service providing API methods for managing tenant users.
type TenantUserServiceServer interface {
	// Add an user to the tenant.
	// Note: the user must already exist.
	AddTenantUser(context.Context, *AddTenantUserRequest) (*AddTenantUserResponse, error)
	// Get the the tenant user for the given tenant and user IDs.
	GetTenantUser(context.Context, *GetTenantUserRequest) (*GetTenantUserResponse, error)
	// Update the given tenant user.
	UpdateTenantUser(context.Context, *UpdateTenantUserRequest) (*UpdateTenantUserResponse, error)
	// Delete the given tenant user.
	DeleteTenantUser(context.Context, *DeleteTenantUserRequest) (*emptypb.Empty, error)
	// Get the list of tenant users.
	ListTenantUsers(context.Context, *ListTenantUsersRequest) (*ListTenantUsersResponse, error)
	mustEmbedUnimplementedTenantUserServiceServer()
}

// UnimplementedTenantUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTenantUserServiceServer struct{}

func (UnimplementedTenantUserServiceServer) AddTenantUser(context.Context, *AddTenantUserRequest) (*AddTenantUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTenantUser not implemented")
}
func (UnimplementedTenantUserServiceServer) GetTenantUser(context.Context, *GetTenantUserRequest) (*GetTenantUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTenantUser not implemented")
}
func (UnimplementedTenantUserServiceServer) UpdateTenantUser(context.Context, *UpdateTenantUserRequest) (*UpdateTenantUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTenantUser not implemented")
}
func (UnimplementedTenantUserServiceServer) DeleteTenantUser(context.Context, *DeleteTenantUserRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTenantUser not implemented")
}
func (UnimplementedTenantUserServiceServer) ListTenantUsers(context.Context, *ListTenantUsersRequest) (*ListTenantUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTenantUsers not implemented")
}
func (UnimplementedTenantUserServiceServer) mustEmbedUnimplementedTenantUserServiceServer() {}
func (UnimplementedTenantUserServiceServer) testEmbeddedByValue()                           {}

// UnsafeTenantUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TenantUserServiceServer will
// result in compilation errors.
type UnsafeTenantUserServiceServer interface {
	mustEmbedUnimplementedTenantUserServiceServer()
}

func RegisterTenantUserServiceServer(s grpc.ServiceRegistrar, srv TenantUserServiceServer) {
	// If the following call pancis, it indicates UnimplementedTenantUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TenantUserService_ServiceDesc, srv)
}

func _TenantUserService_AddTenantUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTenantUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantUserServiceServer).AddTenantUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantUserService_AddTenantUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantUserServiceServer).AddTenantUser(ctx, req.(*AddTenantUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantUserService_GetTenantUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTenantUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantUserServiceServer).GetTenantUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantUserService_GetTenantUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantUserServiceServer).GetTenantUser(ctx, req.(*GetTenantUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantUserService_UpdateTenantUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTenantUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantUserServiceServer).UpdateTenantUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantUserService_UpdateTenantUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantUserServiceServer).UpdateTenantUser(ctx, req.(*UpdateTenantUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantUserService_DeleteTenantUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTenantUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantUserServiceServer).DeleteTenantUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantUserService_DeleteTenantUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantUserServiceServer).DeleteTenantUser(ctx, req.(*DeleteTenantUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantUserService_ListTenantUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTenantUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantUserServiceServer).ListTenantUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantUserService_ListTenantUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantUserServiceServer).ListTenantUsers(ctx, req.(*ListTenantUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TenantUserService_ServiceDesc is the grpc.ServiceDesc for TenantUserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TenantUserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.TenantUserService",
	HandlerType: (*TenantUserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddTenantUser",
			Handler:    _TenantUserService_AddTenantUser_Handler,
		},
		{
			MethodName: "GetTenantUser",
			Handler:    _TenantUserService_GetTenantUser_Handler,
		},
		{
			MethodName: "UpdateTenantUser",
			Handler:    _TenantUserService_UpdateTenantUser_Handler,
		},
		{
			MethodName: "DeleteTenantUser",
			Handler:    _TenantUserService_DeleteTenantUser_Handler,
		},
		{
			MethodName: "ListTenantUsers",
			Handler:    _TenantUserService_ListTenantUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/tenant_user.proto",
}
