// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api/tenant.proto

package api

import (
	common "github.com/SplitStackServer/splitstack-grpc-api/go/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tenant struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant ID (UUID).
	// Note: this value will be automatically generated on create.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Tenant name,
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Tenant description.
	Description *string `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Can the tenant create and "own" Gateways?
	CanHaveBasestations bool `protobuf:"varint,4,opt,name=can_have_basestations,json=canHaveBasestations,proto3" json:"can_have_basestations,omitempty"`
	// Max. basestation count for tenant.
	// When set to 0, the tenant can have unlimited basestations.
	MaxBasestationCount uint32 `protobuf:"varint,5,opt,name=max_basestation_count,json=maxBasestationCount,proto3" json:"max_basestation_count,omitempty"`
	// Max. device count for tenant.
	// When set to 0, the tenant can have unlimited devices.
	MaxDeviceCount uint32 `protobuf:"varint,6,opt,name=max_device_count,json=maxDeviceCount,proto3" json:"max_device_count,omitempty"`
	// Private basestations.
	// If enabled, then basestations will not be shared with other tenants.
	PrivateBasestations bool `protobuf:"varint,7,opt,name=private_basestations,json=privateBasestations,proto3" json:"private_basestations,omitempty"`
	// Private devices.
	// If enabled, then devices will not be shared with other tenants and will not be attached to their basestations.
	PrivateDevices bool `protobuf:"varint,8,opt,name=private_devices,json=privateDevices,proto3" json:"private_devices,omitempty"`
	// List of variable MACs enabled for the tenant.
	VariableMacEnabled *VariableMacList `protobuf:"bytes,9,opt,name=variable_mac_enabled,json=variableMacEnabled,proto3" json:"variable_mac_enabled,omitempty"`
	// Tags (user defined).
	// These tags can be used to add additional information to the tenant. These
	// tags are NOT exposed in the integration events.
	Tags          *common.Tags `protobuf:"bytes,10,opt,name=tags,proto3,oneof" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tenant) Reset() {
	*x = Tenant{}
	mi := &file_api_tenant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tenant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tenant) ProtoMessage() {}

func (x *Tenant) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tenant.ProtoReflect.Descriptor instead.
func (*Tenant) Descriptor() ([]byte, []int) {
	return file_api_tenant_proto_rawDescGZIP(), []int{0}
}

func (x *Tenant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tenant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tenant) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Tenant) GetCanHaveBasestations() bool {
	if x != nil {
		return x.CanHaveBasestations
	}
	return false
}

func (x *Tenant) GetMaxBasestationCount() uint32 {
	if x != nil {
		return x.MaxBasestationCount
	}
	return 0
}

func (x *Tenant) GetMaxDeviceCount() uint32 {
	if x != nil {
		return x.MaxDeviceCount
	}
	return 0
}

func (x *Tenant) GetPrivateBasestations() bool {
	if x != nil {
		return x.PrivateBasestations
	}
	return false
}

func (x *Tenant) GetPrivateDevices() bool {
	if x != nil {
		return x.PrivateDevices
	}
	return false
}

func (x *Tenant) GetVariableMacEnabled() *VariableMacList {
	if x != nil {
		return x.VariableMacEnabled
	}
	return nil
}

func (x *Tenant) GetTags() *common.Tags {
	if x != nil {
		return x.Tags
	}
	return nil
}

type TenantListItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant ID (UUID).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Created at timestamp.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last update timestamp.
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Tenant name.
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// Can the tenant create and "own" Gateways?
	CanHaveBasestations bool `protobuf:"varint,5,opt,name=can_have_basestations,json=canHaveBasestations,proto3" json:"can_have_basestations,omitempty"`
	// Private basestations.
	// If enabled, then basestations will not be shared with other tenants.
	PrivateBasestations bool `protobuf:"varint,7,opt,name=private_basestations,json=privateBasestations,proto3" json:"private_basestations,omitempty"`
	// Private devices.
	// If enabled, then devices will not be shared with other tenants and will not be attached to their basestations.
	PrivateDevices bool `protobuf:"varint,8,opt,name=private_devices,json=privateDevices,proto3" json:"private_devices,omitempty"`
	// Max basestation count.
	// 0 = unlimited.
	MaxBasestationCount uint32 `protobuf:"varint,9,opt,name=max_basestation_count,json=maxBasestationCount,proto3" json:"max_basestation_count,omitempty"`
	// Max device count.
	// 0 = unlimited.
	MaxDeviceCount uint32 `protobuf:"varint,10,opt,name=max_device_count,json=maxDeviceCount,proto3" json:"max_device_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TenantListItem) Reset() {
	*x = TenantListItem{}
	mi := &file_api_tenant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantListItem) ProtoMessage() {}

func (x *TenantListItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantListItem.ProtoReflect.Descriptor instead.
func (*TenantListItem) Descriptor() ([]byte, []int) {
	return file_api_tenant_proto_rawDescGZIP(), []int{1}
}

func (x *TenantListItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TenantListItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TenantListItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *TenantListItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TenantListItem) GetCanHaveBasestations() bool {
	if x != nil {
		return x.CanHaveBasestations
	}
	return false
}

func (x *TenantListItem) GetPrivateBasestations() bool {
	if x != nil {
		return x.PrivateBasestations
	}
	return false
}

func (x *TenantListItem) GetPrivateDevices() bool {
	if x != nil {
		return x.PrivateDevices
	}
	return false
}

func (x *TenantListItem) GetMaxBasestationCount() uint32 {
	if x != nil {
		return x.MaxBasestationCount
	}
	return 0
}

func (x *TenantListItem) GetMaxDeviceCount() uint32 {
	if x != nil {
		return x.MaxDeviceCount
	}
	return 0
}

type CreateTenantRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant name,
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Tenant description.
	Description *string `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Can the tenant create and "own" Gateways?
	CanHaveBasestations bool `protobuf:"varint,4,opt,name=can_have_basestations,json=canHaveBasestations,proto3" json:"can_have_basestations,omitempty"`
	// Max. basestation count for tenant.
	// When set to 0, the tenant can have unlimited basestations.
	MaxBasestationCount uint32 `protobuf:"varint,5,opt,name=max_basestation_count,json=maxBasestationCount,proto3" json:"max_basestation_count,omitempty"`
	// Max. device count for tenant.
	// When set to 0, the tenant can have unlimited devices.
	MaxDeviceCount uint32 `protobuf:"varint,6,opt,name=max_device_count,json=maxDeviceCount,proto3" json:"max_device_count,omitempty"`
	// Private basestations.
	// If enabled, then basestations will not be shared with other tenants.
	PrivateBasestations bool `protobuf:"varint,7,opt,name=private_basestations,json=privateBasestations,proto3" json:"private_basestations,omitempty"`
	// Private devices.
	// If enabled, then devices will not be shared with other tenants and will not be attached to their basestations.
	PrivateDevices bool `protobuf:"varint,8,opt,name=private_devices,json=privateDevices,proto3" json:"private_devices,omitempty"`
	// List of variable MACs enabled for the tenant.
	VariableMacEnabled *VariableMacList `protobuf:"bytes,9,opt,name=variable_mac_enabled,json=variableMacEnabled,proto3" json:"variable_mac_enabled,omitempty"`
	// Tags (user defined).
	// These tags can be used to add additional information to the tenant. These
	// tags are NOT exposed in the integration events.
	Tags          *common.Tags `protobuf:"bytes,10,opt,name=tags,proto3,oneof" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTenantRequest) Reset() {
	*x = CreateTenantRequest{}
	mi := &file_api_tenant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTenantRequest) ProtoMessage() {}

func (x *CreateTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTenantRequest.ProtoReflect.Descriptor instead.
func (*CreateTenantRequest) Descriptor() ([]byte, []int) {
	return file_api_tenant_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTenantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTenantRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateTenantRequest) GetCanHaveBasestations() bool {
	if x != nil {
		return x.CanHaveBasestations
	}
	return false
}

func (x *CreateTenantRequest) GetMaxBasestationCount() uint32 {
	if x != nil {
		return x.MaxBasestationCount
	}
	return 0
}

func (x *CreateTenantRequest) GetMaxDeviceCount() uint32 {
	if x != nil {
		return x.MaxDeviceCount
	}
	return 0
}

func (x *CreateTenantRequest) GetPrivateBasestations() bool {
	if x != nil {
		return x.PrivateBasestations
	}
	return false
}

func (x *CreateTenantRequest) GetPrivateDevices() bool {
	if x != nil {
		return x.PrivateDevices
	}
	return false
}

func (x *CreateTenantRequest) GetVariableMacEnabled() *VariableMacList {
	if x != nil {
		return x.VariableMacEnabled
	}
	return nil
}

func (x *CreateTenantRequest) GetTags() *common.Tags {
	if x != nil {
		return x.Tags
	}
	return nil
}

type CreateTenantResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant object.
	Tenant *Tenant `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	// Created at timestamp.
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTenantResponse) Reset() {
	*x = CreateTenantResponse{}
	mi := &file_api_tenant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTenantResponse) ProtoMessage() {}

func (x *CreateTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTenantResponse.ProtoReflect.Descriptor instead.
func (*CreateTenantResponse) Descriptor() ([]byte, []int) {
	return file_api_tenant_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTenantResponse) GetTenant() *Tenant {
	if x != nil {
		return x.Tenant
	}
	return nil
}

func (x *CreateTenantResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetTenantRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant ID.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantRequest) Reset() {
	*x = GetTenantRequest{}
	mi := &file_api_tenant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantRequest) ProtoMessage() {}

func (x *GetTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantRequest.ProtoReflect.Descriptor instead.
func (*GetTenantRequest) Descriptor() ([]byte, []int) {
	return file_api_tenant_proto_rawDescGZIP(), []int{4}
}

func (x *GetTenantRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTenantResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant object.
	Tenant *Tenant `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	// Created at timestamp.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last update timestamp.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantResponse) Reset() {
	*x = GetTenantResponse{}
	mi := &file_api_tenant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantResponse) ProtoMessage() {}

func (x *GetTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantResponse.ProtoReflect.Descriptor instead.
func (*GetTenantResponse) Descriptor() ([]byte, []int) {
	return file_api_tenant_proto_rawDescGZIP(), []int{5}
}

func (x *GetTenantResponse) GetTenant() *Tenant {
	if x != nil {
		return x.Tenant
	}
	return nil
}

func (x *GetTenantResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetTenantResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type UpdateTenantRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant ID (UUID).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Tenant name,
	Name *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// Tenant description.
	Description *string `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Can the tenant create and "own" Gateways?
	CanHaveBasestations *bool `protobuf:"varint,4,opt,name=can_have_basestations,json=canHaveBasestations,proto3,oneof" json:"can_have_basestations,omitempty"`
	// Max. basestation count for tenant.
	// When set to 0, the tenant can have unlimited basestations.
	MaxBasestationCount *uint32 `protobuf:"varint,5,opt,name=max_basestation_count,json=maxBasestationCount,proto3,oneof" json:"max_basestation_count,omitempty"`
	// Max. device count for tenant.
	// When set to 0, the tenant can have unlimited devices.
	MaxDeviceCount *uint32 `protobuf:"varint,6,opt,name=max_device_count,json=maxDeviceCount,proto3,oneof" json:"max_device_count,omitempty"`
	// Private basestations.
	// If enabled, then basestations will not be shared with other tenants.
	PrivateBasestations *bool `protobuf:"varint,7,opt,name=private_basestations,json=privateBasestations,proto3,oneof" json:"private_basestations,omitempty"`
	// Private devices.
	// If enabled, then devices will not be shared with other tenants and will not be attached to their basestations.
	PrivateDevices *bool `protobuf:"varint,8,opt,name=private_devices,json=privateDevices,proto3,oneof" json:"private_devices,omitempty"`
	// Tags (user defined).
	// These tags can be used to add additional information to the tenant. These
	// tags are NOT exposed in the integration events.
	Tags          *common.Tags `protobuf:"bytes,9,opt,name=tags,proto3,oneof" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTenantRequest) Reset() {
	*x = UpdateTenantRequest{}
	mi := &file_api_tenant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTenantRequest) ProtoMessage() {}

func (x *UpdateTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTenantRequest.ProtoReflect.Descriptor instead.
func (*UpdateTenantRequest) Descriptor() ([]byte, []int) {
	return file_api_tenant_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateTenantRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTenantRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateTenantRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateTenantRequest) GetCanHaveBasestations() bool {
	if x != nil && x.CanHaveBasestations != nil {
		return *x.CanHaveBasestations
	}
	return false
}

func (x *UpdateTenantRequest) GetMaxBasestationCount() uint32 {
	if x != nil && x.MaxBasestationCount != nil {
		return *x.MaxBasestationCount
	}
	return 0
}

func (x *UpdateTenantRequest) GetMaxDeviceCount() uint32 {
	if x != nil && x.MaxDeviceCount != nil {
		return *x.MaxDeviceCount
	}
	return 0
}

func (x *UpdateTenantRequest) GetPrivateBasestations() bool {
	if x != nil && x.PrivateBasestations != nil {
		return *x.PrivateBasestations
	}
	return false
}

func (x *UpdateTenantRequest) GetPrivateDevices() bool {
	if x != nil && x.PrivateDevices != nil {
		return *x.PrivateDevices
	}
	return false
}

func (x *UpdateTenantRequest) GetTags() *common.Tags {
	if x != nil {
		return x.Tags
	}
	return nil
}

type UpdateTenantResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant object.
	Tenant *Tenant `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	// Created at timestamp.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last update timestamp.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTenantResponse) Reset() {
	*x = UpdateTenantResponse{}
	mi := &file_api_tenant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTenantResponse) ProtoMessage() {}

func (x *UpdateTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTenantResponse.ProtoReflect.Descriptor instead.
func (*UpdateTenantResponse) Descriptor() ([]byte, []int) {
	return file_api_tenant_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateTenantResponse) GetTenant() *Tenant {
	if x != nil {
		return x.Tenant
	}
	return nil
}

func (x *UpdateTenantResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UpdateTenantResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type EnableVariableMacRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant ID (UUID).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Variable MAC to enable for the tenant. See ETSI TS 103 357-2 Table 4-57
	Vm            uint32 `protobuf:"varint,2,opt,name=vm,proto3" json:"vm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableVariableMacRequest) Reset() {
	*x = EnableVariableMacRequest{}
	mi := &file_api_tenant_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableVariableMacRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableVariableMacRequest) ProtoMessage() {}

func (x *EnableVariableMacRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenant_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableVariableMacRequest.ProtoReflect.Descriptor instead.
func (*EnableVariableMacRequest) Descriptor() ([]byte, []int) {
	return file_api_tenant_proto_rawDescGZIP(), []int{8}
}

func (x *EnableVariableMacRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EnableVariableMacRequest) GetVm() uint32 {
	if x != nil {
		return x.Vm
	}
	return 0
}

type DisableVariableMacRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant ID (UUID).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Variable MAC to disable for the tenant. See ETSI TS 103 357-2 Table 4-57
	Vm            uint32 `protobuf:"varint,2,opt,name=vm,proto3" json:"vm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableVariableMacRequest) Reset() {
	*x = DisableVariableMacRequest{}
	mi := &file_api_tenant_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableVariableMacRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableVariableMacRequest) ProtoMessage() {}

func (x *DisableVariableMacRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenant_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableVariableMacRequest.ProtoReflect.Descriptor instead.
func (*DisableVariableMacRequest) Descriptor() ([]byte, []int) {
	return file_api_tenant_proto_rawDescGZIP(), []int{9}
}

func (x *DisableVariableMacRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DisableVariableMacRequest) GetVm() uint32 {
	if x != nil {
		return x.Vm
	}
	return 0
}

type VariableMacResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant ID (UUID).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// List of variable MACs enabled for the tenant.
	Vm            *VariableMacList `protobuf:"bytes,2,opt,name=vm,proto3" json:"vm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VariableMacResponse) Reset() {
	*x = VariableMacResponse{}
	mi := &file_api_tenant_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VariableMacResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariableMacResponse) ProtoMessage() {}

func (x *VariableMacResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenant_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariableMacResponse.ProtoReflect.Descriptor instead.
func (*VariableMacResponse) Descriptor() ([]byte, []int) {
	return file_api_tenant_proto_rawDescGZIP(), []int{10}
}

func (x *VariableMacResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VariableMacResponse) GetVm() *VariableMacList {
	if x != nil {
		return x.Vm
	}
	return nil
}

type DeleteTenantRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant ID.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTenantRequest) Reset() {
	*x = DeleteTenantRequest{}
	mi := &file_api_tenant_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTenantRequest) ProtoMessage() {}

func (x *DeleteTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenant_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTenantRequest.ProtoReflect.Descriptor instead.
func (*DeleteTenantRequest) Descriptor() ([]byte, []int) {
	return file_api_tenant_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteTenantRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListTenantsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pagination. Defaults to 100 objects at page index 0.
	Paginator *Paginator `protobuf:"bytes,1,opt,name=paginator,proto3" json:"paginator,omitempty"`
	// If set, the given string will be used to search on name.
	SearchName *string `protobuf:"bytes,3,opt,name=search_name,json=searchName,proto3,oneof" json:"search_name,omitempty"`
	// If set, filters the result set to the tenants of the user.
	// This filter can only be used by admin users or global API keys.
	UserId        *string `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTenantsRequest) Reset() {
	*x = ListTenantsRequest{}
	mi := &file_api_tenant_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantsRequest) ProtoMessage() {}

func (x *ListTenantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenant_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantsRequest.ProtoReflect.Descriptor instead.
func (*ListTenantsRequest) Descriptor() ([]byte, []int) {
	return file_api_tenant_proto_rawDescGZIP(), []int{12}
}

func (x *ListTenantsRequest) GetPaginator() *Paginator {
	if x != nil {
		return x.Paginator
	}
	return nil
}

func (x *ListTenantsRequest) GetSearchName() string {
	if x != nil && x.SearchName != nil {
		return *x.SearchName
	}
	return ""
}

func (x *ListTenantsRequest) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

type ListTenantsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pagination.
	Pagination *Pagination `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// Result-set.
	Result        []*TenantListItem `protobuf:"bytes,2,rep,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTenantsResponse) Reset() {
	*x = ListTenantsResponse{}
	mi := &file_api_tenant_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantsResponse) ProtoMessage() {}

func (x *ListTenantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenant_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantsResponse.ProtoReflect.Descriptor instead.
func (*ListTenantsResponse) Descriptor() ([]byte, []int) {
	return file_api_tenant_proto_rawDescGZIP(), []int{13}
}

func (x *ListTenantsResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListTenantsResponse) GetResult() []*TenantListItem {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_api_tenant_proto protoreflect.FileDescriptor

const file_api_tenant_proto_rawDesc = "" +
	"\n" +
	"\x10api/tenant.proto\x12\x03api\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x10api/common.proto\x1a\x13common/common.proto\"\xc9\x03\n" +
	"\x06Tenant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x122\n" +
	"\x15can_have_basestations\x18\x04 \x01(\bR\x13canHaveBasestations\x122\n" +
	"\x15max_basestation_count\x18\x05 \x01(\rR\x13maxBasestationCount\x12(\n" +
	"\x10max_device_count\x18\x06 \x01(\rR\x0emaxDeviceCount\x121\n" +
	"\x14private_basestations\x18\a \x01(\bR\x13privateBasestations\x12'\n" +
	"\x0fprivate_devices\x18\b \x01(\bR\x0eprivateDevices\x12F\n" +
	"\x14variable_mac_enabled\x18\t \x01(\v2\x14.api.VariableMacListR\x12variableMacEnabled\x12%\n" +
	"\x04tags\x18\n" +
	" \x01(\v2\f.common.TagsH\x01R\x04tags\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\a\n" +
	"\x05_tags\"\x98\x03\n" +
	"\x0eTenantListItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x122\n" +
	"\x15can_have_basestations\x18\x05 \x01(\bR\x13canHaveBasestations\x121\n" +
	"\x14private_basestations\x18\a \x01(\bR\x13privateBasestations\x12'\n" +
	"\x0fprivate_devices\x18\b \x01(\bR\x0eprivateDevices\x122\n" +
	"\x15max_basestation_count\x18\t \x01(\rR\x13maxBasestationCount\x12(\n" +
	"\x10max_device_count\x18\n" +
	" \x01(\rR\x0emaxDeviceCount\"\xc6\x03\n" +
	"\x13CreateTenantRequest\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x122\n" +
	"\x15can_have_basestations\x18\x04 \x01(\bR\x13canHaveBasestations\x122\n" +
	"\x15max_basestation_count\x18\x05 \x01(\rR\x13maxBasestationCount\x12(\n" +
	"\x10max_device_count\x18\x06 \x01(\rR\x0emaxDeviceCount\x121\n" +
	"\x14private_basestations\x18\a \x01(\bR\x13privateBasestations\x12'\n" +
	"\x0fprivate_devices\x18\b \x01(\bR\x0eprivateDevices\x12F\n" +
	"\x14variable_mac_enabled\x18\t \x01(\v2\x14.api.VariableMacListR\x12variableMacEnabled\x12%\n" +
	"\x04tags\x18\n" +
	" \x01(\v2\f.common.TagsH\x01R\x04tags\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\a\n" +
	"\x05_tags\"v\n" +
	"\x14CreateTenantResponse\x12#\n" +
	"\x06tenant\x18\x01 \x01(\v2\v.api.TenantR\x06tenant\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\"\n" +
	"\x10GetTenantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xae\x01\n" +
	"\x11GetTenantResponse\x12#\n" +
	"\x06tenant\x18\x01 \x01(\v2\v.api.TenantR\x06tenant\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xab\x04\n" +
	"\x13UpdateTenantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x127\n" +
	"\x15can_have_basestations\x18\x04 \x01(\bH\x02R\x13canHaveBasestations\x88\x01\x01\x127\n" +
	"\x15max_basestation_count\x18\x05 \x01(\rH\x03R\x13maxBasestationCount\x88\x01\x01\x12-\n" +
	"\x10max_device_count\x18\x06 \x01(\rH\x04R\x0emaxDeviceCount\x88\x01\x01\x126\n" +
	"\x14private_basestations\x18\a \x01(\bH\x05R\x13privateBasestations\x88\x01\x01\x12,\n" +
	"\x0fprivate_devices\x18\b \x01(\bH\x06R\x0eprivateDevices\x88\x01\x01\x12%\n" +
	"\x04tags\x18\t \x01(\v2\f.common.TagsH\aR\x04tags\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\x18\n" +
	"\x16_can_have_basestationsB\x18\n" +
	"\x16_max_basestation_countB\x13\n" +
	"\x11_max_device_countB\x17\n" +
	"\x15_private_basestationsB\x12\n" +
	"\x10_private_devicesB\a\n" +
	"\x05_tags\"\xb1\x01\n" +
	"\x14UpdateTenantResponse\x12#\n" +
	"\x06tenant\x18\x01 \x01(\v2\v.api.TenantR\x06tenant\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\":\n" +
	"\x18EnableVariableMacRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x0e\n" +
	"\x02vm\x18\x02 \x01(\rR\x02vm\";\n" +
	"\x19DisableVariableMacRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x0e\n" +
	"\x02vm\x18\x02 \x01(\rR\x02vm\"K\n" +
	"\x13VariableMacResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12$\n" +
	"\x02vm\x18\x02 \x01(\v2\x14.api.VariableMacListR\x02vm\"%\n" +
	"\x13DeleteTenantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa2\x01\n" +
	"\x12ListTenantsRequest\x12,\n" +
	"\tpaginator\x18\x01 \x01(\v2\x0e.api.PaginatorR\tpaginator\x12$\n" +
	"\vsearch_name\x18\x03 \x01(\tH\x00R\n" +
	"searchName\x88\x01\x01\x12\x1c\n" +
	"\auser_id\x18\x04 \x01(\tH\x01R\x06userId\x88\x01\x01B\x0e\n" +
	"\f_search_nameB\n" +
	"\n" +
	"\b_user_id\"s\n" +
	"\x13ListTenantsResponse\x12/\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x0f.api.PaginationR\n" +
	"pagination\x12+\n" +
	"\x06result\x18\x02 \x03(\v2\x13.api.TenantListItemR\x06result2\xe0\x05\n" +
	"\rTenantService\x12\\\n" +
	"\fCreateTenant\x12\x18.api.CreateTenantRequest\x1a\x19.api.CreateTenantResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/api/tenants\x12U\n" +
	"\tGetTenant\x12\x15.api.GetTenantRequest\x1a\x16.api.GetTenantResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/tenants/{id}\x12a\n" +
	"\fUpdateTenant\x12\x18.api.UpdateTenantRequest\x1a\x19.api.UpdateTenantResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\x1a\x11/api/tenants/{id}\x12~\n" +
	"\x11EnableVariableMac\x12\x1d.api.EnableVariableMacRequest\x1a\x18.api.VariableMacResponse\"0\x82\xd3\xe4\x93\x02*:\x01*\"%/api/tenants/{id}/variable-mac/enable\x12\x81\x01\n" +
	"\x12DisableVariableMac\x12\x1e.api.DisableVariableMacRequest\x1a\x18.api.VariableMacResponse\"1\x82\xd3\xe4\x93\x02+:\x01*\"&/api/tenants/{id}/variable-mac/disable\x12[\n" +
	"\fDeleteTenant\x12\x18.api.DeleteTenantRequest\x1a\x16.google.protobuf.Empty\"\x19\x82\xd3\xe4\x93\x02\x13*\x11/api/tenants/{id}\x12V\n" +
	"\vListTenants\x12\x17.api.ListTenantsRequest\x1a\x18.api.ListTenantsResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/api/tenantsB\xab\x01\n" +
	"\x11io.splitstack.apiB\vTenantProtoP\x01Z6github.com/SplitStackServer/splitstack-grpc-api/go/api\xaa\x02\x14SplitStackServer.Api\xca\x02\x14SplitStackServer\\Api\xe2\x02 GPBMetadata\\SplitStackServer\\Apib\x06proto3"

var (
	file_api_tenant_proto_rawDescOnce sync.Once
	file_api_tenant_proto_rawDescData []byte
)

func file_api_tenant_proto_rawDescGZIP() []byte {
	file_api_tenant_proto_rawDescOnce.Do(func() {
		file_api_tenant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_tenant_proto_rawDesc), len(file_api_tenant_proto_rawDesc)))
	})
	return file_api_tenant_proto_rawDescData
}

var file_api_tenant_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_tenant_proto_goTypes = []any{
	(*Tenant)(nil),                    // 0: api.Tenant
	(*TenantListItem)(nil),            // 1: api.TenantListItem
	(*CreateTenantRequest)(nil),       // 2: api.CreateTenantRequest
	(*CreateTenantResponse)(nil),      // 3: api.CreateTenantResponse
	(*GetTenantRequest)(nil),          // 4: api.GetTenantRequest
	(*GetTenantResponse)(nil),         // 5: api.GetTenantResponse
	(*UpdateTenantRequest)(nil),       // 6: api.UpdateTenantRequest
	(*UpdateTenantResponse)(nil),      // 7: api.UpdateTenantResponse
	(*EnableVariableMacRequest)(nil),  // 8: api.EnableVariableMacRequest
	(*DisableVariableMacRequest)(nil), // 9: api.DisableVariableMacRequest
	(*VariableMacResponse)(nil),       // 10: api.VariableMacResponse
	(*DeleteTenantRequest)(nil),       // 11: api.DeleteTenantRequest
	(*ListTenantsRequest)(nil),        // 12: api.ListTenantsRequest
	(*ListTenantsResponse)(nil),       // 13: api.ListTenantsResponse
	(*VariableMacList)(nil),           // 14: api.VariableMacList
	(*common.Tags)(nil),               // 15: common.Tags
	(*timestamppb.Timestamp)(nil),     // 16: google.protobuf.Timestamp
	(*Paginator)(nil),                 // 17: api.Paginator
	(*Pagination)(nil),                // 18: api.Pagination
	(*emptypb.Empty)(nil),             // 19: google.protobuf.Empty
}
var file_api_tenant_proto_depIdxs = []int32{
	14, // 0: api.Tenant.variable_mac_enabled:type_name -> api.VariableMacList
	15, // 1: api.Tenant.tags:type_name -> common.Tags
	16, // 2: api.TenantListItem.created_at:type_name -> google.protobuf.Timestamp
	16, // 3: api.TenantListItem.updated_at:type_name -> google.protobuf.Timestamp
	14, // 4: api.CreateTenantRequest.variable_mac_enabled:type_name -> api.VariableMacList
	15, // 5: api.CreateTenantRequest.tags:type_name -> common.Tags
	0,  // 6: api.CreateTenantResponse.tenant:type_name -> api.Tenant
	16, // 7: api.CreateTenantResponse.created_at:type_name -> google.protobuf.Timestamp
	0,  // 8: api.GetTenantResponse.tenant:type_name -> api.Tenant
	16, // 9: api.GetTenantResponse.created_at:type_name -> google.protobuf.Timestamp
	16, // 10: api.GetTenantResponse.updated_at:type_name -> google.protobuf.Timestamp
	15, // 11: api.UpdateTenantRequest.tags:type_name -> common.Tags
	0,  // 12: api.UpdateTenantResponse.tenant:type_name -> api.Tenant
	16, // 13: api.UpdateTenantResponse.created_at:type_name -> google.protobuf.Timestamp
	16, // 14: api.UpdateTenantResponse.updated_at:type_name -> google.protobuf.Timestamp
	14, // 15: api.VariableMacResponse.vm:type_name -> api.VariableMacList
	17, // 16: api.ListTenantsRequest.paginator:type_name -> api.Paginator
	18, // 17: api.ListTenantsResponse.pagination:type_name -> api.Pagination
	1,  // 18: api.ListTenantsResponse.result:type_name -> api.TenantListItem
	2,  // 19: api.TenantService.CreateTenant:input_type -> api.CreateTenantRequest
	4,  // 20: api.TenantService.GetTenant:input_type -> api.GetTenantRequest
	6,  // 21: api.TenantService.UpdateTenant:input_type -> api.UpdateTenantRequest
	8,  // 22: api.TenantService.EnableVariableMac:input_type -> api.EnableVariableMacRequest
	9,  // 23: api.TenantService.DisableVariableMac:input_type -> api.DisableVariableMacRequest
	11, // 24: api.TenantService.DeleteTenant:input_type -> api.DeleteTenantRequest
	12, // 25: api.TenantService.ListTenants:input_type -> api.ListTenantsRequest
	3,  // 26: api.TenantService.CreateTenant:output_type -> api.CreateTenantResponse
	5,  // 27: api.TenantService.GetTenant:output_type -> api.GetTenantResponse
	7,  // 28: api.TenantService.UpdateTenant:output_type -> api.UpdateTenantResponse
	10, // 29: api.TenantService.EnableVariableMac:output_type -> api.VariableMacResponse
	10, // 30: api.TenantService.DisableVariableMac:output_type -> api.VariableMacResponse
	19, // 31: api.TenantService.DeleteTenant:output_type -> google.protobuf.Empty
	13, // 32: api.TenantService.ListTenants:output_type -> api.ListTenantsResponse
	26, // [26:33] is the sub-list for method output_type
	19, // [19:26] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_api_tenant_proto_init() }
func file_api_tenant_proto_init() {
	if File_api_tenant_proto != nil {
		return
	}
	file_api_common_proto_init()
	file_api_tenant_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_tenant_proto_msgTypes[2].OneofWrappers = []any{}
	file_api_tenant_proto_msgTypes[6].OneofWrappers = []any{}
	file_api_tenant_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_tenant_proto_rawDesc), len(file_api_tenant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_tenant_proto_goTypes,
		DependencyIndexes: file_api_tenant_proto_depIdxs,
		MessageInfos:      file_api_tenant_proto_msgTypes,
	}.Build()
	File_api_tenant_proto = out.File
	file_api_tenant_proto_goTypes = nil
	file_api_tenant_proto_depIdxs = nil
}
