// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api/tenant_user.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TenantUser struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant ID (UUID).
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// User ID (UUID).
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// User is admin within the context of the tenant.
	// There is no need to set the is_endnode_admin and is_basestation_admin flags.
	IsAdmin bool `protobuf:"varint,3,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	// User is able to modify device related resources (applications,
	// device-profiles, devices, multicast-groups).
	IsEndnodeAdmin bool `protobuf:"varint,4,opt,name=is_endnode_admin,json=isEndnodeAdmin,proto3" json:"is_endnode_admin,omitempty"`
	// User is able to modify gateways.
	IsBasestationAdmin bool `protobuf:"varint,5,opt,name=is_basestation_admin,json=isBasestationAdmin,proto3" json:"is_basestation_admin,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TenantUser) Reset() {
	*x = TenantUser{}
	mi := &file_api_tenant_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantUser) ProtoMessage() {}

func (x *TenantUser) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenant_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantUser.ProtoReflect.Descriptor instead.
func (*TenantUser) Descriptor() ([]byte, []int) {
	return file_api_tenant_user_proto_rawDescGZIP(), []int{0}
}

func (x *TenantUser) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TenantUser) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TenantUser) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *TenantUser) GetIsEndnodeAdmin() bool {
	if x != nil {
		return x.IsEndnodeAdmin
	}
	return false
}

func (x *TenantUser) GetIsBasestationAdmin() bool {
	if x != nil {
		return x.IsBasestationAdmin
	}
	return false
}

type TenantUserListItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant ID (UUID).
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// User ID (UUID).
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Created at timestamp.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last update timestamp.
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// User Email
	Email string `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	// User is admin within the context of the tenant.
	// There is no need to set the is_endnode_admin and is_basestation_admin flags.
	IsAdmin bool `protobuf:"varint,6,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	// User is able to modify device related resources (applications,
	// device-profiles, devices, multicast-groups).
	IsEndnodeAdmin bool `protobuf:"varint,7,opt,name=is_endnode_admin,json=isEndnodeAdmin,proto3" json:"is_endnode_admin,omitempty"`
	// User is able to modify gateways.
	IsBasestationAdmin bool `protobuf:"varint,8,opt,name=is_basestation_admin,json=isBasestationAdmin,proto3" json:"is_basestation_admin,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TenantUserListItem) Reset() {
	*x = TenantUserListItem{}
	mi := &file_api_tenant_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantUserListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantUserListItem) ProtoMessage() {}

func (x *TenantUserListItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenant_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantUserListItem.ProtoReflect.Descriptor instead.
func (*TenantUserListItem) Descriptor() ([]byte, []int) {
	return file_api_tenant_user_proto_rawDescGZIP(), []int{1}
}

func (x *TenantUserListItem) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TenantUserListItem) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TenantUserListItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TenantUserListItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *TenantUserListItem) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *TenantUserListItem) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *TenantUserListItem) GetIsEndnodeAdmin() bool {
	if x != nil {
		return x.IsEndnodeAdmin
	}
	return false
}

func (x *TenantUserListItem) GetIsBasestationAdmin() bool {
	if x != nil {
		return x.IsBasestationAdmin
	}
	return false
}

type AddTenantUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant ID (UUID).
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// User ID (UUID).
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// User is admin within the context of the tenant.
	// There is no need to set the is_endnode_admin and is_basestation_admin flags.
	IsAdmin bool `protobuf:"varint,3,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	// User is able to modify device related resources (applications,
	// device-profiles, devices, multicast-groups).
	IsEndnodeAdmin bool `protobuf:"varint,4,opt,name=is_endnode_admin,json=isEndnodeAdmin,proto3" json:"is_endnode_admin,omitempty"`
	// User is able to modify gateways.
	IsBasestationAdmin bool `protobuf:"varint,5,opt,name=is_basestation_admin,json=isBasestationAdmin,proto3" json:"is_basestation_admin,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AddTenantUserRequest) Reset() {
	*x = AddTenantUserRequest{}
	mi := &file_api_tenant_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTenantUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTenantUserRequest) ProtoMessage() {}

func (x *AddTenantUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenant_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTenantUserRequest.ProtoReflect.Descriptor instead.
func (*AddTenantUserRequest) Descriptor() ([]byte, []int) {
	return file_api_tenant_user_proto_rawDescGZIP(), []int{2}
}

func (x *AddTenantUserRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AddTenantUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddTenantUserRequest) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *AddTenantUserRequest) GetIsEndnodeAdmin() bool {
	if x != nil {
		return x.IsEndnodeAdmin
	}
	return false
}

func (x *AddTenantUserRequest) GetIsBasestationAdmin() bool {
	if x != nil {
		return x.IsBasestationAdmin
	}
	return false
}

type AddTenantUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant user object.
	TenantUser *TenantUser `protobuf:"bytes,1,opt,name=tenant_user,json=tenantUser,proto3" json:"tenant_user,omitempty"`
	// Created at timestamp.
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTenantUserResponse) Reset() {
	*x = AddTenantUserResponse{}
	mi := &file_api_tenant_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTenantUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTenantUserResponse) ProtoMessage() {}

func (x *AddTenantUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenant_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTenantUserResponse.ProtoReflect.Descriptor instead.
func (*AddTenantUserResponse) Descriptor() ([]byte, []int) {
	return file_api_tenant_user_proto_rawDescGZIP(), []int{3}
}

func (x *AddTenantUserResponse) GetTenantUser() *TenantUser {
	if x != nil {
		return x.TenantUser
	}
	return nil
}

func (x *AddTenantUserResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetTenantUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant ID (UUID).
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// User ID (UUID).
	UserId        string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantUserRequest) Reset() {
	*x = GetTenantUserRequest{}
	mi := &file_api_tenant_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantUserRequest) ProtoMessage() {}

func (x *GetTenantUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenant_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantUserRequest.ProtoReflect.Descriptor instead.
func (*GetTenantUserRequest) Descriptor() ([]byte, []int) {
	return file_api_tenant_user_proto_rawDescGZIP(), []int{4}
}

func (x *GetTenantUserRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetTenantUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetTenantUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant user object.
	TenantUser *TenantUser `protobuf:"bytes,1,opt,name=tenant_user,json=tenantUser,proto3" json:"tenant_user,omitempty"`
	// Created at timestamp.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last update timestamp.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantUserResponse) Reset() {
	*x = GetTenantUserResponse{}
	mi := &file_api_tenant_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantUserResponse) ProtoMessage() {}

func (x *GetTenantUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenant_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantUserResponse.ProtoReflect.Descriptor instead.
func (*GetTenantUserResponse) Descriptor() ([]byte, []int) {
	return file_api_tenant_user_proto_rawDescGZIP(), []int{5}
}

func (x *GetTenantUserResponse) GetTenantUser() *TenantUser {
	if x != nil {
		return x.TenantUser
	}
	return nil
}

func (x *GetTenantUserResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetTenantUserResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type UpdateTenantUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant ID (UUID).
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// User ID (UUID).
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// User is admin within the context of the tenant.
	// There is no need to set the is_endnode_admin and is_basestation_admin flags.
	IsAdmin *bool `protobuf:"varint,3,opt,name=is_admin,json=isAdmin,proto3,oneof" json:"is_admin,omitempty"`
	// User is able to modify device related resources (applications,
	// device-profiles, devices, multicast-groups).
	IsEndnodeAdmin *bool `protobuf:"varint,4,opt,name=is_endnode_admin,json=isEndnodeAdmin,proto3,oneof" json:"is_endnode_admin,omitempty"`
	// User is able to modify gateways.
	IsBasestationAdmin *bool `protobuf:"varint,5,opt,name=is_basestation_admin,json=isBasestationAdmin,proto3,oneof" json:"is_basestation_admin,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateTenantUserRequest) Reset() {
	*x = UpdateTenantUserRequest{}
	mi := &file_api_tenant_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTenantUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTenantUserRequest) ProtoMessage() {}

func (x *UpdateTenantUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenant_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTenantUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateTenantUserRequest) Descriptor() ([]byte, []int) {
	return file_api_tenant_user_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateTenantUserRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UpdateTenantUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateTenantUserRequest) GetIsAdmin() bool {
	if x != nil && x.IsAdmin != nil {
		return *x.IsAdmin
	}
	return false
}

func (x *UpdateTenantUserRequest) GetIsEndnodeAdmin() bool {
	if x != nil && x.IsEndnodeAdmin != nil {
		return *x.IsEndnodeAdmin
	}
	return false
}

func (x *UpdateTenantUserRequest) GetIsBasestationAdmin() bool {
	if x != nil && x.IsBasestationAdmin != nil {
		return *x.IsBasestationAdmin
	}
	return false
}

type UpdateTenantUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant user object.
	TenantUser *TenantUser `protobuf:"bytes,1,opt,name=tenant_user,json=tenantUser,proto3" json:"tenant_user,omitempty"`
	// Created at timestamp.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last update timestamp.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTenantUserResponse) Reset() {
	*x = UpdateTenantUserResponse{}
	mi := &file_api_tenant_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTenantUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTenantUserResponse) ProtoMessage() {}

func (x *UpdateTenantUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenant_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTenantUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateTenantUserResponse) Descriptor() ([]byte, []int) {
	return file_api_tenant_user_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateTenantUserResponse) GetTenantUser() *TenantUser {
	if x != nil {
		return x.TenantUser
	}
	return nil
}

func (x *UpdateTenantUserResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UpdateTenantUserResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type DeleteTenantUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant ID (UUID).
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// User ID (UUID).
	UserId        string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTenantUserRequest) Reset() {
	*x = DeleteTenantUserRequest{}
	mi := &file_api_tenant_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTenantUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTenantUserRequest) ProtoMessage() {}

func (x *DeleteTenantUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenant_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTenantUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteTenantUserRequest) Descriptor() ([]byte, []int) {
	return file_api_tenant_user_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteTenantUserRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DeleteTenantUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListTenantUsersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant ID (UUID).
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Pagination. Defaults to 100 objects at page index 0.
	Paginator     *Paginator `protobuf:"bytes,2,opt,name=paginator,proto3" json:"paginator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTenantUsersRequest) Reset() {
	*x = ListTenantUsersRequest{}
	mi := &file_api_tenant_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantUsersRequest) ProtoMessage() {}

func (x *ListTenantUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenant_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantUsersRequest.ProtoReflect.Descriptor instead.
func (*ListTenantUsersRequest) Descriptor() ([]byte, []int) {
	return file_api_tenant_user_proto_rawDescGZIP(), []int{9}
}

func (x *ListTenantUsersRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListTenantUsersRequest) GetPaginator() *Paginator {
	if x != nil {
		return x.Paginator
	}
	return nil
}

type ListTenantUsersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pagination.
	Pagination *Pagination `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// Result-set.
	Result        []*TenantUserListItem `protobuf:"bytes,2,rep,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTenantUsersResponse) Reset() {
	*x = ListTenantUsersResponse{}
	mi := &file_api_tenant_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantUsersResponse) ProtoMessage() {}

func (x *ListTenantUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenant_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantUsersResponse.ProtoReflect.Descriptor instead.
func (*ListTenantUsersResponse) Descriptor() ([]byte, []int) {
	return file_api_tenant_user_proto_rawDescGZIP(), []int{10}
}

func (x *ListTenantUsersResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListTenantUsersResponse) GetResult() []*TenantUserListItem {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_api_tenant_user_proto protoreflect.FileDescriptor

const file_api_tenant_user_proto_rawDesc = "" +
	"\n" +
	"\x15api/tenant_user.proto\x12\x03api\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x10api/common.proto\"\xb9\x01\n" +
	"\n" +
	"TenantUser\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\bis_admin\x18\x03 \x01(\bR\aisAdmin\x12(\n" +
	"\x10is_endnode_admin\x18\x04 \x01(\bR\x0eisEndnodeAdmin\x120\n" +
	"\x14is_basestation_admin\x18\x05 \x01(\bR\x12isBasestationAdmin\"\xcd\x02\n" +
	"\x12TenantUserListItem\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x19\n" +
	"\bis_admin\x18\x06 \x01(\bR\aisAdmin\x12(\n" +
	"\x10is_endnode_admin\x18\a \x01(\bR\x0eisEndnodeAdmin\x120\n" +
	"\x14is_basestation_admin\x18\b \x01(\bR\x12isBasestationAdmin\"\xc3\x01\n" +
	"\x14AddTenantUserRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\bis_admin\x18\x03 \x01(\bR\aisAdmin\x12(\n" +
	"\x10is_endnode_admin\x18\x04 \x01(\bR\x0eisEndnodeAdmin\x120\n" +
	"\x14is_basestation_admin\x18\x05 \x01(\bR\x12isBasestationAdmin\"\x84\x01\n" +
	"\x15AddTenantUserResponse\x120\n" +
	"\vtenant_user\x18\x01 \x01(\v2\x0f.api.TenantUserR\n" +
	"tenantUser\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"L\n" +
	"\x14GetTenantUserRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xbf\x01\n" +
	"\x15GetTenantUserResponse\x120\n" +
	"\vtenant_user\x18\x01 \x01(\v2\x0f.api.TenantUserR\n" +
	"tenantUser\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x90\x02\n" +
	"\x17UpdateTenantUserRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1e\n" +
	"\bis_admin\x18\x03 \x01(\bH\x00R\aisAdmin\x88\x01\x01\x12-\n" +
	"\x10is_endnode_admin\x18\x04 \x01(\bH\x01R\x0eisEndnodeAdmin\x88\x01\x01\x125\n" +
	"\x14is_basestation_admin\x18\x05 \x01(\bH\x02R\x12isBasestationAdmin\x88\x01\x01B\v\n" +
	"\t_is_adminB\x13\n" +
	"\x11_is_endnode_adminB\x17\n" +
	"\x15_is_basestation_admin\"\xc2\x01\n" +
	"\x18UpdateTenantUserResponse\x120\n" +
	"\vtenant_user\x18\x01 \x01(\v2\x0f.api.TenantUserR\n" +
	"tenantUser\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"O\n" +
	"\x17DeleteTenantUserRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"c\n" +
	"\x16ListTenantUsersRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12,\n" +
	"\tpaginator\x18\x02 \x01(\v2\x0e.api.PaginatorR\tpaginator\"{\n" +
	"\x17ListTenantUsersResponse\x12/\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x0f.api.PaginationR\n" +
	"pagination\x12/\n" +
	"\x06result\x18\x02 \x03(\v2\x17.api.TenantUserListItemR\x06result2\xf9\x04\n" +
	"\x11TenantUserService\x12q\n" +
	"\rAddTenantUser\x12\x19.api.AddTenantUserRequest\x1a\x1a.api.AddTenantUserResponse\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/api/tenants/{tenant_id}/users\x12x\n" +
	"\rGetTenantUser\x12\x19.api.GetTenantUserRequest\x1a\x1a.api.GetTenantUserResponse\"0\x82\xd3\xe4\x93\x02*\x12(/api/tenants/{tenant_id}/users/{user_id}\x12\x84\x01\n" +
	"\x10UpdateTenantUser\x12\x1c.api.UpdateTenantUserRequest\x1a\x1d.api.UpdateTenantUserResponse\"3\x82\xd3\xe4\x93\x02-:\x01*\x1a(/api/tenants/{tenant_id}/users/{user_id}\x12z\n" +
	"\x10DeleteTenantUser\x12\x1c.api.DeleteTenantUserRequest\x1a\x16.google.protobuf.Empty\"0\x82\xd3\xe4\x93\x02**(/api/tenants/{tenant_id}/users/{user_id}\x12t\n" +
	"\x0fListTenantUsers\x12\x1b.api.ListTenantUsersRequest\x1a\x1c.api.ListTenantUsersResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/api/tenants/{tenant_id}/usersB\xac\x01\n" +
	"\x11io.splitstack.apiB\x0fTenantUserProtoP\x01Z3github.com/SplitStackServer/splitstack-grpc-api/api\xaa\x02\x14SplitStackServer.Api\xca\x02\x14SplitStackServer\\Api\xe2\x02 GPBMetadata\\SplitStackServer\\Apib\x06proto3"

var (
	file_api_tenant_user_proto_rawDescOnce sync.Once
	file_api_tenant_user_proto_rawDescData []byte
)

func file_api_tenant_user_proto_rawDescGZIP() []byte {
	file_api_tenant_user_proto_rawDescOnce.Do(func() {
		file_api_tenant_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_tenant_user_proto_rawDesc), len(file_api_tenant_user_proto_rawDesc)))
	})
	return file_api_tenant_user_proto_rawDescData
}

var file_api_tenant_user_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_tenant_user_proto_goTypes = []any{
	(*TenantUser)(nil),               // 0: api.TenantUser
	(*TenantUserListItem)(nil),       // 1: api.TenantUserListItem
	(*AddTenantUserRequest)(nil),     // 2: api.AddTenantUserRequest
	(*AddTenantUserResponse)(nil),    // 3: api.AddTenantUserResponse
	(*GetTenantUserRequest)(nil),     // 4: api.GetTenantUserRequest
	(*GetTenantUserResponse)(nil),    // 5: api.GetTenantUserResponse
	(*UpdateTenantUserRequest)(nil),  // 6: api.UpdateTenantUserRequest
	(*UpdateTenantUserResponse)(nil), // 7: api.UpdateTenantUserResponse
	(*DeleteTenantUserRequest)(nil),  // 8: api.DeleteTenantUserRequest
	(*ListTenantUsersRequest)(nil),   // 9: api.ListTenantUsersRequest
	(*ListTenantUsersResponse)(nil),  // 10: api.ListTenantUsersResponse
	(*timestamppb.Timestamp)(nil),    // 11: google.protobuf.Timestamp
	(*Paginator)(nil),                // 12: api.Paginator
	(*Pagination)(nil),               // 13: api.Pagination
	(*emptypb.Empty)(nil),            // 14: google.protobuf.Empty
}
var file_api_tenant_user_proto_depIdxs = []int32{
	11, // 0: api.TenantUserListItem.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: api.TenantUserListItem.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: api.AddTenantUserResponse.tenant_user:type_name -> api.TenantUser
	11, // 3: api.AddTenantUserResponse.created_at:type_name -> google.protobuf.Timestamp
	0,  // 4: api.GetTenantUserResponse.tenant_user:type_name -> api.TenantUser
	11, // 5: api.GetTenantUserResponse.created_at:type_name -> google.protobuf.Timestamp
	11, // 6: api.GetTenantUserResponse.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 7: api.UpdateTenantUserResponse.tenant_user:type_name -> api.TenantUser
	11, // 8: api.UpdateTenantUserResponse.created_at:type_name -> google.protobuf.Timestamp
	11, // 9: api.UpdateTenantUserResponse.updated_at:type_name -> google.protobuf.Timestamp
	12, // 10: api.ListTenantUsersRequest.paginator:type_name -> api.Paginator
	13, // 11: api.ListTenantUsersResponse.pagination:type_name -> api.Pagination
	1,  // 12: api.ListTenantUsersResponse.result:type_name -> api.TenantUserListItem
	2,  // 13: api.TenantUserService.AddTenantUser:input_type -> api.AddTenantUserRequest
	4,  // 14: api.TenantUserService.GetTenantUser:input_type -> api.GetTenantUserRequest
	6,  // 15: api.TenantUserService.UpdateTenantUser:input_type -> api.UpdateTenantUserRequest
	8,  // 16: api.TenantUserService.DeleteTenantUser:input_type -> api.DeleteTenantUserRequest
	9,  // 17: api.TenantUserService.ListTenantUsers:input_type -> api.ListTenantUsersRequest
	3,  // 18: api.TenantUserService.AddTenantUser:output_type -> api.AddTenantUserResponse
	5,  // 19: api.TenantUserService.GetTenantUser:output_type -> api.GetTenantUserResponse
	7,  // 20: api.TenantUserService.UpdateTenantUser:output_type -> api.UpdateTenantUserResponse
	14, // 21: api.TenantUserService.DeleteTenantUser:output_type -> google.protobuf.Empty
	10, // 22: api.TenantUserService.ListTenantUsers:output_type -> api.ListTenantUsersResponse
	18, // [18:23] is the sub-list for method output_type
	13, // [13:18] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_api_tenant_user_proto_init() }
func file_api_tenant_user_proto_init() {
	if File_api_tenant_user_proto != nil {
		return
	}
	file_api_common_proto_init()
	file_api_tenant_user_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_tenant_user_proto_rawDesc), len(file_api_tenant_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_tenant_user_proto_goTypes,
		DependencyIndexes: file_api_tenant_user_proto_depIdxs,
		MessageInfos:      file_api_tenant_user_proto_msgTypes,
	}.Build()
	File_api_tenant_user_proto = out.File
	file_api_tenant_user_proto_goTypes = nil
	file_api_tenant_user_proto_depIdxs = nil
}
